### ISSUE TITLE
Registry Route Doesn't Match Cert

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#1]
```
 v1 ping attempt failed with error: Get https://registry.svc.ci.openshift.org/v1/_ping: x509: certificate is valid for docker-registry-default.svc.ci.openshift.org, docker-registry.default.svc.cluster.local, 172.30.118.158, not registry.svc.ci.openshift.org. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry registry.svc.ci.openshift.org` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/registry.svc.ci.openshift.org/ca.crt
```

@smarterclayton

**Comment by deads2k** [comment]
and if you fake that with a host file, you get `v2 ping attempt failed with error: Get https://docker-registry-default.svc.ci.openshift.org:443/v2/: x509: certificate is valid for router.default.svc, router.default.svc.cluster.local, not docker-registry-default.svc.ci.openshift.org
`

**Comment by cgwalters** [comment]
This is going to block a "production" deployment of some of our CI infra (Homu at first) to this cluster.

**Comment by stevekuznetsov** [comment]
Renaming the route is simple - we'll get this fixed for the next redeploy, likely first week of January

**Comment by smarterclayton** [comment]
I just haven't bothered to automate this but until we get the docker issue sorted, it will be part of the next drop.

**Comment by kargakis** [comment]
Still an issue?
