### ISSUE TITLE
api.ci: can't get autoscaler logs, node cert invalid

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#1020]
```
$ oc logs cluster-autoscaler-fd6f4d8d7-c28ps -n kube-system
Error from server: Get https://origin-ci-ig-m-vqm9:10250/containerLogs/kube-system/cluster-autoscaler-fd6f4d8d7-c28ps/autoscaler: x509: certificate has expired or is not yet valid
```

/asssign @smarterclayton 
/kind bug

**Comment by smarterclayton** [comment]
The bootstrap autoapprover was down, so nodes certs expired.  I think the approver was down because the node cert expired for another reason, and i'm deploying a new AMI to the cluster that has a newer version of the kubelet that fixes the edge case where a node wedges its config.

**Comment by smarterclayton** [comment]
I *think* this should be resolved but I'm watching it.
