### ISSUE TITLE
azure: use project requests instead of new-project

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1056]
@openshift/sig-azure we should be using a [project request manifest](https://github.com/openshift/release/blob/78442331f793f033555f5d975093144716f90969/cluster/ci/config/roles.yaml#L4) for creating the `azure` namespace, instead of [new-project](https://github.com/openshift/release/blob/78442331f793f033555f5d975093144716f90969/Makefile#L278) since new-project updates the current context and there may be other context-dependent steps in the release Makefile that will get broken.

**Comment by mjudeikis** [comment]
people should not rely on the context and always specify the context for each component. But agreed, are you taking this one or can I?

**Comment by kargakis** [comment]
Not a high priority but if you want you can tackle it.
