### ISSUE TITLE
`make jobs` fails with podman

### ISSUE THREAD

**Issue by adambkaplan** [openshift/release#10915]
/kind bug

## What did you expect to happen?

When using podman, `make jobs` should succeed.

## What happened?

`make jobs` failed with error:

```
time="2020-08-11T19:02:03Z" level=fatal msg="Failed to process arguments" error="--from-release-repo error: /go/src/github.com/openshift/release/ci-operator/config is not an existing directory"
```

Unlike docker, podman will not create a destination directory if it does not exist already in the container. See [1].

## How can the error be reproduced?

`$ make jobs CONTAINER_ENGINE=podman`

## Is there anything else we need to know?

[1] https://github.com/containers/podman/issues/6234

**Comment by ArangoGutierrez** [comment]
Hey @adambkaplan is this still an issue?

**Comment by adambkaplan** [comment]
/close

I don't think this is an issue any more
