### ISSUE TITLE
need to auto-sync ci-operator templates to cluster

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#1114]
/cc @gabemontero 
/assign

**Comment by kargakis** [comment]
This is an issue on creation, right?

**Comment by stevekuznetsov** [comment]
Both on creation and sync -- I don't think we are config syncing this stuff yet

**Comment by stevekuznetsov** [comment]
No, literally the OpenShift Templates used by ci-op under cluster/ci/prow/config/jobs/ (????)
