### ISSUE TITLE
populate-configmaps.sh should use replace instead of apply

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1115]
All these configmaps sooner or later are getting replaced by the prow built-in config updater

https://github.com/openshift/release/blob/0385aee42f62dcbc0400d42e83d746a99c480fa9/cluster/ci/config/prow/plugins.yaml#L35-L104

@stevekuznetsov

**Comment by stevekuznetsov** [comment]
Built-in is going to be for updates, the script is for bootstrap? Why replace?

**Comment by kargakis** [comment]
Wrong use of apply, it needs to own updates too.

**Comment by kargakis** [comment]
I guess it doesn't really matter, just the extra apply annotation is redundant.
