### ISSUE TITLE
RHCOS users unable to authenticate

### ISSUE THREAD

**Issue by cgwalters** [openshift/release#1159]
I can `https://api.ci.openshift.org/oauth/token/request` OK, but several other people e.g. `dm0-`, `ashcrow`, `rahuls0720` just get `An authentication error occurred.` from the web page.

Is there something else that needs to be done to make them be able to auth?

**Comment by cgwalters** [comment]
See e.g. https://github.com/coreos/rhcos-apici/pull/1 which I thought would be sufficient.

**Comment by stevekuznetsov** [comment]
We delegate auth to GitHub via OAuth so if they're in the OpenShift org they can log in. Why are they logging into the cluster?

**Comment by stevekuznetsov** [comment]
FYI your private repo link 404's for me

**Comment by cgwalters** [comment]
> We delegate auth to GitHub via OAuth so if they're in the OpenShift org they can log in.

Makes sense; I'll double check that people are in the org.

> Why are they logging into the cluster?

Our team is going to be maintaining build infrastructure there.

**Comment by stevekuznetsov** [comment]
> Our team is going to be maintaining build infrastructure there.

Let's sync on your needs to make sure changes we make to the cluster for Origin CI don't adversely impact your workloads.

**Comment by stevekuznetsov** [comment]
@cgwalters was this resolved?

**Comment by ashcrow** [comment]
Adding @mike-nguyen who has been tracking this down.

**Comment by ashcrow** [comment]
@mike-nguyen Is it safe to say this is no longer an issue?

**Comment by mike-nguyen** [comment]
No one has been complaining so its fine to close.
