### ISSUE TITLE
Image pruning failure when spaces are appenend at end of container image ref

### ISSUE THREAD

**Issue by mjovanovic0** [openshift/release#11787]
/kind bug

## What did you expect to happen?
ImagePruner sucessfully prune images

## What happened?
Scheduled ImagePruner pod failed with CrashLoop and later with Failed status.

Logs:
```
W0914 09:36:53.086948       1 prune.go:577] Unable to parse DockerImageReference "<namespace redacted>/<image name redacted>@sha256:7d2c7e119781584ec57fef52ebdf8fb1a998288a64e05ab424b68fc8994aba2e         " of ReplicaSet[<namespace redacted>/<replica set name redacted>-7fdbcdb47b]: invalid reference format - skipping
Failed to build graph!

The following objects have invalid references:

  ReplicaSet[<namespace redacted>/<replica set name redacted>-7fdbcdb47b]: invalid container image reference "<namespace redacted>/<image name redacted>@sha256:7d2c7e119781584ec57fef52ebdf8fb1a998288a64e05ab424b68fc8994aba2e         ": invalid reference format

Either fix the references or delete the objects to make the pruner proceed.
error: failed to build graph - no changes made
```

## How can the error be reproduced?
Append unnecessary spaces at the end of image ref.

## Is there anything else we need to know?
This could be easly fixed with string trim before validation of image ref rather than fail to execute.

**Comment by alvaroaleman** [comment]
@mjovanovic0 thanks for reporting this bug, however this repository holds only release and test configuration for openshift and does not serve as as issue tracker for openshift. Please use https://bugzilla.redhat.com/ to report bugs against openshift.
/close
