### ISSUE TITLE
ci-operator: config is not in the correct place

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#1200]
I see the following that need to be migrated:

| from | to |
| - | - |
| `ci-operator/config/kubernetes/cluster-capacity` | `ci-operator/config/kubernetes-incubator/cluster-capacity` |
| `ci-operator/config/kubernetes/coredns` | `ci-operator/config/coredns/coredns` |
| `ci-operator/config/kubernetes/descheduler` | `ci-operator/config/kubernetes-incubator/descheduler` |
| `ci-operator/config/kubernetes/metrics-server` | `ci-operator/config/kubernetes-incubator/metrics-server` |

but are those configs for the upstream repos? or the downstream forks...

@smarterclayton we need to not have this issue please

**Comment by smarterclayton** [comment]
The authoritative branches for those repos will come from the openshift/
forks.  One or two of them might also have upstream ci-operator paths in a
few cases, but they are all logically separate (the e2e tests for an
upstream version != how origin / ocp would use them).

**Comment by stevekuznetsov** [comment]
Ok, so we need to migrate those to `openshift/$org-$repo` directories then ... We must ensure that all config for ci-operator is under `ci-operator/config/$org/$repo` for the _actual_ `$org/$repo` under test. I am not interested in vanity naming that makes generation and tooling more difficult.

**Comment by stevekuznetsov** [comment]
Work captured here: https://jira.coreos.com/browse/DPTP-140
/close
