### ISSUE TITLE
Automate SP secret reconcilation

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1297]
@openshift/sig-azure

**Comment by kargakis** [comment]
If not possible, we should at least document how to manually rotate the CI secret.

**Comment by stevekuznetsov** [comment]
We need a solution from Prow side as well to ingest the secret without the person doing the rotation needing access to namespace `ci`. Right now we can just create a namespace where you guys can deposit the secret and I can move it myself, we can write a controller for this too

**Comment by mjudeikis** [comment]
@stevekuznetsov we had a situation today where one of our test leaked secret into logs. We had to rotate it. I think for short term we could have something like secret mirroring controller. We manage secrets in our namespace - you mirror them where you need. And versus.

**Comment by stevekuznetsov** [comment]
This is captured in a JIRA ticket: https://jira.coreos.com/browse/DPTP-100

/close
