### ISSUE TITLE
PR History posted by the bot in openshift-azure has an incorrect link

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1334]
The PR test history posted by the bot in https://github.com/openshift/openshift-azure/pull/300#issuecomment-417571511 points to a broken link. I expected to see the test history of my PR.

@stevekuznetsov @bbguimaraes

**Comment by stevekuznetsov** [comment]
Can you please write down what you expected to see, what you saw, and why you think what you saw was in correct?

**Comment by kargakis** [comment]
The PR history posted by the bot in https://github.com/openshift/openshift-azure/pull/300#issuecomment-417571511 points to a broken link. I expected to see the test history of my PR.

**Comment by stevekuznetsov** [comment]
Implementation details: 

The template [here](https://github.com/openshift/release/blob/01be0e6781b630a05a8a7d468163a24a805a27f9/ci-operator/jobs/infra-periodics.yaml#L28) needs to be edited to link to the correct page. It should contain logic to add `org_repo/` to the URL like the other templates do: `{{if ne .Spec.Refs.Repo "origin"}}/{{.Spec.Refs.Org}}_{{.Spec.Refs.Repo}}/{{end}}`
