### ISSUE TITLE
/retest may result in returning the same failed test output

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1335]
When I /retest a PR, I expect the failed steps of a failed job to be retried. This is not always the case with the ci-operator: when I /retest immediately after a failure, the old failure is getting reused in the new test run.

Example:
first job: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/315/pull-ci-openshift-azure/564/build-log.txt
second job: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/315/pull-ci-openshift-azure/566/build-log.txt

/kind bug

**Comment by stevekuznetsov** [comment]
Can you please link to the:
 - first job that ran and used correct output
 - stable link to a job that ran and re-used a test

barring that, just paste the logs here

**Comment by stevekuznetsov** [comment]
If the links to Gubernator from deck are not correct, we need to submit a bug on the URL template

**Comment by stevekuznetsov** [comment]
Also like specifically which target was not re-run, which did you expect, how is job configured (which --target are present) etc

**Comment by kargakis** [comment]
I have no access to my PR history because of https://github.com/openshift/release/issues/1334

**Comment by kargakis** [comment]
> Also like specifically which target was not re-run, which did you expect, how is job configured (which --target are present) etc

Job config is [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/openshift-azure/master.json) + [here](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml) + [here](https://github.com/openshift/release/blob/master/ci-operator/templates/cluster-launch-e2e-azure.yaml). The e2e-azure target had failed and in a subsequent /retest, the bot posted the same ci-operator log back.

**Comment by kargakis** [comment]
Here is an example:
first job: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/315/pull-ci-openshift-azure/564/build-log.txt
second job: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/315/pull-ci-openshift-azure/566/build-log.txt

**Comment by kargakis** [comment]
And another one:
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/283/pull-ci-openshift-azure/593/build-log.txt
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/283/pull-ci-openshift-azure/595/build-log.txt

**Comment by bbguimaraes** [comment]
https://jira.coreos.com/browse/DPTP-185

**Comment by stevekuznetsov** [comment]
Tracked in JIRA, closing this
/close
