### ISSUE TITLE
CI-test does not create logs and artifacts

### ISSUE THREAD

**Issue by nhosoi** [openshift/release#1337]
I'm running the CI-tests from this PR/1314.
https://github.com/openshift/origin-aggregated-logging/pull/1314

The tests ci/openshift-jenkins/logging and ci/openshift-jenkins/json-file are failing, but following the [Details link](https://openshift-gce-devel.appspot.com/build/origin-/pr-logs/pull/openshift_origin-aggregated-logging/1314/test_pull_request_origin_aggregated_logging_json_file/1011/) just takes us to the page which has this error: 
```
Unable to load build details from gs://origin-/pr-logs/pull/openshift_origin-aggregated-logging/1314/test_pull_request_origin_aggregated_logging_json_file/1011
This may mean the job has not yet uploaded any artifacts, or that it failed to upload. Take a look at the job in Jenkins for more information.
```
Could you please help us to get the logs and artifacts?
/kind bug

/area test-artifacts

/area test-results

/area webpages

## What did you expect to happen?

We need to get the logs and artifacts for debugging.

## What happened?

Logs and artifacts are missing.

## How can the error be reproduced?

We reran /retest several times, but we got the same issue.

Thanks for your help, in advance.

**Comment by stevekuznetsov** [comment]
@nhosoi thanks for the report! We had an issue with how we linked to job reports, it should be fixed with https://github.com/openshift/release/pull/1342 -- can you please `/retest` and re-open this issue if you notice the links are still not working?
/close
