### ISSUE TITLE
openshift-samples  Degraded / restart master

### ISSUE THREAD

**Issue by tronicanet** [openshift/release#13470]
1. when I finish installing okd I get the operator openshift-samples Degraded.
2. when a master is restarted (in an all-in-one machine), the service is down and even if I restart kubelet it does not lift.
3. If I take a snapshot of the machine when it lifts, it remains with the degraded operators.

- kube-apiserver    **updating**

- openshift-controller-manager    **updating**

- operator-lifecycle-manager-packageserver **updating**

- monitoring  **updating**

**Comment by alvaroaleman** [comment]
@tronicanet  thanks for reporting this bug, however this repository holds only release and test configuration for openshift and does not serve as as issue tracker for openshift. Please use https://bugzilla.redhat.com/ to report bugs against openshift/OKD
/close
