### ISSUE TITLE
Error starting Jenkins job for origin-web-console, enterprise-3.9 PRs

### ISSUE THREAD

**Issue by spadgett** [openshift/release#1352]
/kind bug

/area test-execution

## What did you expect to happen?

Jenkins tests should run in the origin-web-console enterprise-3.9 branch.

## What happened?

Got error:

> Error starting Jenkins job.

https://github.com/openshift/origin-web-console/pull/3058

## How can the error be reproduced?

Open a PR against origin-web-console enterprise-3.9 branch

cc @stevekuznetsov @jhadvig

**Comment by stevekuznetsov** [comment]
The configuration is trying to start the `test_pull_request_origin_web_console_39` job:

https://github.com/openshift/release/blob/c864dd032437cfd79015c2ad60c00cba43b4c3f1/ci-operator/jobs/openshift/origin-web-console/openshift-origin-web-console-presubmits.yaml#L3-L12

However the Jenkins [page](https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_web_console_39) 404's and there is no job configured in [aos-cd-jobs](https://github.com/openshift/aos-cd-jobs/tree/master/sjb/config/test_cases). Did you create the Jenkins job?

**Comment by stevekuznetsov** [comment]
@spadgett ping

**Comment by spadgett** [comment]
We used to have one job for PRs to any branch. Is this still possible or do we need a separate job for each?

**Comment by stevekuznetsov** [comment]
@smarterclayton this looks like a you problem

**Comment by smarterclayton** [comment]
@spadgett yeah, it would be best if you fork the job.
