### ISSUE TITLE
could not determine if template instance was ready: failed to create objects: rolebindings.authorization.openshift.io "e2e-azure-image-puller" already exists

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1403]
Failed test with:
```
error: could not run steps: could not wait for template instance to be ready: could not determine if template instance was ready: failed to create objects: rolebindings.authorization.openshift.io "e2e-azure-image-puller" already exists
pods "e2e-azure" already exists
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/374/pull-ci-openshift-azure-e2e/4/build-log.txt
/kind bug
@petr-muller @bbguimaraes @stevekuznetsov @droslean

**Comment by bbguimaraes** [comment]
Is this the same as #1335?

**Comment by kargakis** [comment]
This was caused becaused I added a second template in a job that applies the same resources as the first one so the job failed because the rolebinding already exists?

**Comment by bbguimaraes** [comment]
These two have to be unique for all jobs in the same namespace:

https://github.com/openshift/release/blob/3dc81783f21c71c7756bc451956c4837cafa278c/ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml#L20
https://github.com/openshift/release/blob/3dc81783f21c71c7756bc451956c4837cafa278c/ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-presubmits.yaml#L30-L31

**Comment by kargakis** [comment]
Yeah, figured that out the hard way.

**Comment by stevekuznetsov** [comment]
We need validation for this

**Comment by stevekuznetsov** [comment]
@kargakis what does the re-open here mean?

**Comment by kargakis** [comment]
> We need validation for this

**Comment by stevekuznetsov** [comment]
There's a JIRA ticket for it, this can be closed

/close
