### ISSUE TITLE
failure to gather artifacts from template job

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1438]
I have seen [this](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/389/pull-ci-openshift-azure-e2e/66/build-log.txt) a couple of times already. Basically, the teardown container of [our template](https://github.com/openshift/release/blob/293c50542c276a10156fa9474ec0793a4e446d16/ci-operator/templates/openshift-azure/cluster-launch-e2e-azure.yaml) exits and one hour later whichever component is responsbile for gathering artifacts, tries to get the artifacts from the container but the container does not exist at that point.
```console
2018/09/10 23:57:16 Tagging sync into stable
2018/09/11 01:56:17 Container teardown in pod e2e-azure completed successfully
2018/09/11 02:56:02 Copying artifacts from e2e-azure into /logs/artifacts/e2e-azure
2018/09/11 02:56:02 error: unable to signal to artifacts container to terminate in pod e2e-azure, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")
2018/09/11 02:56:02 error: unable to retrieve artifacts from pod e2e-azure: could not read gzipped artifacts: unable to upgrade connection: container not found ("artifacts")
E0911 02:56:07.365548      11 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".155338ff614b180e", GenerateName:"", Namespace:"ci-op-p70nndjr", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"ci-op-p70nndjr", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"CiJobFailed", Message:"Running job pull-ci-openshift-azure-e2e for PR https://github.com/openshift/openshift-azure/pull/389 in namespace ci-op-p70nndjr from author jim-minter", Source:v1.EventSource{Component:"ci-op-p70nndjr", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbedde991d5ac120e, ext:10956847317661, loc:(*time.Location)(0x19b7fc0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbedde991d5ac120e, ext:10956847317661, loc:(*time.Location)(0x19b7fc0)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events ".155338ff614b180e" is forbidden: unable to create new content in namespace ci-op-p70nndjr because it is being terminated' (will not retry!)
```
I would expect to get artifacts gathered on time.

@stevekuznetsov @bbguimaraes @petr-muller @droslean 

/kind bug
/area test-artifacts

**Comment by stevekuznetsov** [comment]
For whoever looks at this -- code for the artifact retrieval is here: https://github.com/openshift/ci-operator/blob/master/pkg/steps/artifacts.go

**Comment by kargakis** [comment]
And another one: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_openshift-azure/477/pull-ci-openshift-azure-e2e/225/build-log.txt

If you want to add any debug logging in that area of code, I'd be happy to enable them in our jobs.

**Comment by stevekuznetsov** [comment]
@kargakis unlikely we will have time -- can you add it?

**Comment by stevekuznetsov** [comment]
```
2018/11/27 11:27:13 Running pod e2e-gcp
2018/11/27 11:52:23 Container setup in pod e2e-gcp completed successfully
2018/11/27 13:33:03 Container teardown in pod e2e-gcp completed successfully
2018/11/27 14:27:11 Copying artifacts from e2e-gcp into /logs/artifacts/e2e-gcp
2018/11/27 14:27:11 error: unable to signal to artifacts container to terminate in pod e2e-gcp, triggering deletion: could not run remote command: unable to upgrade connection: container not found ("artifacts")
2018/11/27 14:27:11 error: unable to retrieve artifacts from pod e2e-gcp: could not read gzipped artifacts: 
2018/11/27 14:27:17 Ran for 3h9m24s
error: could not run steps: could not wait for pod to complete: could not wait for pod completion: pod e2e-gcp was already deleted
```

Is this a race with another job deleting the pod? Or is there something garbage collecting things? That test took ... forever ...

/cc @bbguimaraes @petr-muller

**Comment by gabemontero** [comment]
I'll initiate new jenkins e2e in a bit and log into api.ci and try to tail the test pod logs .... get a sense as to what is going on

**Comment by gabemontero** [comment]
So https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/744/pull-ci-openshift-jenkins-master-e2e-gcp/100 is still in progress ... teardown says it is already completed but it is still cooking

**Comment by gabemontero** [comment]
As is https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/745/pull-ci-openshift-jenkins-master-e2e-gcp/101

That project is still up though, and the e2e-gcp has 
```
e2e-gcp                           3/5       InvalidImageName   0          31m
```

So something else with our last change is most likely wrong with my last attempted fix.  I'll quit cluttering this issue then.
