### ISSUE TITLE
tnozicka/openshift-acme: Template.template.openshift.io "e2e-gcp" is invalid

### ISSUE THREAD

**Issue by tnozicka** [openshift/release#1464]
/kind bug
/area test-execution
## What did you expect to happen?
Run the e2e

## What happened?
```
could not wait for template instance to be ready: could not determine if template instance was ready: failed to create objects: Template.template.openshift.io "e2e-gcp" is invalid: [template.parameters[3]: Required value: template.parameters[3]: parameter IMAGE_FORMAT is required and must be specified, template.parameters[4]: Required value: template.parameters[4]: parameter IMAGE_ANSIBLE is required and must be specified, template.parameters[6]: Required value: template.parameters[6]: parameter IMAGE_CLI is required and must be specified]
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/tnozicka_openshift-acme/79/pull-ci-openshift-acme-e2e/4

## How can the error be reproduced?
`/test e2e` on https://github.com/tnozicka/openshift-acme/pull/79

## Is there anything else we need to know?
This job haven't run successfully yet, just trying to set it up. @stevekuznetsov says it looks like a bug with ci-operator.

**Comment by tnozicka** [comment]
@stevekuznetsov thanks for finding the root cause, validation would be nice for sure :)

**Comment by petr-muller** [comment]
The error message is not exactly helpful then, too.
