### ISSUE TITLE
openshift/release CI should validate duplicate keys in config files

### ISSUE THREAD

**Issue by tnozicka** [openshift/release#1479]
/kind bug

While editing https://github.com/openshift/release/blob/359d82a240fdf1d7999d104fd51af5d4c017eae7/cluster/ci/config/prow/plugins.yaml#L44-L45 my IDE is screaming for duplicate keys in that file, might not be the only one.

Examples:
`openshift/builder:`, `ci-operator/config/openshift/cluster-samples-operator/*.yaml:`

This should be enforced in a presubmit checking those files.

**Comment by stevekuznetsov** [comment]
@tnozicka could you please migrate this to `kubernetes/test-infra` and `/cc` me there?

**Comment by stevekuznetsov** [comment]
Looks like a fundamental issue with the upstream k8s YAML loading libraries -- @deads2k how do we handle this in apimachinery?
