### ISSUE TITLE
Remove unrelated builds from the ci namespace

### ISSUE THREAD

**Issue by kargakis** [openshift/release#152]
kube-state-metrics, kubernetes-autoscaler, node-exporter, prometheus, prometheus-alertmanager, oauth-proxy, and their binary builds

All of the above builds should probably move into a separate namespace as they are not directly related to any of the services we run inside ci (and shouldn't). Ever since we moved prow builds alongside their deployments, it has been really hard to go through the list of builds in the ci namespace.

@stevekuznetsov @smarterclayton

**Comment by stevekuznetsov** [comment]
Yeah, unclear. Do we just want to have a namespace per project? Or one with all of them? I created an issue on the web console, there isn't a good overview of chained builds today that don't result in a deployment. At the same time though we want a good dashboard to keep track of release pipelines for all projects. Soon Origin will be in that mix. For ease of use in downstream projects, I think we should either have one aggregated namespace for those image streams or one namespace per project.

**Comment by smarterclayton** [comment]
I don't really want one namespace per, that gets annoying.  These are all
related builds.  Create separate namespaces for different people or
different security zones, but don't do it because you can.

This is also just a limitation of the current UI - we should take feedback
to sam about how certain sized lists start to be less useful.

**Comment by stevekuznetsov** [comment]
Issue I created: https://github.com/openshift/origin-web-console/issues/2008

**Comment by kargakis** [comment]
This is not about the console only. `oc get builds` is no fun no more.

**Comment by kargakis** [comment]
Or `oc get po`. I end up running `kc get po` just because `kubectl` defaults to `--show-all=false`. :)
