### ISSUE TITLE
azure: bootstrap autoapprover fails to come up in node build job

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1557]
```
1m          11m          46        bootstrap-autoapprover-769f756747-vx75k.1555c67d22a9dc16   Pod                      Warning   FailedCreatePodSandBox   kubelet, master-000001   Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.access.redhat.com/openshift3/ose-pod:v3.10.0": open /etc/docker/certs.d/registry.access.redhat.com/redhat-ca.crt: no such file or directory
```
@kwoodson @mjudeikis 

/kind bug
/sig azure

**Comment by kargakis** [comment]
Hrm, it seems that we are trying to build a centos7 image and pull enterprise images.

**Comment by mjudeikis** [comment]
Are we doing anything with `oreg_url` here:
https://github.com/openshift/openshift-ansible/blob/master/playbooks/azure/openshift-cluster/build_node_image.yml#L84-L88 ?

**Comment by kargakis** [comment]
We used to use that in acs-engine, I don't think we use it in openshift-azure. Probably we need to start using it.

**Comment by mjudeikis** [comment]
wtf? how they manage to deviate?

**Comment by kargakis** [comment]
```
[root@master-000000 origin]# cat master/master-config.yaml | grep format
  format: docker.io/openshift/origin-${component}:${version}
[root@master-000000 origin]# cat node/node-config.yaml | grep format
  format: registry.access.redhat.com/openshift3/ose-${component}:${version}
```

**Comment by kargakis** [comment]
cc @jim-minter may be related to https://github.com/openshift/openshift-azure/pull/414

I still can't understand why the config map translation doesn't use `DEPLOY_OS`.

**Comment by kargakis** [comment]
https://github.com/openshift/release/blob/13517c7eb2290c381124e108f026a55f7a3325ae/ci-operator/templates/openshift/openshift-azure/build-azure-image.yaml#L166-L218

**Comment by kargakis** [comment]
I think I know what's the issue. The config map is created by sync, and sync does not use `DEPLOY_OS` :)

**Comment by kargakis** [comment]
Closing in favor of https://github.com/openshift/openshift-azure/issues/487
