### ISSUE TITLE
e2e parallelization needs to be configurable

### ISSUE THREAD

**Issue by bparees** [openshift/release#1578]
We have tests that, when run in the default parallelization of 30, fail because we exhaust the cluster resources.

It should be possible to decide what level of ginkgo parallelization to choose, in the same way that we choose the `FOCUS`.

/cc @gabemontero 

@coverprice 
@stevekuznetsov

**Comment by stevekuznetsov** [comment]
Do you have any links to the tests in question?

**Comment by stevekuznetsov** [comment]
It's odd that specific workloads end up breaking. Can we fix those workloads instead? Can a cluster of the size we're starting not handle 30 builds in parallel?

**Comment by bparees** [comment]
it's not 30 builds, it's 30 jenkins servers plus their slave pods plus their NFS servers plus the builds they run, etc.

it's the "openshift pipeline" focus.

**Comment by stevekuznetsov** [comment]
Is this an issue with resource requests and limits? If the tests set those appropriately, won't they effectively get serialized by the scheduler?

/assign @smarterclayton

**Comment by bparees** [comment]
> Is this an issue with resource requests and limits? If the tests set those appropriately, won't they effectively get serialized by the scheduler?

no, we'll just have deployments timeout because pods don't come up in time because they couldn't be scheduled, and then the tests will fail.

**Comment by stevekuznetsov** [comment]
What happens in production in that case? If the pods stay in pending too long the deployment fails? Can the TTL on the deployment be changed?
