### ISSUE TITLE
labels in openshift/cluster-openshift-apiserver-operator are all grey

### ISSUE THREAD

**Issue by deads2k** [openshift/release#1579]
labels created in https://github.com/openshift/cluster-openshift-apiserver-operator are all grey

This is not urgent, but it is weird.

**Comment by tnozicka** [comment]
Either the cronjob that is suppose to sync it from https://github.com/openshift/release/blob/8aefab5609aa19dde89b3a5842df0f531ba8e921/cluster/ci/config/prow/labels.yaml#L1 is broken, or there are permission issues

/cc @stevekuznetsov @bbguimaraes

**Comment by tnozicka** [comment]
labels are synced now
/close
