### ISSUE TITLE
GCP jobs need more resources or less parallelism

### ISSUE THREAD

**Issue by bparees** [openshift/release#1631]
Looking at the most recent couple of runs of my new GCP-based extended test job that runs our builds tests (which previously weren't run in a GCP env):

https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/pull/openshift_builder/4/pull-ci-openshift-builder-master-extended-builds/

The failures are basically inconsistent across the runs w/ a couple themes being that our heaviest tests (the ones that rely on coordination of multiple pods/builds) are the ones that fail (but don't fail consistently).  These tests are completely stable in their AWS job form.

I believe this is due to insufficient resources in the GCP cluster.  We saw similar issues in our jenkins pipeline test job and resolved them by reducing the parallelism from 30 to 10.

Yes, I can do more investigation here, but the easiest way to confirm whether it's a resource issue would be to either:

1) reduce the parallelism in the GCP template
or
2) increase the nodes/resources in the GCP cluster that is launched.

I am requesting we do one of those things before i invest significant time in this investigation.

**Comment by bparees** [comment]
@smarterclayton @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Feel free to fork the template and reduce parallelism.

**Comment by bparees** [comment]
That's an unsustainable long term solution. Then you'll update the primary
template and tell me I'm on my own to maintain my special case. We've been
down this road too many times already and I don't want to own any more
snowflakes.


Ben Parees | OpenShift

**Comment by smarterclayton** [comment]
Don’t fork the template. Let’s find out how much to increase size by

**Comment by smarterclayton** [comment]
I really doubt your jobs are special.  Let’s find out first

**Comment by bparees** [comment]
@smarterclayton ok...  what's the current resource allocation for the GCP cluster?  what can we bump it to?

**Comment by stevekuznetsov** [comment]
Isn't this a dupe of #1578

**Comment by bparees** [comment]
i'd say they are related, not a dupe.

if you deliver on https://github.com/openshift/release/issues/1578 then you can close this one, but since i doubt you're going to deliver on https://github.com/openshift/release/issues/1578 any time soon, we need an immediate solution.

**Comment by bparees** [comment]
making it configurable here:
https://github.com/openshift/release/pull/1652
