### ISSUE TITLE
Enable copying secrets across namespaces

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1634]
Not sure this is tracked anywhere so I am opening this issue. We want to be able to have full control over our CI secrets via a namespace in the CI cluster where our team has access. Then we can build jobs on top of those secrets to automate rotation. Having something like a controller in the `ci` namespace that copies secrets from other namespaces, driven by config in openshift/release, would be very helpful.

@stevekuznetsov @bbguimaraes @droslean @petr-muller 
cc @mjudeikis @kwoodson @jim-minter 
/kind feature

**Comment by stevekuznetsov** [comment]
Features need to go into JIRA tickets. We already have this tracked: https://jira.coreos.com/browse/DPTP-100

/close

**Comment by stevekuznetsov** [comment]
Please search the JIRA board first.
