### ISSUE TITLE
When building locally I get a warning "permission to update the namespace"

### ISSUE THREAD

**Issue by asalkeld** [openshift/release#1636]
../ci-operator/ci-operator --config ci-operator/config/openshift/azure-misc/master.yaml --git-ref asalkeld/azure-misc@move-src-go --namespace asalkeld-test
2018/09/24 19:31:08 Resolved asalkeld/azure-misc@move-src-go to commit b755a09afa1b263382e828eb96cb1336bec49adf
2018/09/24 19:31:08 Resolved source https://github.com/asalkeld/azure-misc to move-src-go@b755a09a
2018/09/24 19:31:10 Resolved openshift/release:golang-1.10 to sha256:0d3cef65fd05b6929397022b809ad32dc08ea51fe7a0523aca2de10467649679
2018/09/24 19:31:10 Resolved azure/plugin-base:latest to sha256:872c657890a1d075378423d5322c8fc6829a02974e5eae5d75e2f397091567ad
2018/09/24 19:31:10 Using namespace asalkeld-test
2018/09/24 19:31:10 Running [input:root], [input:base], [release-inputs], src, bin, purge, prometheus-sidecar, [output:stable:purge], [output:stable:prometheus-sidecar], [images], [release:latest]
2018/09/24 19:31:10 Creating namespace asalkeld-test
2018/09/24 19:31:10 Setting a soft TTL of 1h0m0s for the namespace
2018/09/24 19:31:10 Setting a hard TTL of 12h0m0s for the namespace
**2018/09/24 19:31:11 warning: Could not mark the namespace to be deleted later because you do not have permission to update the namespace (details: namespaces "asalkeld-test" is forbidden: User "asalkeld" cannot update namespaces in the namespace "asalkeld-test": no RBAC policy matched)**
2018/09/24 19:31:11 Setting up pipeline imagestream for the test
2018/09/24 19:31:11 Populating secrets for test
2018/09/24 19:31:11 Tagging openshift/release:golang-1.10 into pipeline:root
2018/09/24 19:31:11 Tagging azure/plugin-base:latest into pipeline:base
2018/09/24 19:31:11 Tagged release images from openshift/origin-v3.10:${component}, images will be pullable from registry.svc.ci.openshift.org/asalkeld-test/stable:${component}
E0924 19:31:11.871925   16691 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:".15574c19d5eb3324", GenerateName:"", Namespace:"asalkeld-test", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"asalkeld-test", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"CiJobStarted", Message:"Running job dev for PRs () in namespace asalkeld-test from authors ()", Source:v1.EventSource{Component:"asalkeld-test", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbee24997e4c93d24, ext:3663223010, loc:(*time.Location)(0x196c3c0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbee24997e4c93d24, ext:3663223010, loc:(*time.Location)(0x196c3c0)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "asalkeld" cannot create events in the namespace "asalkeld-test": no RBAC policy matched' (will not retry!)
2018/09/24 19:31:12 Building src

**Comment by droslean** [comment]
@asalkeld You run the ci-operator locally, which means that it's using your account when it tries to give TTL to the namespace, which you don't have access.

**Comment by droslean** [comment]
We can't allow to the user to be able to add TTL to the namespaces. Not even give the user temporarily permissions to do it and then revoke. In both cases is not secure. The best we can do is to output a better warning.

**Comment by droslean** [comment]
@asalkeld Are you using the latest ci-operator?

**Comment by asalkeld** [comment]
@droslean I just cloned the repo and built the binary. This is not a big deal to me, @kargakis suggested that I raise an issue.

**Comment by droslean** [comment]
when running locally, please use --dry-run=true.

**Comment by stevekuznetsov** [comment]
@asalkeld yeah just clean up your namespace yourself.
