### ISSUE TITLE
Kill PUSH_SECRET in image templates

### ISSUE THREAD

**Issue by smarterclayton** [openshift/release#166]
Or make it more useful.  Most people never need it if they're building to the same image stream, it's annoying.

**Comment by csrwng** [comment]
The image templates are meant to be instantiated by a Jenkins pipeline. When we create a build directly, the push/pull secrets don't get automatically populated (as when you instantiate one from a buildconfig). Should we change the build controller to do so?

**Comment by csrwng** [comment]
@smarterclayton ^^ created origin issue: https://github.com/openshift/origin/issues/16609
