### ISSUE TITLE
Too many jobs racing with TTL controller

### ISSUE THREAD

**Issue by smarterclayton** [openshift/release#1671]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/21057/pull-ci-origin-e2e-gcp/3970/

Looks like the job was racing with the TTL controller.  No idea why, since you'd have to start the next run exactly one hour after the last job completed, which should be really rare.

**Comment by stevekuznetsov** [comment]
There's a JIRA for this -- we don't check at the outset if we're hitting a namespace in deletion. If the namespace finalizers are taking a while, the window for this is larger. test/integration/data/output/jobs/super/duper/super-duper-release-3.10-presubmits.yaml
