### ISSUE TITLE
Jenkins proxy needs to be able to decode booleans from Jenkins

### ISSUE THREAD

**Issue by kargakis** [openshift/release#169]
https://github.com/kubernetes/test-infra/pull/4630 will force prow to use the Jenkins proxy for all Jenkins requests (queue requests are bypassing it so far, see https://github.com/kubernetes/test-infra/issues/4366#issuecomment-329167063). Inside the proxy, we are [unmarshaling](https://github.com/openshift/release/blob/b56c70efef1dbc11897489a40839d97694e01690/tools/jenkins-proxy/proxy.go#L329) all queue responses from Jenkins in order to mux into a single response that will be returned to prow. The proxy assumes that all parameters values it gets from Jenkins are [strings](https://github.com/openshift/release/blob/b56c70efef1dbc11897489a40839d97694e01690/tools/jenkins-proxy/proxy.go#L293). We need to support booleans so we won't clobber the unmarshaling because some of our jobs are using them (luckily enough none that runs via prow today).
```
2017/09/22 10:48:18 Cannot list from queues: json: cannot unmarshal bool into Go struct field .value of type string, (Request: GET /queue/api/json?tree=items[task[name],actions[parameters[name,value]]])
```
This results in 502s in the jenkins-operator which will abort a sync with https://github.com/kubernetes/test-infra/pull/4630 instead of failing jobs that it is doing today.
```
{"error":"error listing jenkins builds: response not 2XX: 502 Bad Gateway","level":"error","msg":"Error syncing.","time":"2017-09-22T10:48:21Z"}
```
We also need something like https://github.com/kubernetes/test-infra/issues/4691 upstream, and probably make the jenkins-operator able to decode Jenkins booleans, too.

@stevekuznetsov 
/kind bug
/area prow

**Comment by stevekuznetsov** [comment]
Surprising since they _are_ strings, no?

**Comment by kargakis** [comment]
No, they are not. Example:
```json
{
  "_class": "hudson.model.Queue",
  "items": [
    {
      "_class": "hudson.model.Queue$BlockedItem",
      "actions": [
        {
          "_class": "hudson.model.ParametersAction",
          "parameters": [
            {
              "_class": "hudson.model.StringParameterValue",
              "name": "buildId",
              "value": "blabla"
            }
          ]
        },
        {
          "_class": "hudson.model.CauseAction"
        },
        {},
        {}
      ],
      "id": 2,
      "task": {
        "_class": "hudson.model.FreeStyleProject",
        "name": "free"
      }
    },
    {
      "_class": "hudson.model.Queue$BlockedItem",
      "actions": [
        {
          "_class": "hudson.model.ParametersAction",
          "parameters": [
            {
              "_class": "hudson.model.StringParameterValue",
              "name": "buildId",
              "value": "blabla"
            },
            {
              "_class": "hudson.model.BooleanParameterValue",
              "name": "RUN_EXTENDED",
              "value": false
            }
          ]
        },
        {
          "_class": "hudson.model.CauseAction"
        },
        {},
        {}
      ],
      "id": 3,
      "task": {
        "_class": "hudson.model.FreeStyleProject",
        "name": "free"
      }
    }
  ]
}
```
We need to handle the conversion outside of json.Unmarshal.

**Comment by stevekuznetsov** [comment]
Jenkins is literally the worst.

**Comment by kargakis** [comment]
Btw, the job that caused this issue shouldn't run in the first place: 
https://ci.openshift.redhat.com/jenkins/job/test_origin_branch/

I remember that I had disabled it when we enabled postsubmits, not sure why it's enabled again.
https://deck-ci.svc.ci.openshift.org/?type=postsubmit

**Comment by stevekuznetsov** [comment]
@kargakis i did a push of everything after the jenkins reboot so we had up-to-date configs
