### ISSUE TITLE
merge bot not loving containers/libpod

### ISSUE THREAD

**Issue by baude** [openshift/release#1751]
/kind question

We recently starting using the openshift CI for containers/libpod (https://github.com/containers/libpod/).  We are not seeing the merge bot do its thing for our project and I would like some help troubleshooting what might be going on (config/user error/etc).

**Comment by baude** [comment]
A good example of a PR is -> https://github.com/containers/libpod/pull/1556

**Comment by smarterclayton** [comment]
@bbguimaraes do you have time to look at this?

**Comment by smarterclayton** [comment]
Just at a casual glance, I don't see a tide entry in GitHub CI status, which probably means you missed setting up the tide config.

**Comment by baude** [comment]
tide config == https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml#L114  ?

**Comment by stevekuznetsov** [comment]
We are seeing 404 on setting the status. Unclear what that means. I'll look tomorrow

**Comment by stevekuznetsov** [comment]
Isn't the `tide` context failing due to 
```
 {"component":"tide","controller":"status-update","error":"status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/statuses/#create-a-status\"}","level":"error","msg":"Failed to set status context from \"\" to \"pending\".","org":"containers","pr":1556,"repo":"libpod","sha":"c71637a1c1e79b07f8d015f456fa5fd921a06193","time":"2018-09-28T14:24:03Z"}
```

We should still add the context and list the failing tests in all cases

**Comment by bbguimaraes** [comment]
I think they are two separate issues. I had a more careful look at the code later and you're right, the context should still be added.

The failing tests were corrected and we're now getting past the issue I posted above, but we are still getting 404s.

**Comment by stevekuznetsov** [comment]
Yeah we're getting 404 on adding the status and merging:

```
 {"component":"tide","controller":"status-update","error":"status code 404 not one of [201], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/repos/statuses/#create-a-status\"}","level":"error","msg":"Failed to set status context from \"\" to \"success\".","org":"containers","pr":1556,"repo":"libpod","sha":"c71637a1c1e79b07f8d015f456fa5fd921a06193","time":"2018-09-28T15:24:51Z"}
 {"base-sha":"e7e81e6448dc4ad1d53ef51e8175d717d18a8197","branch":"master","component":"tide","controller":"sync","error":"status code 404 not one of [200 405 409], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button\"}","level":"error","msg":"Merge failed.","org":"containers","pr":1556,"repo":"libpod","sha":"c71637a1c1e79b07f8d015f456fa5fd921a06193","time":"2018-09-28T15:24:57Z"}
```

@baude something is wrong with the robot configuration in github
