### ISSUE TITLE
GCP extended test env is unreliable

### ISSUE THREAD

**Issue by bparees** [openshift/release#1759]
I don't know who to chase for all these things, but i've run a series of extended tests against the same PR w/ a random set of failures.  You can see the whole test history here:

https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/pull/openshift_builder/4/pull-ci-openshift-builder-master-extended-builds/

Failures include:
Cannot reach the api server:
```
Post https://internal-api.ci-op-ts6fl7dc-454ab.origin-ci-int-gce.dev.rhcloud.com:8443/apis/template.openshift.io/v1/namespaces/e2e-test-jenkins-pipeline-gbb4l/processedtemplates: dial tcp 35.185.116.42:8443: connect: no route to host",
```

Cannot access something behind a route:
```
error: fatal: unable to access 'https://gitserver-e2e-test-build-sti-private-repo-qhc9h.apps.ci-op-8trqf3lp-454ab.origin-ci-int-gce.dev.rhcloud.com/ruby-hello-world/': Failed connect to gitserver-e2e-test-build-sti-private-repo-qhc9h.apps.ci-op-8trqf3lp-454ab.origin-ci-int-gce.dev.rhcloud.com:443; Connection refused
```

A timeout waiting for a build to finish (after waiting 10 minutes):
```
/tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/jenkins_plugin.go:389
Expected error:
    <*errors.errorString | 0xc420093560>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/jenkins_plugin.go:411
```

Networking issues reaching rubygems (*could* be a rubygems issue, but given the instability of everything else i'm not inclined to bet on that right now):

```
2018-09-27T21:48:32.118305818Z Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/i18n-0.9.3.gem)
2018-09-27T21:48:33.238425532Z An error occurred while installing i18n (0.9.3), and Bundler cannot continue.
```

These tests are rock solid in the AWS env and in various runs against the PR all of them have succeeded at times, so I don't consider the tests fundamentally broken or flaky.

I have tuned my parallelism down to "10" for my job which seems to have possibly helped with some, but not all, of these issues.

**Comment by smarterclayton** [comment]
This is https://bugzilla.redhat.com/show_bug.cgi?id=1624961

**Comment by bparees** [comment]
@smarterclayton you think 

```error: fatal: unable to access 'https://gitserver-e2e-test-build-sti-private-repo-qhc9h.apps.ci-op-8trqf3lp-454ab.origin-ci-int-gce.dev.rhcloud.com/ruby-hello-world/': Failed connect to gitserver-e2e-test-build-sti-private-repo-qhc9h.apps.ci-op-8trqf3lp-454ab.origin-ci-int-gce.dev.rhcloud.com:443; Connection refused
```
 is the same root cause as 

```
Post https://internal-api.ci-op-ts6fl7dc-454ab.origin-ci-int-gce.dev.rhcloud.com:8443/apis/template.openshift.io/v1/namespaces/e2e-test-jenkins-pipeline-gbb4l/processedtemplates: dial tcp 35.185.116.42:8443: connect: no route to host",

```

I would have thought they were different since one is explicitly the router and the other is the SDN(?).

**Comment by smarterclayton** [comment]
I'll reopen for the router one (I think it's actually the same cause, but router runs on worker nodes so possible it's not)

**Comment by smarterclayton** [comment]
I bumped the CPU for masters in https://github.com/openshift/release/pull/2024
