### ISSUE TITLE
Runlevels not respected in operator manifests

### ISSUE THREAD

**Issue by ecordell** [openshift/release#1770]
/kind bug

## What did you expect to happen?
OLM [manifests](https://github.com/operator-framework/operator-lifecycle-manager/tree/master/manifests) have this this input format (prefix 30):
```
30_00-namespace.yaml
```

We expected to have these manifests in the `origin-release` image as well.

## What happened?

The output in `origin-release` is:
```
99_olm_30_00-namespace.yaml
```
And they are duplicated three times (for each of our output images)

## How can the error be reproduced?
Build openshift-release artifact with the current ci-operator and olm config. 

## Is there anything else we need to know?

I suspect this has to do with our ci-operator config: https://github.com/openshift/release/blob/master/ci-operator/config/operator-framework/operator-lifecycle-manager/master.yaml using the `images` to output three images, but it’s not obvious to me what the best way to fix it is.

**Comment by smarterclayton** [comment]
Duplication is because you have /manifests dir and label in all three images.  You need to have a single docker file for your image that sets those labels.

Prefix is `0000_RUNLEVEL_*` for run levels.

**Comment by stevekuznetsov** [comment]
@smarterclayton where is the doc for this workflow?

**Comment by smarterclayton** [comment]
Same place as all update payloads https://docs.google.com/a/redhat.com/document/d/1CGZVEyuloZ9oD4NUArW6dnEpi0WFc6BP2tqPSwFZTCY/mobilebasic#heading=h.1zgrwxmpgxbr

**Comment by ecordell** [comment]
Closing since I know the proper format now.
