### ISSUE TITLE
Non-4.0 Template Tests Cannot Provide RELEASE_IMAGE_LATEST

### ISSUE THREAD

**Issue by dmage** [openshift/release#1812]
/kind bug

The `e2e` tests fail for the branch [release-3.10 of openshift/image-registry](https://github.com/openshift/image-registry/tree/release-3.10) with the error

> cannot resolve parameter RELEASE_IMAGE_LATEST into template e2e-gcp: could not lazily evaluate deferred parameter: could not retrieve output imagestream: imagestreams.image.openshift.io "release" not found

List of failed executions:

https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/pull/openshift_image-registry/127/pull-ci-image-registry-e2e-3.10/

**Comment by smarterclayton** [comment]
Fixed with #1816
