### ISSUE TITLE
Azure origin conformance tests failure

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/release#1825]
/kind question

Our Azure origin conformance tests suddenly fails with the error that TEST_COMMAND is undefined
```
2018/10/05 12:49:12 All images ready
2018/10/05 12:49:12 No release image necessary, stable image stream does not include a cluster-version-operator image
2018/10/05 12:49:13 Ran for 6m23s
error: could not run steps: template cluster-launch-e2e-azure-conformance has required parameter TEST_COMMAND which is not defined
```
Is there something which changed recently in prow configuration such that we need to re-align our ci-operator configs?

@bbguimaraes

**Comment by mjudeikis** [comment]
@openshift/sig-azure

**Comment by mjudeikis** [comment]
This is "us not quite using same config as everybody else" so we need to align.

**Comment by bbguimaraes** [comment]
@charlesakalugwu: can you add a link to that specific job failure?

**Comment by charlesakalugwu** [comment]
@bbguimaraes I ran `ci-operator` locally using the `cakalugwu-osa-origin-conformance` namespace of the CI cluster. I guess all logs should be there. 

```
export CI_OPERATOR_NAMESPACE=cakalugwu-osa-origin-conformance

ci-operator \
    --config ci-operator/config/openshift/openshift-azure/openshift-openshift-azure-master.yaml \
    --git-ref=openshift/openshift-azure@master \
    --namespace=${CI_OPERATOR_NAMESPACE} \
    --template ci-operator/templates/openshift/openshift-azure/cluster-launch-e2e-azure-conformance.yaml \
    --secret-dir $(pwd)/cluster/test-deploy/azure/
```

Local run logs: https://gist.github.com/charlesakalugwu/21bdb531c79b37aa09549201bf16a1da

**Comment by charlesakalugwu** [comment]
thanks @bbguimaraes
