### ISSUE TITLE
CI Job running wrong version of extended tests

### ISSUE THREAD

**Issue by bparees** [openshift/release#1833]
I have a CI job on openshift/builder that runs the extended tests from openshift/origin.

I recently merged changes to the extended tests:
https://github.com/openshift/origin/pull/21178

it merged at 10am.

I ran the CI job against my openshift/builder PR at 3pm:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_builder/4/pull-ci-openshift-builder-master-extended-builds/62

The test job failed, reporting a failure in the test that was disabled in origin:
```
/tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/gitauth.go:92
Expected
    <bool>: false
to be true
/tmp/openshift/build-rpms/rpm/BUILD/origin-4.0.0/_output/local/go/src/github.com/openshift/origin/test/extended/builds/gitauth.go:88
```

https://github.com/bparees/origin/blob/91aee8f86b7172ce7e6c676434302033ab6c8ad7/test/extended/builds/gitauth.go#L94

So it seems like the CI job is using an old version of the origin extended tests when it runs.

**Comment by stevekuznetsov** [comment]
Do you have always pull policy on your pods?

**Comment by bparees** [comment]
@stevekuznetsov what do you mean by "my" pods?  The issue here isn't related to pods the tests themselves are launching, it's w/ the CI job building/running the wrong extended.test binary.

The job definition is here:
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml#L124-L184

and its pull policy appears to be always:
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/builder/openshift-builder-master-presubmits.yaml#L160

**Comment by smarterclayton** [comment]
Interesting.  Another option is that the tests image didn't get updated for some reason.

https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/branch-ci-openshift-origin-master-images/53/

failed - was that when you merged?  The next merge was at 5pm, so that would explain this.

**Comment by bparees** [comment]
> failed - was that when you merged? The next merge was at 5pm, so that would explain this.

probably, my merge happened at 9:57am and that job ran at 9:58am.

Seems like we need that job to rerun on failure?

**Comment by stevekuznetsov** [comment]
We need a better job type in Prow that isn't just "run something after a merge" but "enforce some useful items for a job that's meant to publish something"...

**Comment by stevekuznetsov** [comment]
@smarterclayton was this one of the api.ci outages?

**Comment by smarterclayton** [comment]
Possible or another undiagnosed network flake
