### ISSUE TITLE
how to get 3.11 and newer rpms for openshift

### ISSUE THREAD

**Issue by charlesakalugwu** [openshift/release#1858]
It looks like rpm artifacts for the newer versions are no longer published in the CI buckets https://console.cloud.google.com/storage/browser/origin-ci-test/releases/openshift/origin?project=openshift-gce-devel

This is a problem for us on the azure team as we require that those artifacts be available outside the CI cluster (e.g. azure) in order for our vms to bootstrap themselves prior to image creation. 

Do you have suggestions how we can solve this issue? In the worst case, we might need to resort to running our own rpm mirror...

/kind question

**Comment by kargakis** [comment]
@smarterclayton @stevekuznetsov
