### ISSUE TITLE
Problem building jenkins image when adding container.yml

### ISSUE THREAD

**Issue by gabemontero** [openshift/release#1860]
/kind bug

When ci-operator is building the jenkins test image, we continually get

```
2018/10/04 06:27:07 Build jenkins-e2e-tests failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-drj4hw4k/pipeline@sha256:541003e446505e868000fc9cb89a58f40b9ea72b66c0680bf3daf7b1ea447915" ...
error: error copying source path /go/src/github.com/openshift/jenkins/test-e2e/. to .: API error (404): {"message":"lstat /var/lib/docker/overlay2/f5779d4e78738830ff229f7a6c9e4989f03a3a393f7d13b38775d1e0eebc06ad/merged/go/src/github.com/openshift/jenkins/test-e2e/.: no such file or directory"}
```

See PR https://github.com/openshift/jenkins/pull/712

/area test-execution

## What did you expect to happen?

For the test image to be properly built and the openshift/jenkins e2e test launched

## What happened?

The ci-operator run fails trying to build our test image

## How can the error be reproduced?

retest the PR I noted above

## Is there anything else we need to know?

The container.yml added in the PR is the power pc  guys are part trying to get things going for their stuff

**Comment by stevekuznetsov** [comment]
Can you link the failed build logs, job configuration in ci-op and prow, etc

**Comment by gabemontero** [comment]
ci-op config: https://github.com/openshift/release/blob/master/ci-operator/config/openshift/jenkins/openshift-jenkins-master.yaml

presubmit:  https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml

failed build log:  https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_jenkins/712/pull-ci-openshift-jenkins-openshift-3.10-e2e-gcp/4/build-log.txt

**Comment by stevekuznetsov** [comment]
There's no `test-e2e` directory in the `openshift-3.10` branch, so the copy isn't working

**Comment by gabemontero** [comment]
DAAAAAAHHHHHH .... somehow did not pick up on the 3.10 aspect

thanks @stevekuznetsov  :-$ .... (emoticon per https://pc.net/emoticons/smiley/embarrassed )
