### ISSUE TITLE
Need a gating PR job for service-serving-cert-signer repo

### ISSUE THREAD

**Issue by mrogers950** [openshift/release#1862]
@smarterclayton We're not yet using images from openshift/service-ca-operator, so for the time being we could use one for openshift/service-serving-cert-signer

**Comment by stevekuznetsov** [comment]
What is being asked for here, and from who is it being asked from?

**Comment by mrogers950** [comment]
@stevekuznetsov Ignore, I should have checked with Clayton on this one first.
