### ISSUE TITLE
generated-config validate untenable

### ISSUE THREAD

**Issue by gabemontero** [openshift/release#1903]
/kind bug

generated-config parsing of my presubmits

/area test-execution

## What did you expect to happen?

See https://github.com/openshift/release/pull/1902#issuecomment-429086212

also, before I got to this point, the diff logic complained if yaml lines were not in exactly the right order ... even at the same level of the yaml docs hierarchy ... 

## How can the error be reproduced?

re-run generated-config in my https://github.com/openshift/release/pull

**Comment by bbguimaraes** [comment]
@gabemontero: we enforce alphabetical ordering in the job definitions to make the migration to auto-generated jobs practical. The generator outputs jobs in the correct format, but that has to be taken into account when adding jobs manually.

As for the generation itself, each test type in the ci-operator configuration file corresponds to a test workflow (i.e. one of the templates in `ci-operator/templates`). Support for the common test types and cluster profiles (described [here](https://github.com/openshift/ci-operator/blob/master/CONFIGURATION.md#tests)) has already been added.

New types and profiles need to be added to the generator if automatic generation of jobs is desired — adding jobs manually is still an option. The openshift-ansible team is working on adding two of their templates, their [PR](https://github.com/openshift/ci-operator/pull/176) can be used as a guide to add support for the `cluster-launch-e2e-openshift-jenkins` template.

**Comment by stevekuznetsov** [comment]
Note -- it's worth it for you to follow the generator approach IFF you expect others to use your template. You can just use a template without changing your CI-Operator configuration and handle the ProwJob configuration yourself if you want this to be a one-off.

**Comment by petr-muller** [comment]
One thing that we could make easier is a pre-push sanitization to save people from having this PR-oh-f**k-alphabet cycle. There are scripts in `hack` that do this but we would need to improve them,

**Comment by stevekuznetsov** [comment]
I would assume people are running their tests locally, too ...

**Comment by petr-muller** [comment]
I meant for `openshift/release`. I wonder if people just trying to setup / change CI things even know about what `hack/` scripts run in openshift/release presubmits.

**Comment by gabemontero** [comment]
ok thanks for the background and pointers @bbguimaraes ... going through them this morning

@stevekuznetsov - on the set up on your own piece, the creation of the config map in the ci namespace on api.ci is certainly manageable for non-DPTP/Clayton folks ... I did that already, but the notion of updating the prowjob config came up when we first introduced this jenkins e2e earlier this summer, and between permissions, cert setup, etc. it was untenable for that to be done by just anyone (among other things, that was why we went down that "-canary" path in the job name, etc. etc.)

Has something changed where it is viable for me to run `mkpj` and what not update the prow config?

And yeah, I only expect the jenkins e2e to use my  template ... of course, I have a separate template cause Clayton did not want the extra env vars/ params the jenkins e2e needs in the core template.

I'll start in the interim with making the ci-operator changes a la the ansible team so I can get accepted by the generator approach, but can certainly pivot to doing mkpj manually based on any responses you all have there.

**Comment by bbguimaraes** [comment]
@gabemontero: automatic generation of jobs is only useful for templates that are used in multiple jobs. If your template is specific to one or a few jobs, it would be counter-productive to add support for it in the generator, specially since you have already added the jobs manually.

Automatic generation is completely optional — the generator will keep jobs that are already present in the Prow configuration even if they are not in the ci-operator configuration file.

**Comment by gabemontero** [comment]
OK, @bbguimaraes  - can you confirm for me the instructions for me doing int manually?

I found:
a) https://github.com/openshift/test-infra/blob/master/prow/getting_started.md
b) https://github.com/openshift/test-infra/tree/master/prow

Are there any other recipes I need to reference?

**Comment by stevekuznetsov** [comment]
The manual workflow is literally what you had before -- write a template, use the ProwJob config to use it. The suggestion is simply to not make any changes to the ci-operator configuration -- your other PR was not necessary

**Comment by gabemontero** [comment]
If by my other PR you mean https://github.com/openshift/release/pull/1902 the only reason I submitted that is because @smarterclayton told me in  https://github.com/openshift/release/pull/1176#discussion_r224233278  to override `TEST_PARALLELISM` there vs. changing the default in the template.

The "make copying easier" as he noted in the commit I presume was to make easy for folks who update cluster-launch-e2e.yaml to copy those updates to the delta templates.

I am perfectly happy to set `TEST_PARALLELISM` in the template if that is preferred.  Presumably then, I would need to watch for updates to cluster-launch-e2e.yaml and copy changes as needed of updates to cluster-launch-e2e.yaml would not be reproduced in the other delta templates in the future.

Or if it is none of that, let's bluejeans when you all are available and get on the same page.

thanks

**Comment by gabemontero** [comment]
ahhhhh ... thanks for putting it in terms that resonate @bbguimaraes .... my previous forays here were pre-auto gen, and I just did not pick up on that distinction.

I'll update https://github.com/openshift/release/pull/1176 momentarily.

Should I remove the files in question from `ci-operator/config` then?  We can sort out in the PR or here, wherever you prefer.

**Comment by gabemontero** [comment]
@bbguimaraes  though I'm a bit confused as I started to update the PR .... if you look at https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/1902/pull-ci-openshift-release-master-generated-config/557

It is doing a diff of the presubmits under `ci-operator/jobs` and complaining
```
diff -Naupr hack/../ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml /tmp/tmp.qA8DO6Ne1L/ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml
--- hack/../ci-operator/jobs/openshift/jenkins/openshift-jenkins-master-presubmits.yaml	2018-10-11 19:17:50.803271497 +0000
```

It seems as if it is complaining about the `ci-operator/jobs` content ... not the `ci-operator` content.

I'll ping on slack ...

**Comment by gabemontero** [comment]
reader's digest of slack chat with everyone ... remove ci-operator/config changes, leave ci-operator/job ... removing config changes will bypass validation

**Comment by gabemontero** [comment]
PR merged ... closing ... thanks everyone
