### ISSUE TITLE
Jobs failed to push image: unauthorized: unable to validate token

### ISSUE THREAD

**Issue by legionus** [openshift/release#1925]
```
could not wait for build: the build src failed with reason PushImageToRegistryFailed: Failed to push the image to the registry.

Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: unauthorized: unable to validate token
```

https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/36/pull-ci-openshift-cluster-image-registry-operator-master-unit/56

This blocks the cluster-image-registry-operator repository.

/kind bug
/area test-execution

**Comment by stevekuznetsov** [comment]
Taking this offline with @legionus

**Comment by legionus** [comment]
OK. I see a problem. The builder is trying to talk with registry without token. It happened when you switched to cri-o. It happend 2018-10-15T14:43:11.118679033Z or so.

/cc @bparees

**Comment by bparees** [comment]
/cc @smarterclayton 

the builder doesn't use crio to push images (it still depends on docker), so this is something else pushing images....  unless api.ci has somehow picked up 4.0 already.

**Comment by bparees** [comment]
Seems to be fixed?

**Comment by legionus** [comment]
Looks like fixed.

**Comment by stevekuznetsov** [comment]
@smarterclayton can you detail what happened here?

**Comment by smarterclayton** [comment]
No idea.  It's possible that the cluster was bogged down and a pull secret didn't get created and pushed to the build pod, but I find that unlikely.
