### ISSUE TITLE
Jenkins proxy dies when kicking off a new job

### ISSUE THREAD

**Issue by csrwng** [openshift/release#193]
Starting a new job on the jenkins proxy caused it to crash. (/test verify-origin). It was crashing previously when invoking a different test (/test ut-origin).  I stopped retrying the build and eventually after a while it stopped crashing on *that* test.

There's no stack dump in the log when this happens:
```
2017/09/28 19:48:16 Reading config from /etc/jenkins-proxy/config
2017/09/28 19:48:16 Listing jobs from https://ci.openshift.redhat.com/jenkins
2017/09/28 19:48:16 Listing jobs from https://jenkins-origin-ci.svc.ci.openshift.org
2017/09/28 19:48:16 Serving on :8080
2017/09/28 19:49:16 Reading config from /etc/jenkins-proxy/config
2017/09/28 19:49:16 Jenkins proxy config reloaded.
2017/09/28 19:49:30 http: read on closed response body
```

**Comment by csrwng** [comment]
@kargakis

**Comment by stevekuznetsov** [comment]
@kargakis this is what killed us in the past I am sure

**Comment by stevekuznetsov** [comment]
Looks like a job with no builds is no bueno for the proxy

**Comment by kargakis** [comment]
The proxy crash is fixed in https://github.com/openshift/release/pull/196.
