### ISSUE TITLE
e2e-aws fails with object is being deleted: pods "e2e-aws" already exists

### ISSUE THREAD

**Issue by mfojtik** [openshift/release#1955]
e2e-aws test fails with:

```
2018/10/17 20:22:19 Creating or restarting template instance
2018/10/17 20:22:19 Waiting for template instance to be ready
2018/10/17 20:22:25 Ran for 48s
error: could not run steps: could not wait for template instance to be ready: could not determine if template instance was ready: failed to create objects: object is being deleted: pods "e2e-aws" already exists
```
Sample: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_installer/420/pull-ci-openshift-installer-master-e2e-aws/774

/area test-execution
/kind bug

**Comment by smarterclayton** [comment]
`object is being deleted: pods already exists` is the weirdness

**Comment by petr-muller** [comment]
This is probably #1335 which I though I have fixed in https://github.com/openshift/ci-operator/pull/179 :(
