### ISSUE TITLE
e2e-aws failed: Another process exited

### ISSUE THREAD

**Issue by dmage** [openshift/release#1968]
```
2018/10/18 14:19:45 Running pod e2e-aws
2018/10/18 14:21:08 Container setup in pod e2e-aws completed successfully
2018/10/18 16:20:02 Container teardown in pod e2e-aws completed successfully
2018/10/18 16:20:11 Copying artifacts from e2e-aws into /logs/artifacts/e2e-aws
Another process exited
2018/10/18 16:20:11 Container test in pod e2e-aws failed, exit code 1, reason Error
2018/10/18 16:20:11 Copied 0.00Mi of artifacts from e2e-aws to /logs/artifacts/e2e-aws
2018/10/18 16:20:17 Ran for 2h4m13s
error: could not run steps: could not wait for pod to complete: could not wait for pod completion: the pod ci-op-kbml1crm/e2e-aws failed after 2h0m27s (failed containers: test):  unknown

Container test exited with code 1, reason Error
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/33/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws/20

**Comment by bbguimaraes** [comment]
That's from the script that executes the test after the cluster is provisioned:

https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L108

@wking

**Comment by wking** [comment]
>      2018/10/18 16:20:17 Ran for 2h4m13s

Sounds like your cluster never brought up [a recognized router][1] and you fell out the bottom of [the teardown timeout][2].

[1]: https://github.com/openshift/release/blob/17d2b89150c939f07742d20bf70e5bd7439060bc/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L130
[2]: https://github.com/openshift/release/blob/17d2b89150c939f07742d20bf70e5bd7439060bc/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L346

**Comment by stevekuznetsov** [comment]
Looks like there are no actionable fixes here

/close
