### ISSUE TITLE
CI cluster git-clone uses chmod as non-priv user

### ISSUE THREAD

**Issue by mjudeikis** [openshift/release#1975]
in our CI jobs we started seeing git-clone failures inside our custom image:
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_openshift-azure/628/pull-ci-openshift-openshift-azure-master-verify/319 

```
{"command":"git merge 81e29c16d4e81ea3a2c4751eb24defcdb7280282","component":"clonerefs","error":null,"level":"info","msg":"Ran command","output":"Merge made by the 'recursive' strategy.\n README.md | 1 +\n 1 file changed, 1 insertion(+)\n","time":"2018-10-19T10:20:27Z"}
{"component":"clonerefs","level":"info","msg":"Finished cloning refs","time":"2018-10-19T10:20:27Z"}
chmod: changing permissions of '/go/src': Operation not permitted
chmod: changing permissions of '/go/src/github.com': Operation not permitted
```

Idea is that folder is owned by root but with open permissions:
```
→ docker run --privileged -it -u 2147483647 test bash 
bash-4.2$ ls -la /go
total 36
drwxrwxrwx. 1 root root 4096 Oct 19 11:30 .
drwxr-xr-x. 1 root root 4096 Oct 19 12:24 ..
drwxrwxrwx. 2 root root 4096 Oct 19 11:30 bin
drwxrwxrwx. 3 root root 4096 Oct 19 11:30 pkg
drwxrwxrwx. 4 root root 4096 Oct 19 11:30 src
```

so create/delete files should work just fine in the folders. But for `chmod/chown` does not work as container runs as random UID and files are not owned but it. 

We use minimal entrypoint (similar to ansible image)
https://github.com/openshift/release/blob/master/projects/azure/base-images/test-base/root/usr/local/bin/entrypoint

Is this a case what we need to change something in our base image or underlaying bug in code clone process?

cc: @stevekuznetsov @smarterclayton @kargakis @bbguimaraes

**Comment by smarterclayton** [comment]
We make the directories group writable and owned by the root group and ensure they have the sticky bit for inheritance
