### ISSUE TITLE
Cannot pull pipeline imagestream

### ISSUE THREAD

**Issue by kargakis** [openshift/release#1976]
I would love to be able to pull tags from the pipeline imagestream so then I can verify individual ci-operator steps locally.

**Comment by bbguimaraes** [comment]
PR authors have admin access to the ci-operator namespace, so it is already possible to start pods or add something similar to [what's done in e2e tests](https://github.com/openshift/release/blob/master/ci-operator/templates/cluster-launch-e2e.yaml#L26-L36).

The only thing to keep in mind is the [TTL controller](https://github.com/openshift/ci-ns-ttl-controller) will eventually delete the namespace (we use the [default values](https://github.com/openshift/release/blob/master/ci-operator/templates/cluster-launch-e2e.yaml#L26-L36) for the TTLs in CI jobs).

**Comment by stevekuznetsov** [comment]
As noted by Bruno, there is a simple way to do this already.

/close
