### ISSUE TITLE
 ci/prow/e2e-conformance-k8s will not pass

### ISSUE THREAD

**Issue by coreydaley** [openshift/release#1996]
/kind bug
/area test-execution

The ci/prow/e2e-conformance-k8s  test will not pass, you can see at this link (https://openshift-gce-devel.appspot.com/builds/origin-ci-test/pr-logs/directory/pull-ci-openshift-origin-master-e2e-conformance-k8s) the logs of all of the failures.  It is holding up (at least my) pull requests but I would assume there are others also.

https://github.com/openshift/origin/pull/21331

**Comment by stevekuznetsov** [comment]
The test runs fine here, but the cluster looks degraded. I'd suggest contacting the test authors to determine what the issue is.

/close

**Comment by bparees** [comment]
> The test runs fine here

Where is "here"

> but the cluster looks degraded.

What cluster looks degraded?

**Comment by coreydaley** [comment]
@stevekuznetsov That seems backwards to me?
If it runs fine "there" then it's not a test issue, if the cluster is degraded, isn't that your department?

**Comment by bparees** [comment]
This cannot be closed until this job is passing and we can merge code again.  If that means disabling the job or hunting down the test owners, so be it, but this is a blocker for our team to make progress for 4.0.

**Comment by stevekuznetsov** [comment]
As in, the test infrastructure runs and the cluster is up, end-to-end tests are executed .... there is no actionable issue for DPTP here. If you'd like to keep this open while you track down owners. that is fine

**Comment by bparees** [comment]
@coreydaley please open a high severity BZ against the master team and link it here.

**Comment by coreydaley** [comment]
Opened https://bugzilla.redhat.com/show_bug.cgi?id=1642132

**Comment by bparees** [comment]
Per my comments in the BZ, I don't think this test should have even been triggered against the PR in question.  When I cherry-picked the commit to a new PR, the test was not run against the new PR.  

That's sufficient for us to move on, but if we continue to see behavior in which optional tests are triggered against PRs for no apparent reason, we'll reopen this as a prow issue.
