### ISSUE TITLE
Google Cloud Service Account for Registry Doesn't Have Privileges to Registry GCS Bucket

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#2]
I added the privileges to it manually in the console, but if the service account and/or registry bucket in GCS are created on startup this privilege needs to be created as well.

@smarterclayton

**Comment by stevekuznetsov** [comment]
@smarterclayton something about your setup still fails this

**Comment by kargakis** [comment]
/assign smarterclayton 

Is this a problem now?
