### ISSUE TITLE
HOME is set to wrong and unwritable dir ci-operator tests

### ISSUE THREAD

**Issue by tnozicka** [openshift/release#2057]
/kind bug

## What did you expect to happen?
Be able to write to $HOME in ci-operator test.

## What happened?
User couldn't write to $HOME

($HOME was pointing to `/` I think.)

## How can the error be reproduced?
By removing this line:
https://github.com/openshift/release/pull/2051/files#diff-111afe11cb1461f9175deea657ae5b11R46

**Comment by stevekuznetsov** [comment]
Home is not set to anything by our systems. Why do you need it? If you need it, set it.

**Comment by stevekuznetsov** [comment]
Generally tests that are messing with the container filesystem outside of the working directory are very smelly. I would like to understand the use-case here better.
