### ISSUE TITLE
Branch names are interpreted as regular expressions by prow

### ISSUE THREAD

**Issue by akrejcir** [openshift/release#20684]
/kind bug
/area test-execution

## What did you expect to happen?
In our project `kubevirt/ssp-operator`, there are 3 branches that we want to execute tests for.
The branch names in the prow jobs are generated from the filenames in the `ci-operator/config` directory:
- `kubevirt-ssp-operator-master.yaml`
- `kubevirt-ssp-operator-release-v0.1.yaml` 
- `kubevirt-ssp-operator-release-v0.11.yaml`

I expected the jobs to run for these branches.

## What happened?
In the generated prow job, the branch name is specified in the `branches` list. But prow interprets this list as a list of regular expressions. It matches the expressions to the branch name to check if a job should run.

In our case any PR for branch `release-v0.11` matches regular expressions for 2 prow jobs: `release-v0.1` and `release-v0.11`, and it fails with this error:
```
failed to load configuration: got unexpected http 404 status code from configresolver: failed to get config: found more than one matching config for branch release-v0.11 on repo kubevirt/ssp-operator
```

I have tried renaming the config file to `kubevirt-ssp-operator-^release-v0.11$.yaml` to set the branch regex to `^release-v0.11$`, but `make update` fails with error:
```
time="2021-07-29T12:41:27Z" level=fatal msg="failed to load Prow configuration" error="[invalid presubmit job pull-ci-kubevirt-ssp-operator-^release-v0.11$-e2e-functests: name: must match regex \"^[A-Za-z0-9-._]+$\", invalid presubmit job pull-ci-kubevirt-ssp-operator-^release-v0.11$-e2e-upgrade-from-old-operator-functests: name: must match regex \"^[A-Za-z0-9-._]+$\", invalid presubmit job pull-ci-kubevirt-ssp-operator-^release-v0.11$-images: name: must match regex \"^[A-Za-z0-9-._]+$\", invalid presubmit job pull-ci-kubevirt-ssp-operator-^release-v0.11$-unittests: name: must match regex \"^[A-Za-z0-9-._]+$\"]"
```

**Comment by petr-muller** [comment]
Not a bug, that's intentional and documented behavior, see https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#feature-branches

**Comment by petr-muller** [comment]
That said, we want to change this behavior to be slightly more strict and require feature branches to match `$base-$suffix` pattern, whcih should resolve the undesired treatment of `release-v0.11` as a feature branch of `release-v0.1`.

**Comment by akrejcir** [comment]
Ok, thanks for the information. Then I will need to think of some workaround.
