### ISSUE TITLE
Registry "unable to check your credentials:... net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by wking** [openshift/release#2070]
/kind bug
/area test-execution

## What did you expect to happen?

Successful registry access.

## What happened?

In [the `images` job][1]:

```
2018/11/05 19:45:16 Copying artifacts from release-latest into /logs/artifacts/release-latest
info: Using registry public hostname registry.svc.ci.openshift.org
error: unable to check your credentials - pass --skip-check to bypass this error: Get https://registry.svc.ci.openshift.org/v2/: net/http: TLS handshake timeout
2018/11/05 19:45:16 Container release in pod release-latest failed, exit code 1, reason Error
```

## How can the error be reproduced?

I'm not sure, shortly before the above error, [a separate run][2] had:

```
2018/11/05 19:41:04 Copying artifacts from release-latest into /logs/artifacts/release-latest
info: Using registry public hostname registry.svc.ci.openshift.org
info: Found 81 images in image stream
info: Manifests will be extracted to /tmp/release-image-0.0.1-2018-11-05T194045Z990286717
warning: Could not load current user information: user: unknown userid 1114450000
Unable to connect to the server: net/http: TLS handshake timeout
2018/11/05 19:41:05 Container release in pod release-latest failed, exit code 1, reason Error
```

That looks like another code path hitting the same underlying issue (that time with a logged warning, but still a non-zero exit code).  Outside of those two failures, the same `images` job has been working fine.

[1]: https://github.com/openshift/installer/pull/606#issuecomment-436010843
[2]: https://github.com/openshift/installer/pull/606#issuecomment-436009132

**Comment by stevekuznetsov** [comment]
@smarterclayton can you triage

**Comment by wking** [comment]
Got this again [just now][1].

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/625/pull-ci-openshift-installer-master-images/1084/build-log.txt

**Comment by bparees** [comment]
On pto, can't look right now, maybe @legionus or @dmage can.

**Comment by dmage** [comment]
Ehm, where can I get the logs?

**Comment by wking** [comment]
Saw this again today over [here][1].  @smarterclayton, do you know where @dmage can get the logs?

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/778/pull-ci-openshift-installer-master-images/1448/build-log.txt

**Comment by wking** [comment]
Saw this again today over [here][1].

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/batch/pull-ci-openshift-installer-master-e2e-aws/2133/build-log.txt

**Comment by wking** [comment]
Saw this again today over [here][1], although this time the message was:

```
error: unable to connect to image repository registry.svc.ci.openshift.org/ci-op-f54sng97/stable@sha256:58b79dec7b54b6ade89615e2afc9cfdefb2f03bd612f6f27a4eff2763a342443: Get https://registry.svc.ci.openshift.org/v2/: net/http: TLS handshake timeout
```

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/882/pull-ci-openshift-installer-master-images/1658/build-log.txt

**Comment by wking** [comment]
Got [another][1]:

```
error: unable to connect to image repository registry.svc.ci.openshift.org/ci-op-7x26ipsi/stable@sha256:04b6a2c614fb3840782db830c5739ff00b74ba596c768b0c4de457b5584bdecd: Get https://registry.svc.ci.openshift.org/v2/: net/http: TLS handshake timeout
```

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/911/pull-ci-openshift-installer-master-e2e-aws/2313/build-log.txt

**Comment by bparees** [comment]
timestamp: 2018/12/14 19:29:44

**Comment by bparees** [comment]
Nothing in the registry logs related to that request, I don't think it got there.  I'm increasingly suspicious these errors have the same networking flake root cause as the no route to host errors that are being seen in the GCP runs.  We have also seen tls handshake timeouts there(talking to things other than the registry).

**Comment by bparees** [comment]
my only other suggestion would be to add another registry instance in api.ci since there are only 3 currently and if it's cpu-bound, perhaps that could cause this.

**Comment by bparees** [comment]
@smarterclayton @stevekuznetsov opinions on adding another regsitry replica instance to api.ci?

**Comment by bparees** [comment]
I do see some gaps from 19:29:09->19:34:31 between requests for an image from "i-op-7x26ipsi" 

However during that time the registry processes lots of requests for images from other namespaces.  So again, nothing seems unhealthy on the registry side.

**Comment by bparees** [comment]
> Do it. Do two more.

@smarterclayton @stevekuznetsov I don't have edit permission to change the replica count

**Comment by smarterclayton** [comment]
Updated

On Dec 14, 2018, at 12:34 PM, Ben Parees <notifications@github.com> wrote:

Do it. Do two more.

@smarterclayton <https://github.com/smarterclayton> @stevekuznetsov
<https://github.com/stevekuznetsov> I don't have edit permission to change
the replica count

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/release/issues/2070#issuecomment-447472035>,
or mute the thread

**Comment by wking** [comment]
Got another one of these [here][1], so I guess it wasn't a CPU-bound issue?

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/240/pull-ci-openshift-machine-config-operator-master-images/444/build-log.txt

**Comment by bparees** [comment]
I am officially ignoring this issue until the generalized network problems are resolved and we still see this happening.

**Comment by kikisdeliveryservice** [comment]
I just saw this today [here](https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/164/pull-ci-openshift-machine-config-operator-master-e2e-aws/823/build-log.txt)

**Comment by bparees** [comment]
@openshift/sig-network-edge a question on this error:

```
error: unable to connect to image repository registry.svc.ci.openshift.org/ci-op-7x26ipsi/stable@sha256:04b6a2c614fb3840782db830c5739ff00b74ba596c768b0c4de457b5584bdecd: Get https://registry.svc.ci.openshift.org/v2/: net/http: TLS handshake timeout
```

registry.svc.ci.openshift.org is a re-encrypt route.  If the TLS handshake failure is happening between the router and the backend pod (ie during the re-encrypt phase), is this the error the docker client would see?

I might have expected to only see this error for a handshake failure to the router(ie between the client+router), whereas a failure between the router and the backend pod would be returned to the client as a 504 or some other failure that indicates backend unavailability?

**Comment by bparees** [comment]
@ironcladlou bump ^^

**Comment by ramr** [comment]
@bparees  yes, so if the router is up and servicing requests and is unable to get to the registry - pod doesn't exist/service doesn't exist etc, it would return a 503. Same's true if say the destination CA cert doesn't match for a re-encrypt route (aka it can't send a request to the-pod-backing-the-service).  
In general, any errors the router talking to the service [pods] for the route, would manifest as http errors back to the client.

In this case, it looks like it is the connection between the client and the router that's failing.
In the past, we have seen issues like this when the mtu doesn't match: 
ref: https://docs.openshift.com/container-platform/3.11/admin_guide/sdn_troubleshooting.html#tls-handshake-timeout

Tagging @danwinship  as well in case he has something to add.

**Comment by danwinship** [comment]
>  In the past, we have seen issues like this when the mtu doesn't match:

Right, because if the network was totally broken you'd get "can't connect" or "no route to host", but with a misconfigured MTU, you can successfully connect but then run into problems when the server tries to send a response containing a TLS certificate that's larger than 1500 bytes.

As long as all of the hosts in the cluster have the same MTU, we should be autodetecting it correctly; you can find the detected MTU in the pod logs of the cluster-network-operator in the test artifacts. eg:

    2019/01/29 10:19:59 Reconciling NetworkConfig.networkoperator.openshift.io default
    2019/01/29 10:19:59 Detected uplink MTU 9001

If the hosts don't all have the same MTU, then you would need to configure it explicitly at install time, but I'm assuming that's not the problem here.
