### ISSUE TITLE
False positive router availability checks possible in e2e launch template

### ISSUE THREAD

**Issue by ironcladlou** [openshift/release#2089]
/kind bug

/area test-execution

## What did you expect to happen?

The e2e-aws tests should not proceed until the router is available. 

## What happened?

In some cases tests proceed even when the router isn't actually available.

## How can the error be reproduced?

The problem is a gap in [the router gating logic](https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/installer/cluster-launch-installer-e2e.yaml#L157): when the worker node count is zero, `oc rollout status` will return success for the router daemonset. If no workers nodes exist, the router daemonset "desired" is zero, and since desired (0) equals available (0), the daemonset is considered rolled out.

## Is there anything else we need to know?

This gap allowed at least one [major installer regression](https://github.com/openshift/installer/issues/622) to slip through CI.

**Comment by smarterclayton** [comment]
This is a kube bug.  A 0 damensot is not available.

**Comment by ironcladlou** [comment]
Daemonsets have no conditions published on status, so I don't see any state discrepancies here at the moment; it seems we're beholden to the actual semantics of `rollout status`...

**Comment by smarterclayton** [comment]
that's a bug in daemonsets too

**Comment by ironcladlou** [comment]
This actually prompted us to reassess our decision to use DaemonSet for routers. We decided that Deployment is actually more useful, and so [we're going to switch](https://jira.coreos.com/browse/NE-104).

That will also allow us to side-step the DaemonSet conditions issue in this case.

**Comment by smarterclayton** [comment]
let's fix rollout status now

**Comment by smarterclayton** [comment]
I plan on replacing this very shortly with the new openshift test binary which will be able to tolerate / handle this correctly by waiting for cluster stabilization before continuing.  We'll also remove the router wait loop in favor of `oc wait` against the cluster version payload application.
