### ISSUE TITLE
test failures in jenkins logging CI jobs for release-3.11

### ISSUE THREAD

**Issue by richm** [openshift/release#2106]
See https://github.com/openshift/origin-aggregated-logging/pull/1446
Sometimes the logging tests will pass and complete successfully - but the PR `ci/openshift-jenkins/json-file` and `ci/openshift-jenkins/logging` will report `Pending` - yes, I've waited several hours and used `/refresh` - it never reports success
Sometimes the logging tests will hit a flake and fail - but the jenkins job says `
Build Still Running!` even though the test is complete - and there are no artifacts either on the https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1446/test_pull_request_origin_aggregated_logging_journald-release-3.11/131/ link or in the jenkins job link https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_journald-release-3.11/131/

/kind bug

/area test-artifacts

/area test-results

**Comment by stevekuznetsov** [comment]
One of the jobs that failed to publish artifacts lost connection to the test machine. We should see if that's the most common source of error:

```
+ scp -F /var/lib/jenkins/jobs/test_pull_request_origin_aggregated_logging_json_file-release-3.11/workspace@2/.config/origin-ci-tool/inventory/.ssh_config /tmp/tmp.F2RQcDfH5X openshiftdevel:/tmp/tmp.F2RQcDfH5X
lost connection
++ export status=FAILURE
++ status=FAILURE
```

**Comment by stevekuznetsov** [comment]
Can you link us to a job that is hung and not reporting status?

**Comment by richm** [comment]
I don't have one yet - will just have to keep doing /retest until I can reproduce - here is another 3.11 PR which I'm using for testing - https://github.com/openshift/origin-aggregated-logging/pull/1447

**Comment by richm** [comment]
ok - at least the kibana test failures are due to https://github.com/openshift/aos-cd-jobs/pull/1526

**Comment by richm** [comment]
This test is hung: https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_aggregated_logging_json_file-release-3.11/117/console

The test failed and the logging test script has exited - not sure what jenkins is doing

**Comment by richm** [comment]
I restarted the tests - the actual logging tests will hopefully pass since I have pushed https://github.com/openshift/aos-cd-jobs/pull/1526 for now - should solve the kibana failures anyway

**Comment by richm** [comment]
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_origin-aggregated-logging/1446/test_pull_request_origin_aggregated_logging_json_file-release-3.11/117/

says `No Test Failures!` but there were definitely test failures 
There are now artifacts
