### ISSUE TITLE
[RFE] Periodic jobs access to the team

### ISSUE THREAD

**Issue by mjudeikis** [openshift/release#2113]
We run multiple periodic jobs in prow.
When jobs fail, we need a way to access them and find what broke down so we can debug locally.

It should be possible to grant access to the team/group for periodic jobs namespaces. Something like:

```
ci-operator.openshift.io/namespace-access-group: azure-team
```
where `azure-team` is our team group in CI cluster. 

@kargakis @stevekuznetsov @bbguimaraes

**Comment by stevekuznetsov** [comment]
No. Expose the artifacts you need. There is no guarantee that any job namespaces or pods are existing when you go look, as they will get GC-ed. This approach isn't tenable.

/close
