### ISSUE TITLE
set the user id for unit tests

### ISSUE THREAD

**Issue by mfojtik** [openshift/release#2181]
In 1.12.2 rebase PR there is a unit test failing from kube that require the UID <-> username mapping.
The prow container that run the unit tests use the random UUID so there is no entry for that user inside /etc/passwd.

We should probably consider using the fixed UID (1001?) for these containers to avoid such failures.

**Comment by stevekuznetsov** [comment]
That seems kind of crazy as a requirement for a unit test .... can you go into more detail?

/cc @smarterclayton

**Comment by smarterclayton** [comment]
please fix the unit test
