### ISSUE TITLE
rename all periodics files to indicate branch

### ISSUE THREAD

**Issue by jim-minter** [openshift/release#2212]
Clayton asked:

> is ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml off master or 3.11
> same question for preview-1

Then said:

> i would recommend renaming that file so that it clearly denotes which branch it is from
> to be consistent with other jobs
> if you need to add a variant at the end like preview 1 you can do _preview1.yaml
> when doing refactors in ci it’s hard if you guys have a different pattern than everything else

@kargakis please could you rename the appropriate files accordingly?

**Comment by kargakis** [comment]
@smarterclayton none of the periodics files use the branch name in their filenames. I am not sure of the mechanics to read these files anymore and I don't want to break our periodics. Also, I guess we should be renaming them all at once? An intermediate state where you have files with both formats is probably worse than consistency with the one or the other format.
```
$ find * -name *periodic* 
ci-operator/jobs/openshift/origin/openshift-origin-periodics.yaml
ci-operator/jobs/openshift/azure-misc/openshift-azure-misc-periodics.yaml
ci-operator/jobs/openshift/knative-eventing/openshift-knative-eventing-periodics.yaml
ci-operator/jobs/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-periodics.yaml
ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-periodics.yaml
ci-operator/jobs/openshift/ose/openshift-ose-periodics.yaml
ci-operator/jobs/openshift/release/openshift-release-periodics.yaml
ci-operator/jobs/openshift/knative-build/openshift-knative-build-periodics.yaml
ci-operator/jobs/openshift/knative-serving/openshift-knative-serving-periodics.yaml
ci-operator/jobs/kubernetes-sigs/cri-o/kubernetes-sigs-cri-o-periodics.yaml
ci-operator/jobs/infra-periodics.yaml
```

**Comment by kargakis** [comment]
And fwiw all openshift-azure periodics are targetting openshift-azure@master.

**Comment by stevekuznetsov** [comment]
Periodics are not inherently tied to a repo, or a ref, or anything... which is why I put them into a `_periodics` file at firat

**Comment by stevekuznetsov** [comment]
Whoa, ctrl+enter now closes the issue?
