### ISSUE TITLE
Instructions on how to update a pipeline job

### ISSUE THREAD

**Issue by kargakis** [openshift/release#222]
I am trying to update the pod template used by our unit tests in order to try out a few different approaches and I am lost as to how to proceed. This [README](https://github.com/openshift/release/blob/master/cluster/ci/origin/README.md) talks about pipeline instantiation but not about updating stuff. It would be nice to walk through an update scenario.

/assign @csrwng

**Comment by kargakis** [comment]
I guess I am asking for something similar to the upstream [getting started](https://github.com/kubernetes/test-infra/blob/master/prow/getting_started.md#add-more-jobs-by-modifying-configyaml) guide but scoped to working with our pipelines. Also, new-app is etoomuch dark magic since it mutates the generated artifacts in very subtle ways. Can we simply use `oc process`?

**Comment by csrwng** [comment]
Yup, will write a doc today. All new-app does is add an app label if none is present, but yes, we can switch to process in the instructions.

Just fyi, the pod template for unit tests is here:
https://github.com/openshift/release/blob/master/cluster/ci/origin/config/unit-tests.yaml
