### ISSUE TITLE
optional test jobs not being treated as optional

### ISSUE THREAD

**Issue by bparees** [openshift/release#2287]
I created this PR:
https://github.com/openshift/origin/pull/21574

At some point e2e-gcp-crio started getting run against it, i'm not sure why (that job is optional and my PR does not touch any paths that are listed in the run if changed:
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/origin/openshift-origin-master-presubmits.yaml#L309
)

I could not get the bot to stop enforcing that job as a required job for the PR to merge.  

Open questions are:

1) why did the bot thing that job was necessary?  It looks like maybe it got picked up when i ran "/test all", so that would answer that mystery at least.

2) even assuming the job was accidentally run once, and thus became "mandatory" for the PR, how do i make it "un-mandatory" without closing the PR?  My understanding is "/skip" i supposed to do this, but that did not appear to work.  (The status reporting was still saying e2e-gcp-crio was a mandatory job for the PR).

**Comment by stevekuznetsov** [comment]
Turns out the job is not optional

/close

**Comment by bparees** [comment]
in my defense it was also not "always_run".  i guess you'd call it "conditional" but not "optional".
