### ISSUE TITLE
optional jobs run by default on every PR 

### ISSUE THREAD

**Issue by kargakis** [openshift/release#2313]
We just merged a couple of optional jobs (see https://github.com/openshift/release/pull/2293 and https://github.com/openshift/release/pull/2309) and they seem to be running on PRs w/o having them requested (see https://github.com/openshift/openshift-azure/pull/824#issuecomment-444517722).

/kind bug

**Comment by kargakis** [comment]
@openshift/sig-azure fyi

**Comment by kargakis** [comment]
FWIW it seems they run on PRs only initially and on subsequent retests they arent

**Comment by stevekuznetsov** [comment]
Yeah, this is a bug in the new `status-reconciler` component

/close

https://github.com/kubernetes/test-infra/pull/10348

**Comment by kargakis** [comment]
Do you need to rebase openshift/test-infra?
