### ISSUE TITLE
gather-must-gather step failing on ocp 4.6 and 4.7

### ISSUE THREAD

**Issue by mrhillsman** [openshift/release#23175]
/kind bug

/area test-execution

## What did you expect to happen?
I expected to see a successful run of the gather step.

## What happened?
When running a job where OpenShift 4.6 or 4.7 is claimed from the ci cluster pool the gather-must-gather step fails.

## How can the error be reproduced?
We trigger the CI environment by manually adding a ProwJob. That ProwJob requests a cluster from the CI cluster pool of a version of OpenShift; currently 4.6-4.9. We run the following steps:

Pre:
ipi-install-rbac
Test:
operator-pipelines-preflight-common-decrypt
operator-pipelines-preflight-common-check
operator-pipelines-preflight-common-encrypt
Post:
gather

The gather post step is failing when OpenShift 4.6 or 4.7 is the cluster claimed. Output from both can be seen here:
[4.6 run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/22985/rehearse-22985-periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.6-preflight-common-claim/1455172336574533632)
[4.7 run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/22985/rehearse-22985-periodic-ci-redhat-openshift-ecosystem-preflight-ocp-4.7-preflight-common-claim/1455172336704557056)

/cc @smarterclayton @wking @vrutkovs @abhinavdahiya @deads2k @ewolinetz @csrwng @staebler

**Comment by vrutkovs** [comment]
The step runs correctly in [other 4.6 jobs](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.6-e2e-gcp/1455393074468360192#1:build-log.txt%3A35).
Seems the step failed in your jobs since kube-apiserver couldn't rollout

**Comment by mrhillsman** [comment]
thx @vrutkovs
