### ISSUE TITLE
images job fails: unable to upload layer sha256:... to destination repository: unknown blob

### ISSUE THREAD

**Issue by wking** [openshift/release#2340]
/kind bug

`images` job for the installer, but likely not installer-specific.

## What happened?

[logs][1]:

```
info: Included 45 referenced images into the payload
Uploading ... 55.64kB/s
error: uploading the source layer sha256:ca9154981764613b2849b53c599da7a3a7037f772173af642815c3e91bea7060 failed: unable to upload layer sha256:ca9154981764613b2849b53c599da7a3a7037f772173af642815c3e91bea7060 to destination repository: unknown blob
2018/12/07 22:30:45 Container release in pod release-latest failed, exit code 1, reason Error
```

I'm reporting the flake here in case there's anything useful in the ci.openshift.com logs, but this is likely a registry bug/flake.

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/793/pull-ci-openshift-installer-master-images/1560/build-log.txt

**Comment by stevekuznetsov** [comment]
@mfojtik @legionus
