### ISSUE TITLE
the retester bot is broken

### ISSUE THREAD

**Issue by kargakis** [openshift/release#2348]
```
{"component":"entrypoint","error":"could not start the process: fork/exec /bin/commenter: no such file or directory","level":"error","msg":"Error executing test process","time":"2018-12-10T15:34:35Z"}
```
https://openshift-gce-devel.appspot.com/builds/origin-ci-test/logs/periodic-retester/

Looks broken ever since [2018-12-03 15:28 CET](https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/periodic-retester/2100/)

@stevekuznetsov @bbguimaraes @petr-muller @droslean 
/kind bug

**Comment by petr-muller** [comment]
Looks like another fallout from our migration to upstream images (which have binaries put into a different place).

**Comment by stevekuznetsov** [comment]
oh boy
