### ISSUE TITLE
Tracer is dead after we no longer build it ourselves

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#2374]
https://tracer-ci.svc.ci.openshift.org/ is down.

After https://github.com/openshift/release/commit/b2665d0be2216db58947d927ae9d3d09e971ba61#diff-732194a40c01839cb14c35bcd6331495 we no longer build Prow binaries ourselves and later https://github.com/openshift/release/commit/936af6d428dd494469d81d04dba270caa38f9415#diff-652864204e272998aa934002826b44b0 removed a reference to the ImageStream and replaced it with a `refresh` image reference (which is probably a mistake). Now the Deployment fails because it tries to pass tracer params to the refresh binary.

It does not seem upstream builds the image for tracer, though, so fixing it is not a matter of simply ixing the image name.

/cc @stevekuznetsov 

/kind bug

**Comment by stevekuznetsov** [comment]
Hrm. Seems like a major mistake on my end. We should get `tracer` built upstream.

**Comment by petr-muller** [comment]
Why was this closed? The referenced PR did not resolve the problem.

**Comment by droslean** [comment]
@petr-muller good point. We still have to create the image upstream (gcr.io/k8s-prow/tracer:v20190109-716fe27)
