### ISSUE TITLE
config-updater failed to deploy because it does not have `--github-token-path` param

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#2375]
In https://github.com/openshift/release/commit/f1c565e47908702f93dc081024685e82063799c7#diff-7a22377df068e20b9fcaa99661eedcaf, a parameter `--github-token-file` (deprecated by upstream) was replaced by `--github-token-path` everywhere but our config-updater still only has `--github-token-file` (https://github.com/openshift/test-infra/blob/master/experiment/config-updater/main.go#L40) only. This probably made a [rolling update](https://api.ci.openshift.org/console/project/ci/browse/rc/config-updater-8?tab=details) to fail. I have fixed it in place and the deployment succeeded.

I wanted to follow up and fix it also in https://github.com/openshift/release/blob/master/cluster/ci/config/prow/openshift/config-updater/deployment.yaml#L36. Then I realized maybe the `config-updater` should be modified to follow upstream convention. Then I discovered the upstream has a `updateconfig` plugin, which I am not sure why we are not using. Hence, this issue to discuss how to best resolve this.

/cc @stevekuznetsov 

/kind bug

**Comment by stevekuznetsov** [comment]
The upstream `updateconfig` just puts data into `ConfigMaps`. The `config-updater` (ugh, naming) does `Templates` and `Lists`.

We should rebase `openshift/test-infra` and update the `config-updater` code. What a mess

/assign

**Comment by stevekuznetsov** [comment]
Actually thinking about this more, we should just run `make <something>` on a postsubmit for `openshift/release` and call it a day.

**Comment by stevekuznetsov** [comment]
Then we can remove the deployment entirely

**Comment by petr-muller** [comment]
Hm, one less thing to worry about sounds good. Plus, it forces us to keep the `make <something>` in good shape.

**Comment by bbguimaraes** [comment]
This was something I considered in the context of the synchronization necessary for the staging namespace. Isn't there a similar argument to be made for both services?

Currently we have the following problem:

- we have make commands that can be used to bootstrap, but are not executed post-submit
- we have services that are executed post-submit, but cannot be used to bootstrap*

Therefore we have duplicate definitions of the bootstraping/update configuration. If we are proposing to create a post-submit job that executes `make` commands (and I don't see a reason not to), do we still need the upstream and downstream services?

\* as I mentioned in our discussion yesterday, there is [an issue upstream](https://github.com/kubernetes/test-infra/issues/8892) to add the bootstrap capability to the upstream service

**Comment by stevekuznetsov** [comment]
We now have a postsubmit.

/close
