### ISSUE TITLE
Move jobs on prow

### ISSUE THREAD

**Issue by kargakis** [openshift/release#238]
https://jenkins-origin-ci.svc.ci.openshift.org/job/origin-ci-base-image-pipeline/
https://jenkins-origin-ci.svc.ci.openshift.org/job/origin-ci-build-tools/

We probably want to run these as presubmits whenever something changes in the underlying sources. We will also take advantage of max_concurrency because running them outside of prow bypasses the field.

cc @stevekuznetsov @csrwng

**Comment by csrwng** [comment]
@kargakis I guess that means we need to redefine them as standalone jobs and remove the corresponding pipeline buildconfig

**Comment by kargakis** [comment]
Can't we use jenkins to trigger from the build configs?

**Comment by csrwng** [comment]
we can... still means that we need a standalone jenkins job. Might as well create one to do the actual build. The Jenkins jobs are really trivial to define because all they need is a SCM location for the pipeline to run.
