### ISSUE TITLE
Ensure new jenkins data is persisted

### ISSUE THREAD

**Issue by kargakis** [openshift/release#239]
Now that we run blocking PR jobs.

/assign @csrwng @stevekuznetsov

**Comment by csrwng** [comment]
Added pv to jenkins on origin-ci ... but we really need a make target to set everything up. Will create a PR for that

**Comment by csrwng** [comment]
@kargakis not sure how a statefulset would help us. afaik jenkins only supports a single master.

**Comment by kargakis** [comment]
The pattern deployment+pvc is really a statefulset, independent of scaling.

**Comment by kargakis** [comment]
@csrwng is the make target in place now?

**Comment by csrwng** [comment]
Yes it is https://github.com/openshift/release/blob/master/Makefile#L154
