### ISSUE TITLE
prow-config-semantics requires me to set a specific run command

### ISSUE THREAD

**Issue by kargakis** [openshift/release#2457]
In https://github.com/openshift/release/pull/2456, I am adding an optional `pull-ci-openshift-openshift-azure-master-e2e-azure-vnet` job with `/test vnet` as a command to run the job. The semantics job requires me to set it to `/test e2e-azure-vnet`. I think it's much simpler if this kind of judgement is left to a human and at least ensure there are no duplicate commands in our jobs. Also, there is a bug in the semantics job: if I add more than one `--target`, the job will succeed ie. won't require me to set a specific command.

/shrug

@stevekuznetsov @petr-muller @bbguimaraes

**Comment by stevekuznetsov** [comment]
If you want it to be called `vnet`, call the job `vnet` too. There's no way to sanely break these things out.
