### ISSUE TITLE
sync github teams in the CI cluster

### ISSUE THREAD

**Issue by kargakis** [openshift/release#2552]
At the moment, we maintain our own [CI group](https://github.com/openshift/release/blob/master/projects/azure/cluster-wide.yaml) which is essentially duplicating [`sig-azure`](https://github.com/orgs/openshift/teams/sig-azure). We should be able to take advantage of the github integration in the CI cluster and sync github teams to openshift groups.

/kind enhancement

**Comment by stevekuznetsov** [comment]
Who is the audience for this issue? Is there an existing team sync that OpenShift provides?

**Comment by petr-muller** [comment]
We have `group-auto-updater` which we could repurpose for this if needed, provided the team would be tracked with Peribolos.

/close
