### ISSUE TITLE
ordered-prow-config nonsensical requirement

### ISSUE THREAD

**Issue by kargakis** [openshift/release#2586]
We are trying to add a PR job that is not using a status context in github (see https://github.com/openshift/release/pull/2585). The ordered-prow-config job result doesn't make much sense.
```
[ERROR] This check enforces Prow Job configuration YAML file format (ordering,
[ERROR] linebreaks, indentation) to be consistent over the whole repository. We have
[ERROR] automation in place that manipulates these configs and consistent formatting
[ERORR] helps reviewing the changes the automation does.

[ERROR] Run the following command to re-format the Prow jobs:
[ERROR] $ docker run -it -v $(pwd)/ci-operator/jobs:/jobs:z registry.svc.ci.openshift.org/ci/determinize-prow-jobs:latest --prow-jobs-dir /jobs

[ERROR] The following errors were found:

diff -Naupr -I '^[[:space:]]*#.*' /tmp/tmp.QeYl3I8WIF/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml hack/../ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml
--- /tmp/tmp.QeYl3I8WIF/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml	2019-01-15 09:35:00.255525900 +0000
+++ hack/../ci-operator/jobs/openshift/openshift-azure/openshift-openshift-azure-master-presubmits.yaml	2019-01-15 09:35:02.066692619 +0000
@@ -4,6 +4,7 @@ presubmits:
     always_run: true
     branches:
     - master
+    context: ""
     decorate: true
     name: pull-ci-openshift-openshift-azure-master-codecov
     rerun_command: /test codecov
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_release/2585/pull-ci-openshift-release-master-ordered-prow-config/2987
/kind bug
@petr-muller @stevekuznetsov @bbguimaraes

**Comment by petr-muller** [comment]
All the job does is parse-and-save using the test-infra code, and the reason for what you see is that `Context` is not marked as optional here, so the default value is marshalled and not omitted: https://github.com/kubernetes/test-infra/blob/master/prow/config/jobs.go#L121

If we are sure that having an empty context is okay then the proper fix is probably to mark the field as optional upstream.

**Comment by stevekuznetsov** [comment]
@kargakis please stop pushing the boundaries. You're just making your life harder. Set a status and `skip_report`

**Comment by kargakis** [comment]
Yeah, merged an empty context.
