### ISSUE TITLE
tcp timeouts occuring in OSA CI tests

### ISSUE THREAD

**Issue by kargakis** [openshift/release#2608]
We have been experiencing a specific test flake for a long time and we cannot seem to be able to reproduce outside of CI. MSFT has confirmed that they haven't seen it either in their tests. The tests are not doing anything crazy, they simply stand up a cluster in Azure, then query the api server to healthcheck nodes, and infra components. In short, every now and then our tests fail with a tcp timeout. 

> I think that `read: connection timed out` means that the TCP socket send buffer still holds outgoing data (written by the HTTP client) which it has being trying to send to the server for some time, but which the server has not acknowledged.
>
> The client is trying to read the HTTP response from the socket, and the local TCP stack injects an error because it is timing out the send (and the read is never going to succeed). In all of the examples of this issue that I've seen, the timeout is about 17 minutes. See tcp(7), tcp_retries2 for more information.

For more context, see https://github.com/openshift/openshift-azure/issues/560.

Has this issue been observed in other CI tests? Any ideas on how to debug further? @smarterclayton  @stevekuznetsov 

cc @openshift/sig-azure

**Comment by stevekuznetsov** [comment]
This could be the load balancer in GCP for api.ci acting up?

**Comment by mjudeikis** [comment]
yes, it might be :/ 
we seen less of these so closing. But we suspect this is lb config and how it handles long hanging tcp sessions
/close
