### ISSUE TITLE
No useful log information available from test failure

### ISSUE THREAD

**Issue by coreydaley** [openshift/release#2648]
/kind bug

/area test-artifacts

## What did you expect to happen?
I expect to be able to view useful logging information about why the test failed

## What happened?
The test ran for 3 hours and did not produce any useful artifacts

## How can the error be reproduced?
It seems to happen frequently on my image registry operator pull requests

## Is there anything else we need to know?
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-image-registry-operator/167/pull-ci-openshift-cluster-image-registry-operator-master-e2e-aws-image-registry/293

**Comment by stevekuznetsov** [comment]
We need to identify a run while in-progress or quickly after it fails and dump the events from the namespace, as mentioned on Slack. 

/cc @smarterclayton

**Comment by stevekuznetsov** [comment]
@smarterclayton is this `ci-operator` artifacts nonsense?
