### ISSUE TITLE
Enable CI configuration to co-exist with repos under test

### ISSUE THREAD

**Issue by kargakis** [openshift/release#2672]
Essentially a "make the openshift prow deployment work like travis".

It will be much more convenient if we can run all of our tests 1. locally, 2. manually using the CI cluster, and 3. automatically in prow, using a single repo.

Today we can only do 1. in `openshift-azure`, 2. and 3. in `release`. This also creates the requirement that we have to duplicate our instructions and secret placement across two different paths in our filesystems: `openshift-azure/secrets/` and `release/cluster/test-deploy/azure/`.

Also, it is going to be easier for newcomers to our project to get started with our CI.

/kind feature

@smarterclayton @stevekuznetsov @petr-muller @droslean @bbguimaraes @openshift/sig-azure

**Comment by kargakis** [comment]
I guess what we mainly need is enabling at least 2. in which case we move over the ci-operator config and templates while still keeping the prowjobs in the release repo for the automated tests to continue working appropriately.

**Comment by stevekuznetsov** [comment]
It's really never going to happen, I think. There's too much momentum and too much to gain from having it in one repo. Moving that for Prow would be a massive undertaking and I'm not even sure it will be allowed from a trust perspective upstream. Have you used the staging namespace? What is missing for your needs?

**Comment by droslean** [comment]
@stevekuznetsov Can this work if they enable the `config-updater` for their repo? I mean that of course, the `config-updater` won't find the paths that are meant to be for `release` repo. Will, that create any problem?

**Comment by stevekuznetsov** [comment]
So so so so many things about Prow and our config structure assume this will never happen. I really don't want to even consider the implications of trying to hack it together with something like `config-updater` instead of implementing it top-down correctly.

Again, I repeat:

If the goal is reproducible builds and dev debugging, have you all used the staging namespace? Will the rehearsals suffice? We _are_ working on this problem and our solutions are either already deployed or almost there -- have you used them? What is missing? Let's focus on making them better.

**Comment by kargakis** [comment]
> Have you used the staging namespace? What is missing for your needs?

I don't think we do but it doesn't sound like it would address any of the issues I am bringing up here. I can try spelling out our situation better:
1. Local testing of our e2es (`make e2e`) can only be done in our repo. Manually testing the e2e job, using the ci-operator image can only be done in `openshift/release`. Ideally, we want our developers to be familiar with both ways of running tests and keeping the necessary config to run the ci-operator job in our repo is more convenient because 2. and 3.
2. Our e2e jobs use various credentials. We have to replicate instructions on how to run these jobs and credentials placement in two different repos instead of one. More maintainance burden instead of less.
3. It's more difficult for newcomers to get their head around how our repo interacts with `openshift/release`. The learning curve is much bigger. Most people are familiar with travis-like configuration when it comes down to tweak CI.

The problem is not debugging, we can run ci-operator jobs locally just fine. The problem is conveniency and the learning curve required today to master our CI jobs.

**Comment by stevekuznetsov** [comment]
> Local testing of our e2es (make e2e) can only be done in our repo. Manually testing the e2e job, using the ci-operator image can only be done in openshift/release.

Write a script that clones latest `openshift/release` to some temp location, cache it, and hide that from users?

> Our e2e jobs use various credentials. 

Work with us to ensure our staging workflow works for you.

> It's more difficult for newcomers to get their head around how our repo interacts with openshift/release.

This is mostly self-inflicted. Can it be hidden?

**Comment by kargakis** [comment]
I guess caching release is an alternative solution, there is potential to improve our flows just by doing that. 

@mjudeikis @charlesakalugwu

**Comment by petr-muller** [comment]
@stevekuznetsov , given `ci-operator` will probably never be used without files from `openshift/release`, maybe we could implement a helper option in `ci-operator` directly to fetch the config from there? All you would need to provide would be a repo, and perhaps allow to override org (default to openshift) and branch (default to master)... Could be useful for everyone.

**Comment by stevekuznetsov** [comment]
Sure, we could do that. Would need to add `git` to the `ci-operator` container image

**Comment by petr-muller** [comment]
Or simply reach out to GH for a raw file via HTTP - it's not that GH is a wonderful file hosting service but it could suffice for fetching YAMLs.

**Comment by stevekuznetsov** [comment]
Would be worried about token usage on that, but we could do some math to see if it would work

**Comment by stevekuznetsov** [comment]
Oh, but it's on the user end. Could use unauthenticated API access and be fine
