### ISSUE TITLE
pipelines: build pods don't get the prow labels, sinker ignores them

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#271]
There doesn't seem to be a simple way to get the build pods to be labeled with `created-by-prow=true` so they stick around. We also don't have the `BuildConfig`-level history limits. Maybe `sinker` can delete the `Build`s themselves and cascade to get the `Pod`?

/cc @kargakis @csrwng

**Comment by kargakis** [comment]
We can't change sinker to handle builds w/o patching. Better have a GC controller for builds. Even better, assuming we had a top-level prow controller for builds (https://github.com/openshift/release/issues/267), we could make it set owner references from prow jobs to builds, so prowjob deletion could cascade to builds+pods thanks to the k8s GC.

**Comment by stevekuznetsov** [comment]
@csrwng you fixed this right?

**Comment by csrwng** [comment]
Yes, the pipeline now deletes the builds it creates.
