### ISSUE TITLE
pipelines: need better metrics for health signal

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#283]
We need to start brainstorming about Prometheus metrics we can be using to track the health of the system

/cc @kargakis @csrwng @paradigm

**Comment by stevekuznetsov** [comment]
Some ideas:

 - time for test pods to go from created to scheduled
 - breakdown of reasons (???) why test pods get killed (is it OOM? is it the process dying?)
 - for well-known stage names in the pipelines, runtime duration over time for each stage
 - jenkins health/heartbeat?

**Comment by kargakis** [comment]
Yes on everything.

**Comment by stevekuznetsov** [comment]
We want a metric for:

 - % of limit that max rss hits for all of our test pods
 - % of limit that our jenkins pv is at
