### ISSUE TITLE
ipi-install-install step alternative restoring from snapshot

### ISSUE THREAD

**Issue by kaovilai** [openshift/release#28473]
We do not require latest openshift images to run our end to end tests on openshift-ci. A latest stable should suffice.

There should be a way to run our end to end tests by giving us the desired cluster version by restoring from a snapshot rather than starting from a new cluster from openshift-installer every time.

It should be possible I feel to install once, snapshot all disks of all master/workers and give the cluster to some running jobs.
These snapshots may only work to restore these set of clusters due to networking configs among other things. This is fine.

The snapshot may only be used by one running cluster at a time. When the job is finished, cluster is deprovisioned per usual.
When another cluster is requested, the cluster disk snapshots from earlier are used to restore this cluster again to a newly installed state for another user.

You would have more than one sets of snapshots for restoring a number of clusters for each jobs.

If running jobs exceed number of available snapshots to restore a test cluster, only then do we fall back to fresh install using [ipi-install-install](https://steps.ci.openshift.org/reference/ipi-install-install) which takes 40 minutes to complete.

This would reduce many number of compute hours used since a good chunk of cluster install time is removed from majority of day to day usage.

I propose you use hibernate feature of openshift to help achieve this.
https://github.com/openshift/hive/blob/master/docs/hibernating-clusters.md

**Comment by bbguimaraes** [comment]
See https://docs.ci.openshift.org/docs/architecture/ci-operator/#testing-with-a-cluster-from-a-cluster-pool.

**Comment by kaovilai** [comment]
Thanks.
