### ISSUE TITLE
Support onboarding new repo to ci-operator via scaffolding

### ISSUE THREAD

**Issue by chancez** [openshift/release#2848]
/kind feature

It would be great if you could use ci-operator or another tool to scaffold out the files required to onboard a new repository. Currently it's somewhat difficult to find a good example to start from, and having it generated means we can always update the default files generated when best practices change.

CC @stevekuznetsov

**Comment by petr-muller** [comment]
/close

We have `repo-init` now: https://github.com/openshift/ci-tools/tree/master/cmd/repo-init
