### ISSUE TITLE
path-label: better label for upstream pulls necessary

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#287]
From [here](https://github.com/openshift/origin/pull/16864#issuecomment-336990150):

>I guess my first reaction was color{red} = PR is blocked and the needs-* prefix makes me think that action is required. When really, it is an annotation and only blocking if there is a rebase gate in place. Maybe a non-red label color and rather than "needs-upstream" maybe just "upstream" or "vendor-patch"?

/assign @kargakis

**Comment by kargakis** [comment]
I like `vendor-patch` or `vendor-change`.

**Comment by kargakis** [comment]
Or `vendor-update`

**Comment by kargakis** [comment]
@smarterclayton @soltysh @sttts @mfojtik @deads2k  thoughts

**Comment by sttts** [comment]
is it for PRs changing vendor/ (like adding or bumping a dependency) or just for those with new UPSTREAM commits?

**Comment by soltysh** [comment]
+1 for `vendor-change` or `vendor-update`. `needs-upstream` with red gives you false information about it. This is more of an information about the contents of the PR.

**Comment by kargakis** [comment]
> is it for PRs changing vendor/ (like adding or bumping a dependency) or just for those with new UPSTREAM commits?

What's the difference between the two? Both change `/vendor`, no?

**Comment by kargakis** [comment]
OK, I've changed the label to `vendor-update` and the color to something akin to turquoise. Let me know if you have any objections.
