### ISSUE TITLE
always_run ignored on existing PR's

### ISSUE THREAD

**Issue by mjudeikis** [openshift/release#2904]
Each time we merge  `optional: true` and `always_run: false` jobs, it triggers them on all PR.
In example this got merged:
https://github.com/openshift/release/commit/1ef240f5c077d15fb7af795b1f133a0fb962adb6

And now all PR's got:
![image](https://user-images.githubusercontent.com/3225744/53006906-1bbcaa80-342e-11e9-909c-7c7669512c4c.png)

/kind bug

**Comment by petr-muller** [comment]
Looks like a bug in the reconciler.

/cc @stevekuznetsov

**Comment by mjudeikis** [comment]
It does not do this for new PR's just for existing :/

**Comment by petr-muller** [comment]
Yeah, that's what status reconciler does - it watches changes in job configuration and propagates them to existing PRs - triggers newly added jobs, retires contexts of those removed, etc. Here it seems to be triggering some jobs that should not be triggered.

**Comment by stevekuznetsov** [comment]
This should have been fixed.... And this issue is a dupe of another from Michalis

**Comment by mjudeikis** [comment]
We saw this morning. Any chance this is not rolled out? Michalis who? :)

**Comment by stevekuznetsov** [comment]
Fixed by https://github.com/kubernetes/test-infra/pull/11369
