### ISSUE TITLE
release-latest registry.svc.ci.openshift.org/ci-op-hdsq08kg/stable@sha256:...: 504 Gateway Time-out

### ISSUE THREAD

**Issue by wking** [openshift/release#2905]
/kind bug
/area test-execution

## What did you expect to happen?

A successful e2e-aws run.

## What happened?

From [the build log][1] of an openshift/installer#1163 run:

```
Loading manifests from machine-config-operator: sha256:ff6f606c19b6f4a6f5b22444af61d304c220d68c666c11c74f9823bb9b9fb10b ...
error: unable to read image registry.svc.ci.openshift.org/ci-op-hdsq08kg/stable@sha256:cd30230b8b0fbd2cfcca3040f99a376c86f5f8abca441fb85165d48d1e23ba97: received unexpected HTTP status: 504 Gateway Time-out
2019/02/19 09:23:08 Container release in pod release-latest failed, exit code 1, reason Error
```

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/1163/pull-ci-openshift-installer-master-e2e-aws/3905/build-log.txt

**Comment by wking** [comment]
Same issue over [here][1].

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_hive/222/pull-ci-openshift-hive-master-e2e/97

**Comment by droslean** [comment]
It seems that `stable` imagestream wasn't even created in the temporary namespace. I'll take a look.

**Comment by droslean** [comment]
Same issue with the namespaces that `stable` imagestream exists. Syncing with registry team, the issue should be that the registry is trying to pull from itself, and it creates a neverending loop.

**Comment by droslean** [comment]
/close

The issue was resolved. Related [PR](https://github.com/openshift/image-registry/pull/161). Ci cluster's registry has already been patched.
