### ISSUE TITLE
question: release image version bump

### ISSUE THREAD

**Issue by hexfusion** [openshift/release#2913]
The etcd image Dockerfiles do not properly add the client binary etcdctl. I am about to commit the changes to https://github.com/openshift/etcd/tree/openshift-4.0 branch. My question is how do we handle the image bump with regards to versioning? Does this change just get pulled in or do we need to version the change with a version bump in the config?

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/etcd/openshift-etcd-openshift-4.0.yaml

**Comment by bbguimaraes** [comment]
Simply merge to master, that is going to trigger this job:

https://deck-ci.svc.ci.openshift.org/?job=branch-ci-openshift-etcd-openshift-4.0-images

It will build the image and push it to the CI registry. The release payload will also be updated to include it.

**Comment by hexfusion** [comment]
@bbguimaraes thanks for the quick reply.
