### ISSUE TITLE
Update MCO owners to include MCO team on PRs

### ISSUE THREAD

**Issue by kikisdeliveryservice** [openshift/release#2980]
As brought to my attention in a recent PR #2975 the MCO Owners are out of date and not pinging the current members of the MCO team.

These two files are out of date:
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/machine-config-operator/OWNERS
https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/machine-config-operator/OWNERS

Can you please add the current members of the MCO team to these files so that we are alerted to PRs that involved our project.  

For reference - MCO team: @kikisdeliveryservice @runcom @cgwalters @LorbusChris

**Comment by stevekuznetsov** [comment]
Those configurations are for teams to self-manage -- please update the files at your discretion and submit a PR.

**Comment by kikisdeliveryservice** [comment]
will do, thanks @stevekuznetsov !
