### ISSUE TITLE
client connections from outside the cluster to the API are killed after 30 seconds

### ISSUE THREAD

**Issue by deads2k** [openshift/release#3]
Making a connection from outside the CI cluster to the API are killed after 30 seconds. You can see this the network pane from a browser, via the CLI using the `-w` flag, and via direct curl statements.

When you make API requests from inside the cluster, the connections are not killed.  Use curl from inside a pod (since there's the in-cluster config bug preventing reasonable use of the tools: https://github.com/kubernetes/kubernetes/issues/38834).

That suggests a router or load balancer in the infrastructure.

**Comment by smarterclayton** [comment]
Yes, the master is behind a GCE load balancer.  Might be a gap in the ref arch we need to fix.

**Comment by smarterclayton** [comment]
The load balancer has a "detect dead backends when they don't send any response within X seconds".  I set it to 2 minutes, but this is actually more of a bug in our watch logic (where we wait to send *any* bytes).  I may move this upstream.
