### ISSUE TITLE
question: config nesting clarification

### ISSUE THREAD

**Issue by hexfusion** [openshift/release#3013]
question: `github.com/openshift/kubecsr` has 3 separate binary deliverables. 

* kube-aws-approver
* kube-client-agent
* kube-etcd-signer-server

It was unclear from the my reading of the docs if the below was valid. Nesting multiple separate images under the repo name.   

```
ci-operator/config/openshift/kubecsr/
├── openshift-kube-client-agent-openshift-4.0.yaml
├── openshift-kube-etcd-signer-server-openshift-4.0.yaml
└── OWNERS
```

Or does this require a separate base directory for each such as

```
ci-operator/config/openshift/kube-client-agent/
ci-operator/config/openshift/kube-etcd-signer-server/
```

/kind question

**Comment by hexfusion** [comment]
To be clear each package has its own Dockerfile in the same repo.

**Comment by petr-muller** [comment]
Building multiple images from a single repo is achieved *inside* the ci-operator config file, see e.g. the [openshift/origin one](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/origin/openshift-origin-master.yaml#L27)

So you should have this file structure:

```
ci-operator/config/openshift/kubecsr/
|--- openshift-kubecsr-$BRANCH.yaml
|--- OWNERS
```

and inside the file multiple items in the `images:` list

**Comment by hexfusion** [comment]
@petr-muller thanks a lot
