### ISSUE TITLE
api.ci setup blocking openshift/jenkins PR image building

### ISSUE THREAD

**Issue by gabemontero** [openshift/release#3074]
/kind bug

/area test-execution

The last successful openshift/jenkins ci/prow/images build was https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/814/pull-ci-openshift-jenkins-master-images/100

Something changed, apparently with mirrors for yum installs, since then on api.ci

Now all openshift/jenkins PRs are failing with 

```
Downloading packages:
http://base-4-0.ocp.svc/rhel-server-ose/Packages/atomic-openshift-clients-4.0.22-1.git.0.219bbe2.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

http://base-4-0.ocp.svc/rhel-server-ose/Packages/dumb-init-1.1.3-12.el7.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.


Error downloading packages:
  dumb-init-1.1.3-12.el7.x86_64: [Errno 256] No more mirrors to try.
  atomic-openshift-clients-4.0.22-1.git.0.219bbe2.el7.x86_64: [Errno 256] No more mirrors to try.
```

the last run from https://github.com/openshift/jenkins/pull/816 was https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/816/pull-ci-openshift-jenkins-master-images/120

also seeing with https://github.com/openshift/jenkins/pull/817 where the last run is https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/817/pull-ci-openshift-jenkins-master-images/119

@bparees @adambkaplan fyi

**Comment by bparees** [comment]
@stevekuznetsov @smarterclayton

**Comment by smarterclayton** [comment]
Where is dumb-init coming from?

**Comment by gabemontero** [comment]
We've been installing it since 3.9 @smarterclayton 

When we dropped it in via https://github.com/openshift/jenkins/pull/422, we did not have to add any new repos in the Dockerfile.rhel7 in order to pull it in.  

And the discussion in the PR talks about it being in copr.

So simplistically, it is in rhel7.

Also found this old email thread where the dude tells us he added it to copr:  https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2017-March/msg00021.html

Based on https://rpms.remirepo.net/rpmphp/zoom.php?rpm=dumb-init it has been in fedora since v26

And as I mentioned in the description, it was installing fine until later afternoon yesterday.

If that doesn't sufficiently answer it, then we are beyond my level of know how.

**Comment by smarterclayton** [comment]
Everything passes for me.  I can repeatably build master and publish as
prow jobs.

**Comment by smarterclayton** [comment]
Also, why are you installing the openshift clients RPM?  you should already
be based on the CLI image.

**Comment by gabemontero** [comment]
Yep the image build is now passing again in https://github.com/openshift/jenkins/pull/816 after at least 12 failures over 24 hours based on https://openshift-gce-devel.appspot.com/pr/openshift_jenkins/816

thanks @smarterclayton for whatever fix you introduced (or if you simply looking at this chased away whatever flake was occurring ... couldn't tell from https://github.com/openshift/release/issues/3074#issuecomment-472245567 )

On the client RPM ... yep, that make sense ... both @bparees and I simply missed that in https://github.com/openshift/jenkins/pull/774 when the switch to the cli image occurred.

I'll address that.
