### ISSUE TITLE
optional-operators-subscribe should accept list of operators

### ISSUE THREAD

**Issue by kaovilai** [openshift/release#31162]
https://steps.ci.openshift.org/reference/optional-operators-subscribe
https://github.com/openshift/release/blob/master/ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh

Would be cool if the following could accept a comma separated list if our test require more than one operator installed.
https://github.com/openshift/release/blob/98a8c015e76303b150c9bd8f1797e9a8a44f4982/ci-operator/step-registry/optional-operators/subscribe/optional-operators-subscribe-commands.sh#L33-L37

This mean we can reuse the current implementation of optional-operators-subscibe and don't have to implement operator installation in our e2e test makefile/go/etc.

**Comment by bbguimaraes** [comment]
DPTP are not the maintainers, please contact the owners.  They are listed in the page you linked: https://steps.ci.openshift.org/reference/optional-operators-subscribe#owners.

/close
