### ISSUE TITLE
Jenkins builds go missing 

### ISSUE THREAD

**Issue by kargakis** [openshift/release#326]
We have had a bunch of reports lately about Jenkins builds being reported as missing in Github. These builds are actually missing from Jenkins, eg. there is no 1671 build for https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install/ or 2911 for https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_update/

These builds were actually started at some point via prow (see details) but for a mysterious reason they went missing in Jenkins.

cc: @stevekuznetsov @dobbymoodge 

<details>

```yaml
- apiVersion: prow.k8s.io/v1
  kind: ProwJob
  metadata:
    clusterName: ""
    creationTimestamp: 2017-10-25T21:04:00Z
    generation: 0
    name: 05d1863c-b9c8-11e7-bfbb-0a58ac100ed4
    namespace: ci
    resourceVersion: "9999559"
    selfLink: /apis/prow.k8s.io/v1/namespaces/ci/prowjobs/05d1863c-b9c8-11e7-bfbb-0a58ac100ed4
    uid: 05d23433-b9c8-11e7-8297-42010a800002
  spec:
    agent: jenkins
    context: ci/openshift-jenkins/upgrade
    job: test_pull_request_openshift_ansible_extended_conformance_install_update
    pod_spec: {}
    refs:
      base_ref: master
      base_sha: 305e4897dd6591ee8055414f80e43275696558d2
      org: openshift
      pulls:
      - author: michaelgugino
        number: 5891
        sha: db50b11f29ee95fa6128257141bba9c39fe36de3
      repo: openshift-ansible
    report: true
    rerun_command: /test upgrade
    type: presubmit
  status:
    build_id: "2911"
    completionTime: 2017-10-25T21:43:02.501832264Z
    description: Error finding Jenkins job.
    pod_name: test_pull_request_openshift_ansible_extended_conformance_install_update-2911
    startTime: 2017-10-25T21:04:00.030471048Z
    state: error
    url: https://github.com/kubernetes/test-infra/issues
```
</details>

**Comment by dobbymoodge** [comment]
I suspect these were swallowed when ci.openshift OOMed and had to be rebooted yesterday. Is something breaking because they're missing?

**Comment by dobbymoodge** [comment]
Maybe there's some additional cleanup we need to do when ci.openshift reboots? If so, we should document that.

**Comment by stevekuznetsov** [comment]
I think these are the exception and not the norm -- they most likely went missing when we rebooted Jenkins since it did not get a chance to serialize all state onto disk.

**Comment by kargakis** [comment]
This shouldn't recur then but it is: 4 builds are missing from https://ci.openshift.redhat.com/jenkins/job/test_pull_request_openshift_ansible_extended_conformance_install_containerized/ (1524-1527) and these are from today.

**Comment by kargakis** [comment]
More jobs seems to miss builds too? Did we restart Jenkins again?

**Comment by stevekuznetsov** [comment]
@dobbymoodge ^^

**Comment by kargakis** [comment]
Haven't seen this in a while - closing
