### ISSUE TITLE
ci-operator: support for "dynamic" branches

### ISSUE THREAD

**Issue by vdemeester** [openshift/release#3364]
/kind question

Discussed with @pmorie earlier this week, one thing we end up creating a pull-request to enalbe CI on each new release branches on, for example, `knative` components (see https://github.com/openshift/release/pull/3342).

I was wondering if it would be possible (somehow) to support smarter patterns for those, like for example any branches that has satisfies the following regexp `release-v(\d).(\d).(\d)` would have job automatically created / enabled.  Some "dynamic" ci configuration :angel:.

That would reduce the amount of pull-request to do for each branches we create downstream and thus reduce the number of review required here :angel:

**Comment by stevekuznetsov** [comment]
Prow allows scheduling jobs on branch regex but what we saw in the past was that without fail jobs went stale, config rotted and nobody forked jobs when they needed to. Forking preemptively fixes that. How often do you create release branches? To regenerate jobs you just copy paste the ciop config right? How much work is it?

**Comment by stevekuznetsov** [comment]
Also I'll say you're hitting this as you don't follow the common branching patterns, those repos get branches and ci automatically. Maybe we could make those tools useful for you too and reduce workload.

**Comment by vdemeester** [comment]
> Prow allows scheduling jobs on branch regex but what we saw in the past was that without fail jobs went stale, config rotted and nobody forked jobs when they needed to. Forking preemptively fixes that. How often do you create release branches? To regenerate jobs you just copy paste the ciop config right? How much work is it?

@stevekuznetsov good points (on config rotted, etc..). I think it's manageable :wink: I was just wondering.

> Also I'll say you're hitting this as you don't follow the common branching patterns, those repos get branches and ci automatically. Maybe we could make those tools useful for you too and reduce workload.

I'm interested in that :angel:

**Comment by stevekuznetsov** [comment]
Let me finish up the work for branching etc and I will publish docs on how it's set up.

**Comment by chancez** [comment]
I'd be interested in this too. Part of the need stems from the rebase workflow of taking an upstream release and applying our changes on top. I don't see how CI could create these branches for us automatically so I don't really think your proposed idea would work for us.

We do plan to keep creating branches for each upstream release however, the biggest problem is I'm not really sure how these branches would be automatically tracked into a `release-` branch like we have currently for master. Currently we're on master because thats what we were told to do for 4.1, but that won't work once we need to rebase on top of a new upstream release.

**Comment by stevekuznetsov** [comment]
Yeah, we need to hash out a design for forks. I might try to write some ideas up and get feedback soon, was focused on the non-fork branching recently.

**Comment by chancez** [comment]
I'm also realizing, ART is likely to have to handle this also right? Need to include them in the discussion as well.
