### ISSUE TITLE
Prometheus issues in api.ci

### ISSUE THREAD

**Issue by kargakis** [openshift/release#345]
1. Getting a 500 in the UI
2. The prometheus log is full of warnings and errors like
```
level=error ts=2017-11-01T17:18:22.102842875Z caller=wal.go:683 component=tsdb msg="sync failed" err="flush buffer: write data/wal/000017: file already closed"
level=warn ts=2017-11-01T17:18:24.617463917Z caller=scrape.go:673 component="target manager" scrape_pool=kubernetes-nodes target=https://10.128.0.8:10250/metrics msg="append failed" err="WAL log samples: log series: write data/wal/000017: file already closed"
```
3. One of the node exporters is crashlooping with
```
container_linux.go:247: starting container process caused "exec: \"--collector.procfs=/host/proc\": stat --collector.procfs=/host/proc: no such file or directory"
```
cc: @smarterclayton @stevekuznetsov

**Comment by smarterclayton** [comment]
Known bug, you have to rsh in, delete the entire data dir, and restart.

**Comment by smarterclayton** [comment]
Also, update prometheus to rc2 (see my PR to origin) to avoid that issue.

**Comment by kargakis** [comment]
Interesting - we already run rc2.

**Comment by smarterclayton** [comment]
Hrm, if so can you find the prometheus issue that reports this and indicate
we're seeing it on rc2 (if the issue was closed - if it's still open
comment that we have a reproducer and try to grab the profiles / whatever
was needed)?

**Comment by kargakis** [comment]
The issue is still open (https://github.com/prometheus/prometheus/issues/3283) but I restarted the server yesterday because I am hunting down a different issue in our prow cluster.

**Comment by kargakis** [comment]
I can't see any request latency metrics related to prowjobs. Do we collect custom resource metrics in the api server? Specifically, I am interested in request latencies for POSTing prowjobs. Some of our logs hint to slow updates but I don't know whether I can trust that.

http://pastebin.test.redhat.com/528855

Out of 2m35s spent in a single resync, the jenkins-operator spends most of its time (1m27s) trying to update a single prowjob.
```
{"client":"kube","level":"debug","msg":"ReplaceProwJob(8af22b99-bf13-11e7-97f4-0a58ac100fab, {prow.k8s.io/v1 ProwJob {8af22b99-bf13-11e7-97f4-0a58ac100fab ci map[] map[] 11353547 8af32a51-bf13-11e7-8297-42010a800002} {presubmit jenkins test_pull_request_origin_unit release-3.6:008f2d5528bf998326b5eb3f1fe3144c59392b9d,17131:54fa4874dd66a830c4de9e2af8d103d9ad8a9200 true ci/openshift-jenkins/unit /test unit 0 {[] []  map[]} []} {2017-11-01 14:47:11.449999922 +0000 UTC 0001-01-01 00:00:00 +0000 UTC pending Jenkins job enqueued.   }})","time":"2017-11-01T14:48:35Z"}
{"client":"kube","level":"debug","msg":"ReplaceProwJob(8af4a922-bf13-11e7-97f4-0a58ac100fab, {prow.k8s.io/v1 ProwJob {8af4a922-bf13-11e7-97f4-0a58ac100fab ci map[] map[] 11353549 8af55c50-bf13-11e7-8297-42010a800002} {presubmit jenkins origin-ci-int-origin release-3.6:008f2d5528bf998326b5eb3f1fe3144c59392b9d,17131:54fa4874dd66a830c4de9e2af8d103d9ad8a9200 false ci/openshift-jenkins/experimental/integration /test origin-it 0 {[] []  map[]} []} {2017-11-01 14:47:11.466320904 +0000 UTC 0001-01-01 00:00:00 +0000 UTC pending Jenkins job enqueued.   }})","time":"2017-11-01T14:50:03Z"}
```

**Comment by smarterclayton** [comment]
We can collect metrics from prow, just update the prow service to have the
prometheus.io/scrape=true annotation

**Comment by kargakis** [comment]
We already collect metrics from prow (hook for now). What I am asking is metrics from the apiserver about requests to CustomResources.

**Comment by smarterclayton** [comment]
It looks like a bug, please ping upstream.

**Comment by kargakis** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/55146
