### ISSUE TITLE
3.11 e2e-gcp tests seem to be skipping *ALL* the ginkgo suites

### ISSUE THREAD

**Issue by gabemontero** [openshift/release#3647]
/kind bug
/kind question

/area test-execution

## What did you expect to happen?

I expected these tests:

```
[Feature:Builds][Slow] openshift pipeline build Sync plugin tests using the ephemeral template [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline build Sync plugin tests using the persistent template [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline build jenkins-client-plugin tests using the ephemeral template [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test connection test [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test create obj delete obj [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test exec DSL [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test exec freestyle [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test imagestream SCM DSL [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test imagestream SCM [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test multitag DSL [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test multitag [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test trigger build DSL [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test trigger build including clone [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test trigger build with envs [Suite:openshift]

[Feature:Builds][Slow] openshift pipeline plugin jenkins-plugin test context jenkins-plugin test trigger build with slave [Suite:openshift]

```

to have been run, and see some confirmation of that in both https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/844/pull-ci-openshift-jenkins-openshift-3.11-e2e-gcp/47 and https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_jenkins/844/pull-ci-openshift-jenkins-openshift-3.11-e2e-gcp/47/artifacts/e2e-gcp/container-logs/test.log.gz
## What happened?

Those tests were listed as part of the Skipped tests

## How can the error be reproduced?

retest e2e-gcp in https://github.com/openshift/jenkins/pull/844

## Is there anything else we need to know?

Looks like it has been broke for a bit, and I just noticed it now.  

Best as I can tell, the last job to successfully run the tests was https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_jenkins/753/pull-ci-openshift-jenkins-openshift-3.11-e2e-gcp/12 
from PR https://github.com/openshift/jenkins/pull/753 back in December 2018

Perhaps before the 4.0 openshit-ansible changes kicked in later that month .. in case that has any bearing ??

**Comment by stevekuznetsov** [comment]
@smarterclayton

**Comment by stevekuznetsov** [comment]
Those tests have

```yaml
        - name: TEST_COMMAND
          value: TEST_FOCUS=Suite:openshift/conformance/parallel TEST_FOCUS_SERIAL=Suite:openshift/conformance/serial/minimal
            run-tests
```

**Comment by gabemontero** [comment]
hmmmm .... it is suppose to be https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/jenkins/openshift-jenkins-openshift-3.11-presubmits.yaml#L31-L36

```
        - name: PREPARE_COMMAND
          value: tag-in-image.sh
        - name: RPM_REPO_OPENSHIFT_ORIGIN
          value: https://rpms.svc.ci.openshift.org/openshift-origin-v3.11/
        - name: TEST_COMMAND
          value: TEST_FOCUS='openshift pipeline' TEST_PARALLELISM=3 run-tests

```

**Comment by stevekuznetsov** [comment]
Not sure -- @smarterclayton can you advise

**Comment by stevekuznetsov** [comment]
@gabemontero you can open a PR to change it and the rehearsals should test it for you

**Comment by gabemontero** [comment]
sorry @stevekuznetsov - change what exactly ?

**Comment by stevekuznetsov** [comment]
The TEST_COMMAND from the value it is today to what you linked instead?

**Comment by gabemontero** [comment]
ok but *where* do I make that change @stevekuznetsov ?

I thought the fact I had it like that in the 3.11 presumit was what was required?  which other file do I need to update ?

**Comment by gabemontero** [comment]
you mean change the template at https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e-openshift-jenkins.yaml#L256 and make it what is listed in the presubmit ?

**Comment by gabemontero** [comment]
wait ... or are you saying open a dummy PR and use the rehearsal jobs to help debug @stevekuznetsov ?

(sorry if I'm dense wrt this stuff)

**Comment by stevekuznetsov** [comment]
I pulled my link from `ci-operator/jobs/openshift/origin/openshift-origin-release-3.11-presubmits.yaml` -- I would imagine if the Origin 3.11 jobs do run the correct tests and the Jenkins ones do not, then yes let's make the templates in sync and correct the command for the Jenkins jobs

**Comment by gabemontero** [comment]
10-4 I'll do a diff on the base template and the jenkins snowflake template and report back

And then if need be compare presubmits/postsubmits with a functional 3.11 repo

**Comment by gabemontero** [comment]
@stevekuznetsov - after a few debug runs, I see the call to ginkgo occurring as I would expect, with `TEST_FOCUS` and `TEST_PARALLELISM` getting their values from the presubmit as I would expect.

However, that call to `ginkgo` simply does not execute any tests.

I then went back and looked at a recent openshift/origin 3.11 PR I had ... https://github.com/openshift/origin/pull/22623

In there, I see that the ginkgo extended tests are still the old jenkins/aos-cd-jobs based stuff.  Like https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22623/test_pull_request_origin_extended_builds_311/45/

There is also an e2e-gcp run in there, and it looks just like the one for my 3.11 Jenkins PR ... where ultimately no tests are executed.  See https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/22623/pull-ci-openshift-origin-release-3.11-e2e-gcp/273

That presumably is using the standard, non-jenkins, cluster-launch-e2e.yaml template at https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e.yaml, right?

If so, it would imply that something is up with either ginkgo binary or exact syntax of the ginkgo invocation perhaps?

Also, I think https://github.com/openshift/release/blob/master/ci-operator/templates/openshift/openshift-ansible/cluster-launch-e2e.yaml has moved recently, as it doesn't much in the way of git history ... that seem plausible?

Or maybe all these questions require @smarterclayton input.... but it seems `e2e-gcp` is maybe generally non functional ?? .... I couldn't figure out how to view the 3.11 e2e-gcp runs across all PRs, to get some general feel about it.

Pending any insight from y'all on the above, I'm going to just start hacking on the call to `ginkgo` in that template, see if I can get something to work.

**Comment by gabemontero** [comment]
Found this nugget:  https://github.com/openshift/origin/blob/release-3.11/test/extended/setup.sh#L7-L9

```
function os::test::extended::focus () {
	if [[ "$@[@]" =~ "ginkgo.focus" ]]; then
		os::log::fatal "the --ginkgo.focus flag is no longer supported, use FOCUS=foo <suite.sh> instead."
		exit 1
	fi
```

And have changed the template to use `-focus` vs. `--ginkgo.focus` ... we'll see what happens ...
