### ISSUE TITLE
Running tests that require kubeconfig and s3 bucket

### ISSUE THREAD

**Issue by hexfusion** [openshift/release#3675]
I am trying to get etcd-operator into release and I have a question with regards to testing. To run the test suite the script needs access to KUBECONFIG and an s3 bucket via aws secret.

https://github.com/coreos/etcd-operator/blob/master/hack/test

What would be the best approach here?

**Comment by stevekuznetsov** [comment]
If you add a test stanza like this:

https://github.com/openshift/release/blob/b05852c0f7cf57b11be737f433fc1f4d8cf80be1/ci-operator/config/openshift/ansible-service-broker/openshift-ansible-service-broker-master.yaml#L67-L73

Your test runs with a `$KUBECONFIG` pointing to the test cluster created for your job and in AWS.

**Comment by hexfusion** [comment]
perfect thanks @stevekuznetsov
