### ISSUE TITLE
PR test fails with mkdir: cannot create directory ‘/go’: Permission denied

### ISSUE THREAD

**Issue by sbouchet** [openshift/release#37743]
/kind question

/area test-execution

## What did you expect to happen?
We've setup a PR hook for https://github.com/redhat-developer/intellij-openshift-connector and it fails to run the tests from our repo

## What happened?
see https://github.com/redhat-developer/intellij-openshift-connector/pull/520 for an example of our workflow. 
openshift-ci bot try to run our integration test suite but can't clone the repo : 

{"command":"PWD=/  mkdir -p /go/src/github.com/redhat-developer/intellij-openshift-connector","component":"clonerefs","error":"exit status 1","file":"k8s.io/test-infra/prow/pod-utils/clone/clone.go:85","func":"k8s.io/test-infra/prow/pod-utils/clone.Run.func2","level":"info","msg":"Ran command","output":"mkdir: cannot create directory ‘/go’: Permission denied\n","severity":"info","time":"2023-03-24T09:37:24Z"}

from https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_intellij-openshift-connector/520/pull-ci-redhat-developer-intellij-openshift-connector-main-e2e-4.11/1639199579666649088

**Comment by droslean** [comment]
@sbouchet 

How this image is being maintained? https://github.com/openshift/release/blob/master/ci-operator/config/redhat-developer/intellij-openshift-connector/redhat-developer-intellij-openshift-connector-main.yaml#L2-L5

ref: registry.ci.openshift.org/openshift/ubi8-openjdk-11:1.12

**Comment by droslean** [comment]
/close

I am closing this issue. @sbouchet Please reach out to slack for any further questions.
