### ISSUE TITLE
ci-operator/populate-owners fails

### ISSUE THREAD

**Issue by adambkaplan** [openshift/release#3864]
/kind bug

## What did you expect to happen?
ci-operator/populate-owners.sh succeeds

## What happened?
Failed:
```
failed to fetch https://api.github.com/repos/openshift/azure-misc/commits/HEAD: 403 403 Forbidden
Cloning into '/tmp/populate-owners-757913806'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I believe the azure-misc repo has been deleted.

## How can the error be reproduced?
Run populate-owners.sh

## Is there anything else we need to know?
No.

**Comment by stevekuznetsov** [comment]
Can you just delete all the files referencing that repo?

**Comment by adambkaplan** [comment]
I'll add it to my PR to fix openshift/library

**Comment by ehashman** [comment]
This repo is not deleted, it's private. I guess this PR explains why merges stopped working a few weeks ago.
