### ISSUE TITLE
ci-operator/populate-owners hits Github rate limits

### ISSUE THREAD

**Issue by adambkaplan** [openshift/release#3867]
/kind question

## What did you expect to happen?

`ci-operator/populate-owners.sh` downloads are not throttled.

## What happened?

Downloads get throttled - the populate-owners.sh script eventually encounters a 403, then does very slow clones to extract the owners file for the respective repo.

Can we provide an API token so we don't get throttled?

## How can the error be reproduced?

Run ci-operator/populate-owners.sh

## Is there anything else we need to know?

No

**Comment by stevekuznetsov** [comment]
We could, but it's maybe a bit overkill?

**Comment by petr-muller** [comment]
We no longer use that thing.

/close
