### ISSUE TITLE
job artifacts show .log extension but are .gz

### ISSUE THREAD

**Issue by bparees** [openshift/release#4124]
/kind bug
/area test-artifacts

The .log files located here:
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/2640/artifacts/e2e-aws-upgrade/container-logs/

are actually .gz files upon download.  Can we either get them to have the proper extension or make them not gzipped?  The current experience is confusing.

**Comment by stevekuznetsov** [comment]
@smarterclayton do you remember what the bug here was? we chased it but I forgot ...

**Comment by wking** [comment]
openshift/release-controller#99 was the most recent attempt to fix `/logs/`, and links out to earlier steps.

**Comment by stevekuznetsov** [comment]
Are we running an old version of the release controller? @smarterclayton what's deployed?

**Comment by smarterclayton** [comment]
HEAD of master.

**Comment by petr-muller** [comment]
/close

I don't think this happens anymore.
