### ISSUE TITLE
jenkins-config-updater cannot create processedtemplates.template.openshift.io in the namespace "ci"

### ISSUE THREAD

**Issue by kargakis** [openshift/release#417]
```
$ /usr/bin/make applyTemplate WHAT=cluster/ci/jobs/commenter.yaml
oc process -f cluster/ci/jobs/commenter.yaml | oc apply -f -
error: unable to process template
  User "system:serviceaccount:ci:jenkins-config-updater" cannot create processedtemplates.template.openshift.io in the namespace "ci": User "system:serviceaccount:ci:jenkins-config-updater" cannot create processedtemplates.template.openshift.io in project "ci"
error: no objects passed to apply
make: *** [applyTemplate] Error 1

exit status 2
```
from https://github.com/openshift/release/pull/416#issuecomment-346039121

/assign @paradigm @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Hmmm...

```
$ oc adm policy who-can create processedtemplates.template.openshift.io
Namespace: ci
Verb:      create
Resource:  processedtemplates.template.openshift.io

Users:  system:admin

Groups: system:cluster-admins
        system:masters
```

**Comment by stevekuznetsov** [comment]
The SA has `edit` role in the namespace, why is this not enough?

**Comment by bparees** [comment]
sounds like a security team question.  I don't know why edit wouldn't be able to create that resource.

**Comment by enj** [comment]
I confirmed that `system:serviceaccount:ci:jenkins-config-updater` has `edit` in the `ci` namespace and can run the `oc process` command.

The `who-can` command is misleading here because discovery fails for `processedtemplates.template.openshift.io` (see https://github.com/openshift/origin/issues/16648):

```
$ oc auth can-i create processedtemplates.template.openshift.io --as=system:serviceaccount:ci:jenkins-config-updater -n ci

Warning: the server doesn't have a resource type 'processedtemplates' in group 'template.openshift.io'
no - User "system:serviceaccount:ci:jenkins-config-updater" cannot create processedtemplates.template.openshift.io in project "ci"
```

Because it runs (see the incorrect `resource` and no `group`):

```
{
   "status" : {
      "allowed" : false,
      "reason" : "User \"system:serviceaccount:ci:jenkins-config-updater\" cannot create processedtemplates.template.openshift.io in project \"ci\""
   },
   "spec" : {
      "resourceAttributes" : {
         "namespace" : "ci",
         "verb" : "create",
         "resource" : "processedtemplates.template.openshift.io"
      }
   },
   "kind" : "SelfSubjectAccessReview",
   "apiVersion" : "authorization.k8s.io/v1",
   "metadata" : {
      "creationTimestamp" : null
   }
}
```

Running with a resource that works correctly during discovery:

```
$ oc auth can-i create template.template.openshift.io --as=system:serviceaccount:ci:jenkins-config-updater -n ci

yes
```

Because it runs this (see the correct `resource` and `group`):

```
{
   "metadata" : {
      "creationTimestamp" : null
   },
   "kind" : "SelfSubjectAccessReview",
   "spec" : {
      "resourceAttributes" : {
         "resource" : "templates",
         "namespace" : "ci",
         "group" : "template.openshift.io",
         "verb" : "create"
      }
   },
   "status" : {
      "reason" : "allowed by openshift authorizer",
      "allowed" : true
   },
   "apiVersion" : "authorization.k8s.io/v1"
}
```

@deads2k @mfojtik any reason we do not register `ProcessedTemplate` using `AddKnownTypeWithName` in the grouped scheme?

https://github.com/openshift/origin/blob/be64d51a5165c6d15d86433629d8ccbe464aa4ff/pkg/template/apis/template/register.go#L77-L78

@kargakis not sure why you saw the RBAC error - probably was something transient with the shared informer that is used by the authorizer.

**Comment by stevekuznetsov** [comment]
😢

**Comment by bparees** [comment]
@stevekuznetsov @kargakis see my comment in https://bugzilla.redhat.com/show_bug.cgi?id=1518501#c4

what's your delta between the oc client you're using(possibly the one inside the jenkins image) and your cluster version?

**Comment by stevekuznetsov** [comment]
Ah, slight version skew

```
$ oc exec jenkins-22-lb286 -n origin-ci -- oc version
oc v3.7.0-alpha.1+84e0585-1160
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://172.30.0.1:443
openshift v3.7.0-rc.0+bd64aab-99
kubernetes v1.7.6+a08f5eeb62
```

**Comment by bparees** [comment]
that shouldn't be enough to cause a problem i wouldn't think, but @liggitt or @deads2k would know for sure if there are known issues between those two versions.

also if you're running this on master, it's possible your openshift discovery cache is broken in some weird way, so you could try clearing it.  (if you're doing it on a slave, you'd have a clean cache each time)

**Comment by deads2k** [comment]
> @deads2k @mfojtik any reason we do not register ProcessedTemplate using AddKnownTypeWithName in the grouped scheme?
> 
> https://github.com/openshift/origin/blob/be64d51a5165c6d15d86433629d8ccbe464aa4ff/pkg/template/apis/template/register.go#L77-L78

Looks like a bug.

**Comment by bparees** [comment]
isn't it being added to the group scheme here:
https://github.com/openshift/origin/blob/be64d51a5165c6d15d86433629d8ccbe464aa4ff/pkg/template/apis/template/register.go#L58

?

**Comment by deads2k** [comment]
> isn't it being added to the group scheme here:
> https://github.com/openshift/origin/blob/be64d51a5165c6d15d86433629d8ccbe464aa4ff/pkg/template/apis/template/register.go#L58

The name it is registered with matters for compiled conversion purposes.  We should move off us using the compiled set entirely, but  until we do the distinction has meaning.

**Comment by bparees** [comment]
@deads2k sorry i'm still not clear what has to be done or who should be doing it....

**Comment by stevekuznetsov** [comment]
@enj @deads2k @liggitt is this also causing this line we see in builds on this cluster?

```
I1207 18:56:05.762900       1 request.go:994] Response Body: User "system:serviceaccount:ci-openshift-ansible:default" cannot get builds.build.openshift.io in the namespace "ci-openshift-ansible": User "system:serviceaccount:ci-openshift-ansible:default" cannot get builds.build.openshift.io in project "ci-openshift-ansible"
```

**Comment by stevekuznetsov** [comment]
OK NVM that looks like a legit (but very surprising) RBAC denial?

```
$ oc adm policy who-can get builds.build.openshift.io
Namespace: ci-openshift-ansible
Verb:      get
Resource:  builds.build.openshift.io

Users:  system:admin
        ...
        system:serviceaccount:ci-openshift-ansible:builder
        system:serviceaccount:ci-openshift-ansible:jenkins
        system:serviceaccount:ci-openshift-ansible:jenkins-admin
        system:serviceaccount:ci-openshift-ansible:jenkins-config-updater
        ...
```
