### ISSUE TITLE
Unable to create release cluster-nfd-operator

### ISSUE THREAD

**Issue by zvonkok** [openshift/release#4352]
/kind question

/area test-artifacts

## What did you expect to happen?

Tests
```
ci/prow/images
ci/prow/e2e-test
ci/prow/e2e-aws-upgrade
```
to run successfully. 

## What happened?
The `ci/prow/images` and the other tests exits with the following log:

```
2019/07/11 18:13:38 Create release image registry.svc.ci.openshift.org/ci-op-7inhd11d/release:latest
info: Using registry public hostname registry.svc.ci.openshift.org
info: Found 167 images in image stream
....
info: Loading sha256:143d935f01e63e6c94f6caf8bf3d7d4e23787cc46a976e751c18e10236905c71 support-operator
info: Included 90 images from 32 input operators into the release
error: unable to create a release: cluster-nfd-operator/nfd.package.yaml: manifests must contain Kubernetes API objects with 'kind' and 'apiVersion' set: 
2019/07/11 18:15:19 Container release in pod release-latest failed, exit code 1, reason Error
2019/07/11 18:15:25 Ran for 3m25s
```
Where is `cluster-nfd-operator/nfd.package.yaml` coming from? Is it autogenerated?
What manifests are expected here? 

## How can the error be reproduced?
Triggering a test on cluster-nfd-operator.

**Comment by droslean** [comment]
Well, It seems that the image `support-operator` is corrupted in some way. 

The config in `cluster-nfd-operator` repo is using the `4.2` imagestream in `ocp` namespace. ref: [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-nfd-operator/openshift-cluster-nfd-operator-master.yaml#L26-L28)

Also I can see in the configs, that the `promotion` of this image is disabled.  ref: [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/support-operator/openshift-support-operator-release-4.2.yaml#L18)

@smarterclayton Do we need to enable the promotion of this image?

**Comment by zvonkok** [comment]
It was disabled on purpose, because the current master promotes to 4.2 as discussed here: https://github.com/openshift/release/pull/4304#discussion_r301201902

**Comment by droslean** [comment]
> It was disabled on purpose, because the current master promotes to 4.2 as discussed here: #4304 (comment)

@zvonkok I am talking about the `support-operator` promotion, [here](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/support-operator/openshift-support-operator-release-4.2.yaml#L18)

**Comment by petr-muller** [comment]
> @zvonkok I am talking about the `support-operator` promotion

Same thing applies though, **all** masters  are promoting to 4.2 and promotion is disabled on 4.2 branches everywhere.

**Comment by petr-muller** [comment]
@zvonkok Looks like this file https://github.com/openshift/cluster-nfd-operator/blob/master/controller-manifests/nfd.package.yaml present in your image somehow interferes with the way how the release is created (`oc adm release` command inside ci-operator). I don't know what that file is, but `oc adm release` expects it to contain API objects.

**Comment by zvonkok** [comment]
I am following the doc: "Red Hat Operators - Productization Docs - Part 1", the `contoller-manifest`  folder contains the CSVs, CRDs, and package manifest files (nfd.package.yaml) for OLM.

Why does `oc adm release` expects the this specific file contains API objects? A yaml or json file could be configuration file, like in this case ...

**Comment by petr-muller** [comment]
> Why does oc adm release expects that this specific file contains API objects? A yaml or json file could be configuration file, like in this case ...

I don't know. We don't own `oc adm release`. Not sure who does, though. Might be worth asking on `#4-dev-triage` channel on Slack.

**Comment by smarterclayton** [comment]
NFD isn’t part of the payload, so if you are causing failures that means you’ve done something wrong.  Please speak with your group lead about the right thing to do here

/hold

**Comment by zvonkok** [comment]
If I remove the controller-manifests the all tests pass.

**Comment by zvonkok** [comment]
Comparing my tests and config with cluster-logging-operator I do not see major differences in the  test-confgs or how manifests for OLM are handled. 

I see that cluster-logging-operator is not creating the complete release payload with all cluster operators. 
Is there I am something obvious missing in configuring the ci-operator jobs?

**Comment by zvonkok** [comment]
The error was that I had two conflicting labels in my Dockerfile:
```
#1 io.openshift.release.operator=true 
#2 com.redhat.delivery.appregistry=true
```
after removing the first the tests pass successfully. 

@petr-muller  thanks for helping out.
