### ISSUE TITLE
[RFE] pass pull request information into pod

### ISSUE THREAD

**Issue by thoraxe** [openshift/release#467]
Our test situation is a little different than normal. Currently the CI system is launching a pod that has a script embedded in it. This script launches a test environment on AWS and then executes tests inside that environment.

In order to pull the right artifacts to test into said environment, we need to know the information about the pull request so that we can fetch the PR owner's repo.

For example, our repo is openshift/openshift-cns-testdrive
A PR might come from some_user/openshift-cns-testdrive and their branch is feature-thing

We at a minimum need to know some_user and feature-thing inside our pod.

**Comment by thoraxe** [comment]
@stevekuznetsov Per your request. Let me know if this makes sense.

**Comment by kargakis** [comment]
Fixed I believe
