### ISSUE TITLE
Consider creating a "ci-dev.openshift.org" cluster

### ISSUE THREAD

**Issue by cgwalters** [openshift/release#4892]
Today, "api.ci" AKA https://api.ci.openshift.org/ is fairly critical infrastructure.  It manages tests and generates release images for the primary OpenShift release to customers (in concert with separate behind-the-RHT-firewall infrastructure).

However, there are also a number of other CI-related flows that occur on this cluster, from Prow/ci-operator driven tests of pull requests from external contributors, and there's certainly some other "freeform" code, mostly in the [projects directory](https://github.com/openshift/release/tree/master/projects).

Proposal
====

Retain the primary release infrastructure here, and create a distinct "ci-dev" cluster for the stuff in `projects/`.  In addition, I would like this cluster to support at least `RunAsUser: 0` workflows.

Rationale
===

First, I am working on CoreOS related CI, and not supporting `RunAsUser: 0` basically destroys the ergonomics of everything.  The way the OS works today is "unions" of packages, and not being able to easily spin up a container and have it e.g. replace `/usr/bin` would require completely reworking everything.

Having a separate cluster which supports `RunAsUser: 0` would unblock us without risking the primary release infrastructure.

Longer term of course, [user namespaces](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/node-usernamespace-remapping.md) are the better solution here, but that's not going to happen soon.

Also, deploying a separate ci-dev cluster would be a great opportunity to have it run e.g. 4.2 and ensure that we're finally dogfooding the latest again in CI!

Prow
===

Probably the biggest question here is whether "ci-dev" takes over the Prow flows or not.  If it did, then I think "api.ci" would shrink down to basically running the primary release/test infrastructure,  separate from pull request processing.  There are certain advantages to this in that we clearly want to favor primary releases over pull request testing, although clearly both are critical.

**Comment by cgwalters** [comment]
Alternatively of course for now we could just add `RunAsUser: 0` to the `coreos` namespace (where I'm trying to move our projects).

**Comment by stevekuznetsov** [comment]
I think we do not want to support root containers in test jobs but if they are carefully curated things in a project it can be permissible. I don't think DPTP can handle the operational burden of running two clusters, unfortunately.

**Comment by cgwalters** [comment]
> I don't think DPTP can handle the operational burden of running two clusters, unfortunately.

A lot of the idea behind 4.x is that it's a self-driving cluster remember!  If running it's a burden, that's a bug!

**Comment by stevekuznetsov** [comment]
> A lot of the idea behind 4.x is that it's a self-driving cluster - if running it is a burden, that's a bug!

When we fire the ops and SRE teams, let me know :)

**Comment by cgwalters** [comment]
For reference this is for https://github.com/openshift/release/pull/4880

Now...the CoreOS group also has resources in [CentOS CI](https://console.apps.ci.centos.org:8443/console) which is both bare metal and has granted us a `0` SCC (though not privileged note).  (The RHCOS team also has internal resources but that has the "behind the firewall problem".

I think any path we take will involve federation/dispatching of some kind.

We want to use the Prow instance maintained here rather than own a separate one for hopefully obvious reasons.  However, our CI jobs here may end up scheduling pods on CentOS CI or another cluster (or have the other cluster(s) poll us for work).

Short term, I am going to investigate pairing up Prow jobs here with CentOS CI.

**Comment by cgwalters** [comment]
OK, I wrote this doc:  https://github.com/coreos/coreos-assembler/blob/master/doc/openshift-gcp-nested-virt.md

Here's my new request:

- DPTP stands up cluster in GCP, follows the above doc to enable nested virt.  Call this the "ci-dev" cluster, or maybe someone will come up with a better name.
- DPTP sets up glue in this repository that updates that cluster; something like a `cidev/projects` subdirectory (or we create a separate `openshift/ci-dev-cluster` repo e.g.)
- CoreOS and other groups can submit PRs which create projects there (I suspect e.g. the libvirt installer folks would like this too)

All groups work together on defining a nice way for Prow jobs to schedule pods in ci-dev.  Put all together this will allow us to have a really nice flow for testing that can run disposable/transient VM workloads - also in a fairly cloud-agnostic way, so if we e.g. want to instead use AWS `i3.metal` instances, or simply use time on a real bare metal installation we can do so.

**Comment by stevekuznetsov** [comment]
A federated build cluster where nested virt and general privileged pods are allowed SGTM. When we do the work to get us using federation, this is a great idea.

**Comment by cgwalters** [comment]
> and general privileged pods 

Let's not call them "privileged", rather "uid 0 containers"... see also https://lwn.net/Articles/796700/ and my reply: https://lwn.net/Articles/796885/

**Comment by cgwalters** [comment]
(In Kubernetes/OpenShift terms, `runAsUser: 0`, not `privileged: true`)

**Comment by cgwalters** [comment]
Steve are you actively working on this?  Do you have any idea of a timeframe?  Anything I can do to help?  I know DPTP has a ton going on.  

In the short term, I am going to experiment a bit with doing this myself.  Today I:

 - Stood up a 4.2 cluster in GCP called `coreosci` and did the nested virt setup.
 - Put the admin kubeconfig for it in the `coreos` namespace in api.ci
 - Created a `coreos-pull-requests` project and unprivileged serviceaccount
 - Started looking at how the main Prow jobs that launch a cluster deal with the IaaS cred secrets, as we'd need to do a similar thing with a Prow job here that used the serviceaccount token to launch a pod in the coreos ci cluster

**Comment by stevekuznetsov** [comment]
Let's sync over video Thursday? (I'm out tomorrow)

**Comment by cgwalters** [comment]
> Let's sync over video Thursday? (I'm out tomorrow)

Sure, SGTM; feel free to pick an open time.  Morning EST is a bit easier.

**Comment by cgwalters** [comment]
OK, we have [a secret that should allow scheduling pods](https://github.com/openshift/release/pull/5440) set up.

@stevekuznetsov do you think you'd have some time to help me get a basic Prow job set up that spawns a pod in the coreosci cluster going?  I've read through the Prow docs some but I'm not seeing how to point it at a separate cluster.

**Comment by cgwalters** [comment]
Steve says:

> [...] it should be as easy as passing that via kubeconfig flag to plank
> And targeting your context with job config

So I need to figure that out.

**Comment by hongkailiu** [comment]
Starting point ... no hurry though :)
https://github.com/openshift/release/pull/5847
