### ISSUE TITLE
release-ci: run-build will get stuck in a failed state if a previous build failed

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#502]
If no code changes but a build failed for whatever reason, today all subsequent pipelines just `cat` the logs of the failed build and throw up their hands. Can we do better? If we notice the build is already finished and failed, can we delete it and re-create? I don't think so, since that's super racy with the other threads that could be using it. Could we instead sort the builds by timestamp, allowing us to not require unique build names?

/cc @csrwng

**Comment by csrwng** [comment]
So it will be stuck until any of those pipelines finish and clean up the build. Is that not the case?

**Comment by stevekuznetsov** [comment]
We will clean up builds.

/close
