### ISSUE TITLE
api-ci cluster: PVCs are created and bound, but PV (sometimes) disappears and kubelet cannot mount GCE volume

### ISSUE THREAD

**Issue by sttts** [openshift/release#529]
The problem described in the title happened multiple times, reproducible. Now some hours later it works again. The kube events of the pods are:

```
  Warning  FailedMount  2m (x816 over 1d)    kubelet, origin-ci-ig-n-kwtq  Unable to mount volumes for pod "publisher_sttts(9de06364-f130-11e7-b676-42010a800002)": timeout expired waiting for volumes to attach/mount for pod "sttts"/"publisher". list of unattached/unmounted volumes=[publisher-gopath]
  Warning  FailedMount  53s (x528 over 17h)  attachdetach                  AttachVolume.Attach failed for volume "pvc-2b0c79e1-e006-11e7-b676-42010a800002" : GCE persistent disk not found: diskName="kubernetes-dynamic-pvc-2b0c79e1-e006-11e7-b676-42010a800002" zone="us-central1-a"
```

Here are the complete kubectl outputs: https://gist.github.com/sttts/1fc7c1e072fcf5540085a4320bf397a1

The pods were created through https://github.com/kubernetes/publishing-bot/blob/master/Makefile using `KUBECTL=oc make run` in the sttts namespace.

**Comment by stevekuznetsov** [comment]
/cc @smarterclayton 
The disk actually doesn't exist in GCE

**Comment by smarterclayton** [comment]
Possible race condition in dynamic provisioner on GCE?  @openshift/sig-storage are we aware of any cases where a dynamically provisioned GCP volume on 3.7 / 1.7 could be deleted due to races?

**Comment by jsafrane** [comment]
I am not aware of any races there. Do we have controller-manager logs?
