### ISSUE TITLE
https://github.com/openshift/release/blob/master/services/coreos/admin_group.yaml missing

### ISSUE THREAD

**Issue by cgwalters** [openshift/release#5499]
We're missing https://github.com/openshift/release/blob/master/services/coreos/admin_group.yaml 
I think a cluster admin needs to run `make services-admin`?  Is there no automation for that?

**Comment by stevekuznetsov** [comment]
We try not to have admin level credentials mutating the cluster in automated jobs, so yes that's manual on purpose.
