### ISSUE TITLE
[RFE] Add FIPS tests to inform the 4.3 promote job

### ISSUE THREAD

**Issue by miabbott** [openshift/release#5853]
(Not sure if this is the best place to track this, but going to start here)

To ensure that the FIPS enablement work does not regress, we would like to add a test that runs the OpenShift installer with FIPS enabled to the job that promotes the 4.3 `machine-os-content`

I believe the job in question is `release-promote-openshift-machine-os-content-e2e-aws-4.3` and we need a set of tests to validate FIPS works before the job passes.

From @nee1esh 

> The goal is to make sure that when new drop of RHCOS gets promoted into OpenShift a FIPS test is run to ensure
> 1. Node comes-up in FIPS mode post-install.
> 2. maybe in future, cluster comes up in FIPS mode.
> 3. Even better (in the future) if we can run one of the e2e (say AWS e2e) in FIPS mode to make sure nothing is regressing with the new change.
> Main goal is to avoid the regression we had and cover various regression surfaces via this test

I've spoken to @cgwalters and @vrutkovs about possibly helping out with this.

If there are other details that I have missed, please add them in the comments.

cc: @ashcrow

**Comment by cgwalters** [comment]
Hmm, if I understand correctly this is already covered by
https://prow.svc.ci.openshift.org/job-history/origin-ci-test/logs/release-openshift-ocp-installer-e2e-aws-fips-4.3
(Click on the `aws-fips` link from https://openshift-release.svc.ci.openshift.org/ on the 4.3 art stream)

This job is recently green...so I think the task is to figure out whether this is actually correctly passing now.

**Comment by cgwalters** [comment]
The machine-os-content promotion job is important though in ensuring that e.g. `cri-o` updates land in the release which is then tested by `aws-fips`.

**Comment by vrutkovs** [comment]
machine-os-content promotion in 4.3 has been disabled temporarily due to OKD-on-FCOS work. Once it goes green its just a matter of:

a) creating a new release:
   https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml#L154-L164

b) running necessary tests - both fips and upgrade I assume?
   https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/release/openshift-release-release-4.2-periodics.yaml#L166-L172

**Comment by cgwalters** [comment]
> machine-os-content promotion in 4.3 has been disabled temporarily due to OKD-on-FCOS work.

Wait whaa?  https://prow.svc.ci.openshift.org/?job=release-promote-openshift-machine-os-content-e2e-aws-4.3 seems fine.  Why would OKD have disabled this?

**Comment by vrutkovs** [comment]
>Why would OKD have disabled this?

It does work now, but it hasn't been re-enabled since then. We'll look into this soon
