### ISSUE TITLE
Explore allowing users to run tests with high loglevel verbosity

### ISSUE THREAD

**Issue by kargakis** [openshift/release#588]
Requested in https://github.com/openshift/release/pull/581#issuecomment-363762348

cc @stevekuznetsov @sdodson

**Comment by stevekuznetsov** [comment]
Specific case of general "how do I parameterize a presubmit from GitHub for one run" problem?

**Comment by kargakis** [comment]
Yes, there are two cases so far that people have requested parameterizing test excution (the other being running focus on extended). I have been thinking about making these external plugins in prow, instead of trying to parameterize `/test`.
