### ISSUE TITLE
registry.redhat.io looking for authentication for images like openjdk-11-rhel8:latest

### ISSUE THREAD

**Issue by prietyc123** [openshift/release#6056]
/kind bug
/kind question

```
Running oc with args [oc --request-timeout 5m import-image java:8 --namespace=tietjasysz --from=registry.access.redhat.com/openjdk/openjdk-11-rhel8:latest --confirm]
[oc] error: tag latest failed: Internal error occurred: unsupported: This repo requires terms acceptance and is only available on registry.redhat.io
[oc] imagestream.image.openshift.io/java imported with errors
[oc] 
[oc] Name:			java
[oc] Namespace:		tietjasysz
[oc] Created:		Less than a second ago
[oc] Labels:			<none>
[oc] Annotations:		openshift.io/image.dockerRepositoryCheck=2019-11-21T13:10:35Z
[oc] Image Repository:	image-registry.openshift-image-registry.svc:5000/tietjasysz/java
[oc] Image Lookup:		local=false
[oc] Unique Images:		0
[oc] Tags:			1
[oc] 
[oc] 8
[oc]   tagged from registry.access.redhat.com/openjdk/openjdk-11-rhel8:latest
[oc] 
[oc]   ! error: Import failed (InternalError): Internal error occurred: unsupported: This repo requires terms acceptance and is only available on registry.redhat.io
[oc]       Less than a second ago
[oc] 
```
For more details check https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2402/pull-ci-openshift-odo-master-v4.1-integration-e2e-benchmark/41#1:build-log.txt%3A22549

## What did you expect to happen?

I was trying to pull and tag the image ```openjdk-11-rhel8:latest``` to my test script on prow and did not execute successfully. I can see the reason behind is there is no secret configured for registry ```registry.redhat.io```. Hence each time it looks for the image in the same registry fails with authentication error. cc_ @amitkrout @mohammedzee1000 

```
Running oc with args [oc --request-timeout 5m import-image java:8 --namespace=tietjasysz --from=registry.access.redhat.com/openjdk/openjdk-11-rhel8:latest --confirm]
[oc] error: tag latest failed: Internal error occurred: unsupported: This repo requires terms acceptance and is only available on registry.redhat.io
[oc] imagestream.image.openshift.io/java imported with errors
```

So is there any way which I can set to get over this authentication error? 

## What happened?

Erroring out due to authentication issue

## How can the error be reproduced?

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2402/pull-ci-openshift-odo-master-v4.1-integration-e2e-benchmark/41#1:build-log.txt%3A22549

**Comment by stevekuznetsov** [comment]
If your test requires authentication tokens for external systems, you should provide them using the [self-management system](https://github.com/openshift/release/tree/master/core-services/secret-mirroring#self-managed-secrets). Using [mirroring](https://github.com/openshift/release/blob/master/core-services/secret-mirroring/_mapping.yaml#L110-L115) you can then configure your job to [use the secret](https://github.com/openshift/release/blob/0929069937d7f42924fe5264d1c3d659d2715cbc/ci-operator/jobs/infra-image-mirroring.yaml#L332-L335).
