### ISSUE TITLE
You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#6076]
```json
{"component":"image","error":"query \"is:pr state:open repo:\\\"codeready-toolchain/host-operator\\\" repo:\\\"codeready-toolchain/api\\\" repo:\\\"codeready-toolchain/member-operator\\\" repo:\\\"codeready-toolchain/toolchain-common\\\" repo:\\\"codeready-toolchain/toolchain-e2e\\\" repo:\\\"codeready-toolchain/toolchain-operator\\\" repo:\\\"codeready-toolchain/registration-service\\\" label:\\\"lgtm\\\" label:\\\"approved\\\" -label:\\\"needs-rebase\\\" -label:\\\"do-not-merge/blocked-paths\\\" -label:\\\"do-not-merge/hold\\\" -label:\\\"do-not-merge/work-in-progress\\\" -label:\\\"do-not-merge/invalid-owners-file\\\"\", err: non-200 OK status code: 403 Forbidden body: \"{\\n  \\\"documentation_url\\\": \\\"https://developer.github.com/v3/#abuse-rate-limits\\\",\\n  \\\"message\\\": \\\"You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\\\"\\n}\\n\"","file":"prow/cmd/tide/main.go:221","func":"main.sync","level":"error","msg":"Error syncing.","time":"2019-11-25T18:04:04Z"}
```

---

This means that `tide` sent too many search queries, or too quickly, or they were too large. It should be transient and OK to ignore unless it hits many API calls at once.

**Comment by petr-muller** [comment]
So, what are we going to do with these? Shall triage inspect whether this is still happening, and if yes, reset the staleness and if no, just close it?

**Comment by stevekuznetsov** [comment]
This was more meant as a mechanism to communicate to the other triage role holders that this is fine. We can close it but we should all be generally comfortable understanding what this message means first

**Comment by petr-muller** [comment]
> This was more meant as a mechanism to communicate to the other triage role holders that this is fine. We can close it but we should all be generally comfortable understanding what this message means first

Yeah, I know. I just think that we may have fixed some of these (and those we could close), and some we should keep open for reference.
