### ISSUE TITLE
Not enough reviewers found in OWNERS files for files touched by this PR

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6092]
```json
{
   "level":"warning",
   "msg":"Not enough reviewers found in OWNERS files for files touched by this PR. 1/2 reviewers found.",
}
```

This is a configuration problem where `blunderbuss` (and other plugins that use `OWNERS` files) is enabled for a repo that either does not have `OWNERS` file, or does not have enough people in them. We enable these plugins org-wide for at least `openshift` org.

This is quite benign so it can be ignored.

/area triage

**Comment by petr-muller** [comment]
Another flavor of this is `Couldn't find/suggest approvers for each files. Unapproved: [""]`: that's coming from `approve` plugin,

```
author: "savitaashture"   
  component: "hook"   
  event-GUID: "2284f600-1101-11ea-8ff5-153e1632ff13"   
  event-type: "pull_request"   
  file: "prow/plugins/approve/approvers/owners.go:164"   
  func: "k8s.io/test-infra/prow/plugins/approve/approvers.Owners.GetSuggestedApprovers"   
  level: "warning"   
  msg: "Couldn't find/suggest approvers for each files. Unapproved: [""]"   
  org: "openshift-knative"   
  plugin: "approve"   
  pr: 78   
  repo: "knative-serving-operator"   
  url: "https://github.com/openshift-knative/knative-serving-operator/pull/78"   
```

**Comment by petr-muller** [comment]
This repo should be archived: https://github.com/openshift-knative/knative-serving-operator

**Comment by petr-muller** [comment]
Let's start to weed these out:

https://github.com/openshift/cucushift
https://github.com/openshift/scapresults
https://github.com/openshift/verification-tests
https://github.com/openshift/tektoncd-pipeline-operator
https://github.com/openshift/openshift-docs/
https://github.com/openshift/aos-cd-jobs
https://github.com/operator-framework/community-operators/

**Comment by stevekuznetsov** [comment]
I think it's always going to print this when we have repos without an OWNERS -- not sure we can special-case turn off a plugin.

**Comment by petr-muller** [comment]
Yeah - I was thinking we could at least reduce the log spam by fixing at least the active repos, perhaps over time. I think opting-out a plugin from a org-default would be useful feature even upstream (long-term, don't think we need to do it right now).
