### ISSUE TITLE
prow bumps: Cookie secret should be exactly 32 bytes [deck]

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6096]
This error/warning seems to occur during Prow bumps.

```
"level":"warning",
"msg":"Cookie secret should be exactly 32 bytes. Consider truncating the existing cookie to that length"
```

Not 100% sure about the impact, probably benign, but maybe we have some config to fix.

/area triage

**Comment by petr-muller** [comment]
This is probably related to this secret: https://github.com/openshift/release/blob/master/core-services/prow/03_deployment/deck.yaml#L177, which indeed isn't 32 bytes. I'm not sure what this cookie exactly is, so hard to say whether we should/can truncate it to the length the warning suggests.

**Comment by petr-muller** [comment]
Oh, this is a XSRF token... So I guess it should be safe to just generate a 32 byte secret here and get rid of this warning?

https://github.com/kubernetes/test-infra/blob/c7a125031726b6dc75d090aad74f8ff97e363811/prow/cmd/deck/main.go#L407-L409

**Comment by petr-muller** [comment]
I'm surprised we do not see this also for the `deck-internal` instance which is using a 43-character long generated string as this value: https://github.com/openshift/release/blob/master/core-services/prow/03_deployment/deck.yaml#L7

:confused:

**Comment by petr-muller** [comment]
/reopen

Appeared even today. I checked the `cookie` secret, it's updated and has the expected content that should no longer trigger this. I'll look into this.

**Comment by hongkailiu** [comment]
Appeared today.

```json
{
	"component": "deck",
	"file": "prow/cmd/deck/main.go:359",
	"func": "main.main",
	"level": "warning",
	"msg": "Cookie secret should be exactly 32 bytes. Consider truncating the existing cookie to that length",
	"time": "2020-01-02T21:30:38Z"
}
```
