### ISSUE TITLE
prow bumps: Post http://ghproxy/graphql: dial tcp <IP>: connect: no route to host [needs-rebase]

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6097]
This error/warning seems to occur during Prow bumps.

```
"error":"Post http://ghproxy/graphql: dial tcp 172.30.199.140:80: connect: no route to host",
"level":"error",
"msg":"Error during periodic update of all PRs.",
"plugin":"needs-rebase"
```

Looks like a symptom of ghproxy being bumped at the same time, goes away once it runs.

/area triage

**Comment by stevekuznetsov** [comment]
We should review our deployment strategy for `ghproxy` and ensure it has readiness and health checks, as well as that it exposes them at the right time. Perhaps we cannot do a seamless redeploy since we have a PV that can be mounted only to one Pod?
