### ISSUE TITLE
prow bumps: "GIGANTIC GITHUB QUERY, err: Post http://ghproxy/graphql: dial tcp <IP>: connect: no route to host" [tide]

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6098]
This error/warning seems to occur during Prow bumps.

```
"error":"query \"is:pr state:open GIGANTIC GITHUB QUERY, err: Post http://ghproxy/graphql: dial tcp 172.30.199.140:80: connect: no route to host",
"level":"error",
"msg":"Error syncing."
```

Looks like a symptom of ghproxy being bumped at the same time, goes away once it runs.

/area triage

**Comment by stevekuznetsov** [comment]
Yeah the `ghproxy` redeploy takes time .. but we have likely misconfigured it as it should not have downtime with an appropriate health/ready check and correct deployment strategy.
