### ISSUE TITLE
githuboauth: empty string or cannot convert to string. this probably means the options passed to GitHub don't match what was expected

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6100]
[Stackdriver](https://console.cloud.google.com/logs/viewer?authuser=1&project=openshift-ci-infra&folder&organizationId&minLogLevel=0&expandAll=false&timestamp=2019-11-26T13%3A50%3A40.844000000Z&customFacets&limitCustomFacetWidth=true&dateRangeStart=2019-11-26T07%3A51%3A47.102Z&dateRangeEnd=2019-11-26T13%3A51%3A47.102Z&interval=PT6H&resource=gce_instance&scrollTimestamp=2019-11-26T12%3A00%3A09.000000000Z&filters=jsonPayload.client%3AgithubOauth&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%224429328134516492605%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222019-11-26T11%3A58%3A55.000000000Z%22%0AinsertId%3D%2214eagng2fewnqh%22)

```
{
  client: "githuboauth"   
  component: "image"   
  error: "empty string or cannot convert to string. this probably means the options passed to GitHub don't match what was expected"   
  file: "prow/githuboauth/githuboauth.go:298"   
  func: "k8s.io/test-infra/prow/githuboauth.(*Agent).serverError"   
  level: "error"   
  msg: "Error Get secret state."   
 }
```

Not exactly sure what is happening here, I suspect it may be caused by someone accessing GH OAuth with a stale/clobbered cookie, or maybe from https://deck-ci.svc.ci.openshift.org/\

/area triage

**Comment by stevekuznetsov** [comment]
Yeah this shouldn't happen and looks like someone accessing the wrong Deck URL.

**Comment by petr-muller** [comment]
Can we just remove the `deck-ci` route?

**Comment by stevekuznetsov** [comment]
Yes, let's do that.

**Comment by hongkailiu** [comment]
```
{
 insertId: "1i40lygg1vd9yrq"  
 jsonPayload: {
  client: "githuboauth"   
  component: "deck"   
  error: "empty string or cannot convert to string. this probably means the options passed to GitHub don't match what was expected"   
  file: "prow/githuboauth/githuboauth.go:303"   
  func: "k8s.io/test-infra/prow/githuboauth.(*Agent).serverError"   
  level: "error"   
  msg: "Error Get secret state."   
 }
 labels: {
  compute.googleapis.com/resource_name: "fluentd-gcp-v2.1-tjjpt"   
 }
 logName: "projects/openshift-ci-infra/logs/kubernetes.deck-57fd778688-5n9sm_ci_deck"  
 receiveTimestamp: "2020-04-14T18:59:30.711561649Z"  
 resource: {
  labels: {
   instance_id: "2825824926546013618"    
   project_id: "openshift-ci-infra"    
   zone: "us-east1-c"    
  }
  type: "gce_instance"   
 }
 timestamp: "2020-04-14T18:59:27Z"  
}
```
