### ISSUE TITLE
unrecognized directory name (expected int64)

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6124]
[stackdriver](https://console.cloud.google.com/logs/viewer?authuser=1&project=openshift-ci-infra&minLogLevel=0&expandAll=false&timestamp=2019-11-27T11%3A32%3A17.845000000Z&customFacets&limitCustomFacetWidth=true&dateRangeEnd=2019-11-27T11%3A41%3A23.954Z&interval=PT6H&resource=gce_instance&scrollTimestamp=2019-11-27T11%3A33%3A14.000000000Z&filters=text%3A%22unrecognized%20directory%20name%20(expected%20int64)%22&dateRangeStart=2019-11-27T05%3A41%3A23.954Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%221044682240689639580%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222019-11-27T11%3A33%3A14.000000000Z%22%0AinsertId%3D%221pvqilog2n26qhy%22)

Code location: https://github.com/kubernetes/test-infra/blob/ee0721abf0b851369475deada46c728ab5eb7226/prow/cmd/deck/job_history.go#L219

```
component: "deck"   
  file: "prow/cmd/deck/job_history.go:219"   
  func: "main.gcsBucket.listBuildIDs"   
  level: "warning"   
  msg: "unrecognized directory name (expected int64): logs/release-openshift-origin-installer-launch-aws/logs/"   
```

/area triage

**Comment by stevekuznetsov** [comment]
There was some thought that this was due to us missing a `robots.txt` and having crawlers send us bad requests, but also this should not log at the warning level -- @petr-muller can you demote this to debug upstream? Users sending a bad request is not for an admin to look at.

**Comment by petr-muller** [comment]
ACK, will get to it.

**Comment by petr-muller** [comment]
This is not a crawler that accesses bad URLs. I can reliably reproduce this by following a `Job History` link for any periodic job, for example https://prow.svc.ci.openshift.org/job-history/origin-ci-test/logs/periodic-org-sync

For some reason this does not happen for postsubmit jobs, although the too are not under the `pr-logs` path in GCS.

Investigating further.

**Comment by petr-muller** [comment]
Oh, we really have these (the `logs` suffix is wrong, at this level we should have numerical-named directories). I suggest we just clean these up and leave the warnings, maybe just improve the log message and make it structured.

https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/logs/periodic-org-sync/logs/

**Comment by petr-muller** [comment]
```
gsutil ls -ld 'gs://origin-ci-test/logs/periodic-*/logs/initupload.txt'
      1197  2019-07-26T18:26:21Z  gs://origin-ci-test/logs/periodic-branch-protector/logs/initupload.txt
      1225  2019-10-17T21:00:47Z  gs://origin-ci-test/logs/periodic-image-mirroring-knative/logs/initupload.txt
      1225  2019-10-17T21:00:47Z  gs://origin-ci-test/logs/periodic-image-mirroring-kubefed/logs/initupload.txt
      1233  2019-10-17T21:00:47Z  gs://origin-ci-test/logs/periodic-image-mirroring-openshift/logs/initupload.txt
      1191  2019-07-26T18:15:17Z  gs://origin-ci-test/logs/periodic-ipi-deprovision/logs/initupload.txt
      2341  2019-10-17T21:00:54Z  gs://origin-ci-test/logs/periodic-openshift-release-merge-blockers/logs/initupload.txt
      1165  2019-07-26T18:21:31Z  gs://origin-ci-test/logs/periodic-org-sync/logs/initupload.txt
      1167  2019-10-17T21:04:06Z  gs://origin-ci-test/logs/periodic-retester/logs/initupload.txt
```

Looks like we had two bad days when these were created... Running `gsutil ls -d 'gs://origin-ci-test/logs/*/logs/'` now but it takes more time.

**Comment by petr-muller** [comment]
```console
$ gsutil ls -d 'gs://origin-ci-test/logs/*/logs/'
gs://origin-ci-test/logs/branch-ci-openshift-cluster-image-registry-operator-master-images/logs/
gs://origin-ci-test/logs/branch-ci-openshift-console-release-4.0-images/logs/
gs://origin-ci-test/logs/branch-ci-openshift-openshift-azure/logs/
gs://origin-ci-test/logs/branch-ci-operator-framework-operator-marketplace-master-images/logs/
gs://origin-ci-test/logs/openshift-release-master-config-bootstrapper/logs/
gs://origin-ci-test/logs/periodic-branch-protector/logs/
gs://origin-ci-test/logs/periodic-image-mirroring-knative/logs/
gs://origin-ci-test/logs/periodic-image-mirroring-kubefed/logs/
gs://origin-ci-test/logs/periodic-image-mirroring-openshift/logs/
gs://origin-ci-test/logs/periodic-ipi-deprovision/logs/
gs://origin-ci-test/logs/periodic-openshift-release-merge-blockers/logs/
gs://origin-ci-test/logs/periodic-org-sync/logs/
gs://origin-ci-test/logs/periodic-retester/logs/
gs://origin-ci-test/logs/release-openshift-ocp-installer-e2e-gcp-ovn-kubernetes-4.4/logs/
gs://origin-ci-test/logs/release-openshift-openshift-ansible-e2e-aws-scaleup-rhel7-4.3/logs/
gs://origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/logs/
gs://origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-serial-4.0/logs/
gs://origin-ci-test/logs/release-openshift-origin-installer-launch-aws/logs/
gs://origin-ci-test/logs/release-promote-openshift-machine-os-content-e2e-aws-4.1/logs/
gs://origin-ci-test/logs/release-promote-openshift-machine-os-content-e2e-aws-4.2/logs/
```

**Comment by petr-muller** [comment]
@stevekuznetsov anything against pwning these?
