### ISSUE TITLE
Error from upstream (GitHub) / Error from cache transport layer: context deadline exceeded

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6167]
Two messages fired at the same time, likely related: [1](https://console.cloud.google.com/logs/viewer?authuser=1&project=openshift-ci-infra&folder&organizationId&minLogLevel=0&expandAll=false&timestamp=2019-11-29T13%3A56%3A49.278000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&interval=PT1H&resource=gce_instance&scrollTimestamp=2019-11-29T13%3A59%3A58.000000000Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%223415647326450704092%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222019-11-29T13%3A50%3A27.000000000Z%22%0AinsertId%3D%221sdq6rsg2w90gd9%22&dateRangeStart=2019-11-29T13%3A07%3A53.834Z&dateRangeEnd=2019-11-29T14%3A07%3A53.834Z) | [2](https://console.cloud.google.com/logs/viewer?authuser=1&project=openshift-ci-infra&folder&organizationId&minLogLevel=0&expandAll=false&timestamp=2019-11-29T13%3A56%3A49.278000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&interval=PT1H&resource=gce_instance&scrollTimestamp=2019-11-29T13%3A59%3A58.000000000Z&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%223415647326450704092%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222019-11-29T13%3A50%3A27.000000000Z%22%0AinsertId%3D%221sdq6rsg2w90gda%22&dateRangeStart=2019-11-29T13%3A07%3A53.834Z&dateRangeEnd=2019-11-29T14%3A07%3A53.834Z)

```json
{
  cache-key: "https://api.github.com/repos/openshift/console/pulls/3550"   
  component: "ghproxy"   
  error: "context deadline exceeded"   
  file: "ghproxy/ghcache/coalesce.go:125"   
  func: "k8s.io/test-infra/ghproxy/ghcache.(*requestCoalescer).RoundTrip.func1"   
  level: "error"   
  msg: "Error from cache transport layer."   
 }
```
```json
{
  cache-key: "https://api.github.com/repos/openshift/console/pulls/3550"   
  component: "ghproxy"   
  error: "context deadline exceeded"   
  file: "ghproxy/ghcache/ghcache.go:167"   
  func: "k8s.io/test-infra/ghproxy/ghcache.upstreamTransport.RoundTrip"   
  level: "error"   
  msg: "Error from upstream (GitHub)."   
 }
```

/area triage

**Comment by stevekuznetsov** [comment]
Sometimes GitHub is slow to respond. We should ignore this one.
