### ISSUE TITLE
peribolos: openshift-priv needs more seats

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#6219]
```
 jsonPayload: {
  component: "peribolos"   
  file: "prow/cmd/peribolos/main.go:201"   
  func: "main.main"   
  level: "fatal"   
  msg: "Configuration failed: failed to configure openshift-priv members: 1 errors: [status code 422 not one of [200], body: {"message":"You must purchase at least one more seat to add this user as a member.","errors":[{"code":"no_seat","field":"user"}],"documentation_url":"https://github.com/organizations/openshift-priv/settings/billing/seats"}]"   
 }
```

/cc @openshift/openshift-team-developer-productivity-platform @openshift/openshift-team-developer-productivity-test-platform

**Comment by stevekuznetsov** [comment]
/area triage

This is from attempting to add `openshift-ci-robot`

**Comment by coverprice** [comment]
I added a seat and logged in as `openshift-ci-robot` to accept the invite.

If you need to add more users, let me know as I'll need to bump the seats again. FYI a seat is $9/mo, $108/yr, so let's keep seats as minimal as possible.
