### ISSUE TITLE
abuse detection mechanism tripping: `error checking user availability`

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6463]
This is of course similar to https://github.com/openshift/release/issues/6076, but in a different component, and we tripped this a *lot* today: maybe this path is not handling the back-off mechanism like it should? There are hundreds of hits in a single minute, causing the following (see the blue ramp-up):

![ghproxy](https://user-images.githubusercontent.com/712614/71082115-d7568400-2190-11ea-948c-0d8955dda3fc.png)

```
{
  author: "janepelladinesh"   
  component: "hook"   
  event-GUID: "71173480-2183-11ea-99c6-d3361b13e48d"
  level: "error"   
  msg: "error checking user availability: non-200 OK status code: 403 Forbidden body: "{\n  \"documentation_url\": \"https://developer.github.com/v3/#abuse-rate-limits\",\n  \"message\": \"You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\"\n}\n""   
  org: "operator-framework"   
  plugin: "blunderbuss"   
  pr: 1016   
  repo: "community-operators"   
  url: "https://github.com/operator-framework/community-operators/pull/1016"   
}
```

[stackdriver query](https://console.cloud.google.com/logs/viewer?project=openshift-ci-infra&advancedFilter=resource.type%3D%22gce_instance%22%0AjsonPayload.msg%3A%22error%20checking%20user%20availability%3A%20non-200%20OK%20status%20code%3A%20403%20Forbidden%20body%22%0A&customFacets=jsonPayload.msg&limitCustomFacetWidth=false) | [grafana board](https://grafana-prow-monitoring.svc.ci.openshift.org/d/d72fe8d0400b2912e319b1e95d0ab1b3/github-cache?orgId=1&from=1576657215139&to=1576668015140&var-token=93906c2a1935ce5070a23dcd606cddf0d8e14d7dc3d9adf5ae35661d9915436c&var-path=%2Fgraphql&var-status=200&var-user-agent=Go-http-client%2F1.1&var-range=30m)

/area triage

**Comment by stevekuznetsov** [comment]
We saw an enormous volume of calls to `/repositories` and `/graphql`.

**Comment by stevekuznetsov** [comment]
I need to re-do my user agent thing so we can see who is making the calls

**Comment by hongkailiu** [comment]
Similar log ... also saw an alert about the same time.
https://coreos.slack.com/archives/CHY2E1BL4/p1579125473041800


```jsonnet
{
 insertId: "h7httbfdnk28v"  
 jsonPayload: {
  author: "iamemilio"   
  component: "hook"   
  event-GUID: "359e7300-37e0-11ea-86fc-a09cf1da6aa1"   
  event-type: "pull_request"   
  file: "prow/plugins/blunderbuss/blunderbuss.go:335"   
  func: "k8s.io/test-infra/prow/plugins/blunderbuss.findReviewer"   
  level: "error"   
  msg: "error checking user availability: non-200 OK status code: 403 Forbidden body: "{\n  \"documentation_url\": \"https://developer.github.com/v3/#abuse-rate-limits\",\n  \"message\": \"You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.\"\n}\n""   
  org: "openshift"   
  plugin: "blunderbuss"   
  pr: 2932   
  repo: "installer"   
  url: "https://github.com/openshift/installer/pull/2932"   
 }
 labels: {
  compute.googleapis.com/resource_name: "fluentd-gcp-v2.1-s4hms"   
 }
 logName: "projects/openshift-ci-infra/logs/kubernetes.hook-7bcdd7b66d-nfggw_ci_hook"  
 receiveTimestamp: "2020-01-15T21:45:37.369740833Z"  
 resource: {
  labels: {
   instance_id: "4346492715139076760"    
   project_id: "openshift-ci-infra"    
   zone: "us-east1-c"    
  }
  type: "gce_instance"   
 }
 timestamp: "2020-01-15T21:45:32Z"  
}
```
