### ISSUE TITLE
periodic-label-sync takes 8 hours to execute and does not do what it logs

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6537]
See https://prow.svc.ci.openshift.org/job-history/origin-ci-test/logs/periodic-label-sync

The job started failing on 2019-12-11. Last successful execution is https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-label-sync/566 and first failing one is https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-label-sync/567. All passing runs in the past were very fast, taking tens of seconds or just over a minute. The failing runs are all hitting the 8 hours timeout.

The preliminary investigation:

1. The tool seems to be throttled. In the investigated run https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-label-sync/587, while executing, the logged GH interactions followed this pattern: there are periods where the tool logs an action each 11-13 seconds, separated by pauses that take ~8 minutes and during which no actions are being done. 
2. The culprit seems to be merging https://github.com/openshift/release/pull/6327 which enrolled whole `openshift-kni` organization into label-sync. This means many label-related operations should have been done on all repos in `openshift-kni`, which could lead to throttling in the next run.
3. Still, `openshift-kni` only has 20 repos, and the tool claims that each repo needs 60 changes (https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-label-sync/587#1:build-log.txt%3A2624). Even with throttling, running ~20 days for 8 hours each day should already work through that action backlog already: maybe the tool could hit a timeout for few days, but not this long.
4. It looks like the actions done by the tool are not coming through. The investigated run claims to start working on the `openshift-kni/router` repo [here](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-label-sync/587#1:build-log.txt%3A2642) and to finish [here](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/periodic-label-sync/587#1:build-log.txt%3A2763), ~9 minutes later, but https://github.com/openshift-kni/router/labels (as of now) still does not show any changes. So it looks like that for some reason the sync tool attempts to do the same work all over again every day, never succeeds, and gets throttled in the process.

/area triage

**Comment by stevekuznetsov** [comment]
Let's remove the org from the list and ensure we have appropriate permissions on the `openshift-kni` org as well as making sure no other automation is touching that org.

**Comment by petr-muller** [comment]
It looks like at least some repos received the update: https://github.com/openshift-kni/baremetal-deploy/labels

**Comment by petr-muller** [comment]
@stevekuznetsov ok let's revert https://github.com/openshift/release/pull/6327, I'll prep the PR

If it were the permissions, I would still expect the sync tool to log the failure - maybe it throws it away (and we should fix it) or GH API is stupid by pretending all is fine? It does not seem to be caused by other automation on `openshift-kni` - the repos seem to have just the default GH labels, does not make sense to have automation maintaining these.
