### ISSUE TITLE
assign: Error handling GenericCommentEvent

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6581]
```
{
  component: "hook"   
  error: "status code 404 not one of [201], body: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue"}"   
  event-type: "issue_comment"   
  level": "error"   
  msg: "Error handling GenericCommentEvent."   
  plugin: "assign"   
 }
```

This is caused by people doing `/assign <someone> with additional test`, like https://github.com/openshift/console/pull/3765#issuecomment-571508312 

It is benign, but it should be improved upstream (I'll file a bug there if it does not exist already).

/area triage

**Comment by stevekuznetsov** [comment]
This used to post a comment back to the PR saying "_take a look_ could not be assigned" ... regression in Prow, should open test-infra issue
