### ISSUE TITLE
bugzilla: Unexpected error adding external tracker bug to Bugzilla bug: response code 502 not 200

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#6583]
We recently seem to receive 502s from RH Bugzilla occasionally when the bugzilla plugin tries to interact with it. I have received 502s from it even in my browser, so it's likely not related at all to anything we own. The downside of this is that it leaves BZs in wrong state, which needs to be manually fixed. These failures are at surfaced to GH as a comment, so at least they are not silent:

https://github.com/openshift/cluster-kube-scheduler-operator/pull/196#issuecomment-571569135
(notice that neither later interaction nor `/bugzilla refresh` linked the PR to https://bugzilla.redhat.com/show_bug.cgi?id=1788151)

```
{
  component: "hook"   
  error: "response code 502 not 200"   
  event-type: "pull_request"   
  level: "warning"   
  msg: "Unexpected error adding external tracker bug to Bugzilla bug."   
  org: "openshift"   
  plugin: "bugzilla"   
}
```

/area triage

**Comment by stevekuznetsov** [comment]
Do you think we should re-try in these cases? We should probably see what the error payload actually looks like

**Comment by petr-muller** [comment]
Yeah, retry with a delay would help in some cases, but not all. We could also make the plugin fully reconcile BZ into the desired state on `/bugzilla refresh`, or provide manual commands to make the plugin retry specific actions on demand (to make manual fixups easier).

**Comment by stevekuznetsov** [comment]
We've seen a 502 once in the last month, this is likely not worth it.

/close
