### ISSUE TITLE
publishing bot deployment automation is required

### ISSUE THREAD

**Issue by kargakis** [openshift/release#672]
I can't find any manifests/automation for setting up the publishing bots inside this repo. We need to check them in and automate their creation similar to what has already been done for [`prow`](https://github.com/openshift/release/tree/master/cluster/ci/config/prow), otherwise in the next redeployment of the CI cluster, whoever wants them to run needs to recreate them manually. :)

TODOs:
- [ ] Check-in [roles](https://github.com/openshift/release/blob/master/cluster/ci/config/roles.yaml) for folks who are supposed to manage these namespaces/bots.
- [ ] Add publishing bot manifests under a `publishingbots` directory in [cluster/ci/config](https://github.com/openshift/release/tree/master/cluster/ci/config)
- [ ] Add a makefile target that automates the publishing bots creation in the desired namespaces.

/assign @sttts @mfojtik

**Comment by sttts** [comment]
👍

**Comment by mfojtik** [comment]
agree, will do this

**Comment by kargakis** [comment]
FYI, we are doing a cluster migration today or tomorrow

**Comment by sttts** [comment]
Added a target to install the storage class.

For the Kubernetes instance of the bot I would prefer to keep the coupling with the OpenShift infra at a minimum. Our mid term goal is to move this to a CNCF cluster.

IMO manual deployment is fine for that. We can add namespaces/projects though via the Makefile, and set permission to the relevant people to access it.

**Comment by stevekuznetsov** [comment]
@sttts is any of this work done yet? Docs for deployment will be nice when this moves out to CNCF hardware

**Comment by sttts** [comment]
Yes, on CNCF hardware I would like to document or even better to automate the deployment much better so maintenance can be shared.
