### ISSUE TITLE
Automate prometheus installation in the CI cluster

### ISSUE THREAD

**Issue by kargakis** [openshift/release#724]
Things we should automate in the CI cluster re Prometheus:
- [ ] Prometheus installation
- [ ] laying our ci config on top of the existing config
  - [update kubernetes-service-endpoints to allow prometheus scraping of the ci namespace](https://github.com/openshift/origin/blob/229ee35be209a49f73873edf1bc23065aa25b511/examples/prometheus/prometheus.yaml#L615)
  - deploy [ci rules](https://github.com/openshift/release/blob/master/projects/prometheus/prometheus.rules.yaml)

**Comment by kargakis** [comment]
I am fine with it being a test bed but we also use it to gather stuff for CI and need to iterate over those metrics/alerts.

**Comment by stevekuznetsov** [comment]
@smarterclayton what's the progress here?

**Comment by stevekuznetsov** [comment]
OK, sounds like this is done then.
/close
