### ISSUE TITLE
hook won't start tests for kargakis/acs-engine

### ISSUE THREAD

**Issue by kargakis** [openshift/release#725]
It used to work. Seems to be the only repo that doesn't work anymore :(

Testing in https://github.com/kargakis/acs-engine/pull/58

The hook is delivered but no prowjob is created. No idea what's wrong but we can get around it with labeling lgtm and forcing tide to test the PR.

@stevekuznetsov @bbguimaraes if you have time to look at it

**Comment by stevekuznetsov** [comment]
We're not seeing webhooks land for that PR -- `hook` right now has only the record of the PR being created:

```
[
{"author":"kargakis","component":"hook","event-GUID":"46425880-3291-11e8-85ae-53f53cd5fa41","event-type":"pull_request","level":"info","msg":"Pull request opened.","org":"kargakis","pr":58,"repo":"acs-engine","time":"2018-03-28T14:06:56Z","url":"https://github.com/kargakis/acs-engine/pull/58"}
]
```

**Comment by kargakis** [comment]
Ok, old plugins configmap. I should see that coming, we were running deck with the garrish background until I did some updates into the main configmap and it turned back to grey.
