### ISSUE TITLE
Kill all jobs not run by prow

### ISSUE THREAD

**Issue by kargakis** [openshift/release#732]
Please do

Mainly travis at this point; there is also a fedora/27/atomic in openshift-ansible. Unclear where it runs. 

@stevekuznetsov @bbguimaraes

**Comment by stevekuznetsov** [comment]
`fedora/*/atomic` is not going away in o-a

**Comment by kargakis** [comment]
Is it something we cannot move to run in prow?

**Comment by stevekuznetsov** [comment]
Don't think so, @sdodson can we get a contact for that status?

**Comment by sdodson** [comment]
@jlebon is the contact for that job. It relies on Fedora's CI infra.

**Comment by kargakis** [comment]
Is it Jenkins behind the covers? We can still use prow and trigger the job in its original place as long as we can get a bot account there.

**Comment by jlebon** [comment]
`fedora/27/atomic` uses PAPR: https://github.com/projectatomic/papr.
PAPR doesn't run in the Fedora infra, but on an internal OpenStack instance (though we're working towards migrating it to OCP).

I'm not sure how easy it'd be to make a prow --> PAPR compat shim. Seems like the easiest thing to do would be to just move over to Prow completely instead. It's fairly straightforward: it provisions three FAH27 nodes and runs the openshift-ansible installer.

**Comment by stevekuznetsov** [comment]
@jlebon I poked around the repo for a bit but could not find this -- how is all that triggered? If we can clone the PAPR repo into a container and run the scripts, providing the env vars as necessary, that seems like a good shim.

**Comment by jlebon** [comment]
It's triggered by GHPRB/SCM plugins in an internal Jenkins instance which then fire up PAPR. IOW, PAPR isn't a service that waits for triggers, it's a "one-shot" thing that runs tests in an environment which assumes it has access to e.g. an OpenStack instance for deploying VMs and AWS credentials for publishing logs.

Does the Prow infra have any facilities for provisioning multiple VMs? One nice thing PAPR provides is easy access to the latest FAH27 images, though there are symlinks that exist to make downloading those really convenient: https://fedoraproject.org/wiki/Cloud#Fedora_Cloud_Atomic_Image_Download_Links (which is what the PAPR infra uses to keep the OpenStack images up to date).

**Comment by stevekuznetsov** [comment]
All Prow does do is the triggering -- which is why I was asking about how PAPR was triggered. If we provided the secrets necessary and put the PAPR scripts into a container (and wrote a shim that converted Prow directives into GHPRB environment variables) then PAPR would have no idea that it was being triggered by Prow, right?

**Comment by jlebon** [comment]
> All Prow does do is the triggering

Heh, sorry. I meant the underlying infra where tests actually run. IIRC, tests run in Jenkins and VMs are provisioned in EC2, right?

> If we provided the secrets necessary and put the PAPR scripts into a container...

Assuming it's running somewhere with access to the internal OpenStack instance, that *should* work, yes. But I'm still not sure it's worth the hassle of going through with this vs. setting up another test which does the same thing in the same way all the other tests run. Note we do publish AMIs for each FAH27 release: https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2018-March/msg00066.html, so there's opportunity for better alignment here.

Another issue is that we're in the midst of a huge transition ourselves with PAPR and it's likely things will change in the future re. how it's triggered and how test environments are provisioned: https://github.com/projectatomic/papr/issues/62.

**Comment by sdodson** [comment]
The test now works more often than not, at least on master branch. Is there still a compelling reason to make changes? I can kill off the travis test.

**Comment by kargakis** [comment]
> The test now works more often than not, at least on master branch. Is there still a compelling reason to make changes? I can kill off the travis test.

Eventually we should migrate it.

**Comment by stevekuznetsov** [comment]
The most compelling reason is that you can't `/retest` and use other commands so you need to remember which statuses come from where and how to interact. Plus, a bunch of the automation only works well with statuses it controls. For instance, this job was an issue because we needed to disable the job and couldn't auto-mark the status contexts as green or remove them, as we did not post the context.

**Comment by jlebon** [comment]
This came up in https://github.com/projectatomic/paci/pull/15. I definitely agree that making prow take over the PAPR tests is the right thing to do for various reasons. Digging a bit deeper into the current CI config, it doesn't seem like any of the tests currently provision an Atomic Host? (Looking at the `os:` keys in `sjb/config/common/test_cases`.)

Has anyone tried running `oct provision` pointed at an Atomic Host AMI? Getting this to work nicely would align with https://github.com/openshift/os as well (though IIUC there are still discussions about whether to focus more on `kola` or `oct` for RHCOS CI).

**Comment by jlebon** [comment]
If we're fine with not homogenising on `oct` for all the tests, an easier avenue is to replace GHPRB with Prow for `openshift/openshift-ansible` -- this means that Prow would trigger the PAPR job on the internal Jenkins instance.

One thing I'm unsure of is -- is Prow the one that updates the CI status if the Jenkins job finishes successfully? Or is it that done by `oct` or something else that runs during the Jenkins job itself? If the latter, then it'd be easy to do this since PAPR also expects to be the one that posts the CI status. If the former... it would require some changes so that PAPR *doesn't* update GitHub and instead reflects pass/fail through its exit code (which right now it doesn't; `rc != 0` means infra failure).

**Comment by stevekuznetsov** [comment]
@jlebon we are OK not requiring `oct` for all. I would be worried about the intricacies of contacting that internal Jenkins master -- is it inside of the firewall? 

`prow` does also expect `rc != 0` and expects to set the statuses on a PR. I think right now we do just need to weigh the costs. I think there are clear benefits to the `o-a` developers for having one integrated test interface with one set of commands to remember, etc, but if this is not an active area of concern we should just keep the status quo. It seems like some non-trivial work will be required to port the job.

**Comment by stevekuznetsov** [comment]
@jlebon we are OK not requiring `oct` for all. I would be worried about the intricacies of contacting that internal Jenkins master -- is it inside of the firewall? 

`prow` does also expect `rc != 0` and expects to set the statuses on a PR. I think right now we do just need to weigh the costs. I think there are clear benefits to the `o-a` developers for having one integrated test interface with one set of commands to remember, etc, but if this is not an active area of concern we should just keep the status quo. It seems like some non-trivial work will be required to port the job.

**Comment by jlebon** [comment]
> is it inside of the firewall?

Yeah, so that'd be another hurdle.

> if this is not an active area of concern we should just keep the status quo

Agreed. I might still investigate switching from GHRPB to Prow for the new PAPR infra (the one which runs on top of OpenShift in CentOS CI) because dealing with GHPRB is a pain.

**Comment by vrutkovs** [comment]
For openshift-ansible it not necessary to run tests in OpenStack - AWS would be fine too

**Comment by stevekuznetsov** [comment]
Sure -- if the maintainers of those tests want to rewrite them so they can handle Prow triggers and can run on AWS / GCP we can run them using our infra.

**Comment by sdodson** [comment]
The PAPR jobs have since been disabled for openshift-ansible. travis-ci should be the only test not under prow management now.

**Comment by stevekuznetsov** [comment]
I think this is finished
/close
