### ISSUE TITLE
Periodic runs for the needs-rebase plugin are brokey

### ISSUE THREAD

**Issue by kargakis** [openshift/release#764]
```
{"error":"unexpected status: 502 Bad Gateway","level":"error","msg":"Error during periodic update of all PRs.","plugin":"needs-rebase","time":"2018-04-07T20:17:54Z"}
```
@stevekuznetsov

**Comment by tnozicka** [comment]
still broken :/
/assign @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Seems like upstream is having the same issue /cc @cjwagner @bentheelder

I know we have:

 - other `prow` components like `tide` that hit GitHub GraphQL API with no issue
 - REST calls to GitHub from `needs-rebase` that work with no issue

I think something in the payload or query for this specific interaction is failing us somewhere and we should probably ask GitHub support about why we're getting a 502.

**Comment by kargakis** [comment]
Closing in favor of https://github.com/kubernetes/test-infra/issues/8070
