### ISSUE TITLE
jenkins-operator: Operation cannot be fulfilled on <pj>: the object has been modified

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#7679]
```
  component: "jenkins-operator"   
  error: "errors syncing: [Operation cannot be fulfilled on prowjobs.prow.k8s.io <id>: the object has been modified; please apply your changes to the latest version and try again], errors reporting: []"   
  file: "prow/cmd/jenkins-operator/main.go:229"   
  func: "main.main.func2"   
  level: "error"   
  msg: "Error syncing."   
```

/area triage

I wonder if this is some interaction of jenkins-operator with crier?

Occurences: [1](https://console.cloud.google.com/logs/viewer?authuser=1&folder=true&organizationId=true&project=openshift-ci-infra&minLogLevel=0&expandAll=false&timestamp=2020-03-16T11%3A19%3A06.700000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%229042192309672040084%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222020-03-16T11%3A03%3A13.000000000Z%22%0AinsertId%3D%22tfd7srg136l1l5%22&dateRangeStart=2020-03-16T05%3A42%3A39.656Z&dateRangeEnd=2020-03-16T11%3A42%3A39.656Z&interval=PT6H&scrollTimestamp=2020-03-16T11%3A31%3A38.000000000Z) | [2](https://console.cloud.google.com/logs/viewer?authuser=1&folder=true&organizationId=true&project=openshift-ci-infra&minLogLevel=0&expandAll=false&timestamp=2020-03-16T11%3A19%3A06.700000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%229042192309672040084%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222020-03-16T10%3A34%3A48.000000000Z%22%0AinsertId%3D%22atvgkxg1hnvvy4%22&dateRangeStart=2020-03-16T05%3A42%3A39.656Z&dateRangeEnd=2020-03-16T11%3A42%3A39.656Z&interval=PT6H&scrollTimestamp=2020-03-16T11%3A31%3A38.000000000Z) | [3](https://console.cloud.google.com/logs/viewer?authuser=1&folder=true&organizationId=true&project=openshift-ci-infra&minLogLevel=0&expandAll=false&timestamp=2020-03-16T11%3A19%3A06.700000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%229042192309672040084%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222020-03-16T09%3A58%3A16.000000000Z%22%0AinsertId%3D%22p92rvxg1pbrbof%22&dateRangeStart=2020-03-16T05%3A42%3A39.656Z&dateRangeEnd=2020-03-16T11%3A42%3A39.656Z&interval=PT6H&scrollTimestamp=2020-03-16T11%3A31%3A38.000000000Z) | [4](https://console.cloud.google.com/logs/viewer?authuser=1&folder=true&organizationId=true&project=openshift-ci-infra&minLogLevel=0&expandAll=false&timestamp=2020-03-16T11%3A19%3A06.700000000Z&customFacets=jsonPayload.msg&limitCustomFacetWidth=false&advancedFilter=resource.type%3D%22gce_instance%22%0Aresource.labels.instance_id%3D%229042192309672040084%22%0Aresource.labels.zone%3D%22us-east1-c%22%0Aresource.labels.project_id%3D%22openshift-ci-infra%22%0Atimestamp%3D%222020-03-16T09%3A02%3A13.000000000Z%22%0AinsertId%3D%221bqhejig1obkbj4%22&dateRangeStart=2020-03-16T05%3A42%3A39.656Z&dateRangeEnd=2020-03-16T11%3A42%3A39.656Z&interval=PT6H&scrollTimestamp=2020-03-16T11%3A31%3A38.000000000Z)

**Comment by alvaroaleman** [comment]
Not intearction but yeah, its presumably crier updating the prowjob, causing our update to fail

We could probably change the jenkins operator to do patch instead, then this shouldn't happen anymore.

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/kubernetes/test-infra/pull/16839, not sure why the `fixes` directive doesn't work cross repo.
/close
