### ISSUE TITLE
can i use just the prow part of openshift/release/core-services?

### ISSUE THREAD

**Issue by tseelbach** [openshift/release#8625]
/kind question

I'm trying to setup prow on an OpenShift 4.3 cluster to test some components on top of OpenShift.  The default config in https://github.com/kubernetes/test-infra/tree/master/prow doesn't work in OCP, and i stumbled upon the config here in core-services/prow.  Is there an easy way to use this config to help me get prow working in my cluster?   the 02_config/_config.yaml is oriented toward multiple clusters, not a single cluster so i'm not sure what i'm asking is possible, or even a good approach.  Or should i be asking this over in kubernetes/test-infra? or somewhere else?
Thank you!

**Comment by stevekuznetsov** [comment]
Hey! Which part of the test-infra manifest was not working for you on OCP? We run Prow on OpenShift without issues, and please feel free to use our manifests however you wish.

**Comment by tseelbach** [comment]
Thanks Steve!  I followed manual process: https://github.com/kubernetes/test-infra/blob/master/prow/getting_started_deploy.md#manual-deployment
I already have a cluster, so skipped that step.  I created the secrets for hmac and oauth.
Then i cloned the repo (not listed in getting_started_deploy.md), and did 
    kubectl apply -f config/prow/cluster/starter.yaml

I see 2 problems.  Missing address on ingress, and error starting horologium:

then:
oc get deployments
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
deck               2/2     2            2           21h
hook               2/2     2            2           21h
horologium         0/1     1            0           21h
plank              1/1     1            1           21h
sinker             1/1     1            1           21h
statusreconciler   1/1     1            1           21h
tide               1/1     1            1           21h

oc get pods
NAME                                READY   STATUS             RESTARTS   AGE
deck-7b6f9f4bc9-4869q               1/1     Running            0          21h
deck-7b6f9f4bc9-tspkk               1/1     Running            0          21h
hook-55547d47f-dcqlk                1/1     Running            0          21h
hook-55547d47f-jpqlp                1/1     Running            0          21h
horologium-bb84b755-khqdn           0/1     CrashLoopBackOff   251        21h
plank-6976c7c6d4-sml5j              1/1     Running            0          21h
sinker-6cd9556c66-c6jvv             1/1     Running            0          21h
statusreconciler-69dccc5d47-xxc2s   1/1     Running            0          21h
tide-75789f48cc-jt5c4               1/1     Running            0          21h

[root@again-inf ~]# oc logs horologium-bb84b755-khqdn
{"component":"horologium","error":"a dry-run was requested but required flag -deck-url was unset","file":"prow/cmd/horologium/main.go:77","func":"main.main","level":"fatal","msg":"Invalid options","time":"2020-04-29T11:48:52Z"}

kubectl get ingress ing
NAME   HOSTS   ADDRESS   PORTS   AGE
ing    *                 80      21h
  
We could cancel this issue here and post it in kubernetes/test-infra if you think that is better....

**Comment by tseelbach** [comment]
I opened issue in test-infra https://github.com/kubernetes/test-infra/issues/17503
 Any advice, however small, to get me moving forward would be appreciated.  I googled the error many ways but so far have not figured out what config i need to change...
