### ISSUE TITLE
Bypass prow job initial clone for ci-operator

### ISSUE THREAD

**Issue by smarterclayton** [openshift/release#892]
For ci-operator we want to bypass the initial clone (for origin saves 3-4 wasted minutes).  What's the minimal way to do that for a prow job where we want the other decorators?  I have origin unit ready to cut over to ci-operator and that's the last remaining loose end.

@kargakis @stevekuznetsov

**Comment by stevekuznetsov** [comment]
We should allow for skipping the clone in Prow config first-class
