### ISSUE TITLE
tide unreachable after redeploy until manually hit?

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/release#911]
We see all `deck` instances failing with:

```
 {"agent":"tide","component":"deck","error":"Get http://tide/: dial tcp 172.30.173.237:80: getsockopt: connection refused","level":"error","msg":"Updating pool.","time":"2018-06-05T15:40:10Z"}
```

After a redeploy of the system, until I go to a `deck` instance and navigate to the Tide Status page ... then everything works fine. Seen this twice now. What on earth?

/cc @smarterclayton @kargakis

**Comment by kargakis** [comment]
Reopen if still relevant
