### ISSUE TITLE
openshift/knative-client has configuration for a branch that does not exist

### ISSUE THREAD

**Issue by droslean** [openshift/release#9283]
{"component":"dptp-controller-manager","controller":"promotionreconciler","error":"failed to get current git head for imageStreamTag: failed to get ref: status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/git/refs/#get-a-reference\"}","file":"/go/src/github.com/openshift/ci-tools/pkg/controller/promotionreconciler/reconciler.go:149","func":"github.com/openshift/ci-tools/pkg/controller/promotionreconciler.(*reconciler).Reconcile","level":"error","msg":"Reconciliation failed","name":"knative-v0.14.0:kn-cli-artifacts","namespace":"openshift","time":"2020-05-25T09:16:49Z"}

/cc @openshift/openshift-team-developer-productivity-test-platform

**Comment by alvaroaleman** [comment]
/retitle "Promotionreconciler got 404 from github for knative repo"

**Comment by stevekuznetsov** [comment]
In reality what has happened here is that there is a `openshift/knative-client@release-v0.14.0` configuration but no such branch on the remote. @dsimansk you added this in 7d06bb67163bea15bb073847f52bf7f75465dbf5 about a month ago -- would you be OK with us removing the configuration while the branch does not exist?

**Comment by petr-muller** [comment]
Hit this for openshift/cluster-api/heads/openshift-4.2, opened https://github.com/openshift/release/pull/9564 to address.
