### ISSUE TITLE
crier: Failed to update report state on prowjob

### ISSUE THREAD

**Issue by petr-muller** [openshift/release#9567]
```json
{
   "component":"crier",
   "container_name":"crier",
   "error":"failed to wait for updated report status to be in lister: timed out waiting for the condition",
   "file":"prow/crier/controller.go:296",
   "func":"k8s.io/test-infra/prow/crier.(*Controller).processNextItem",
   "host":"ip-10-0-129-29",
   "jobName":"pull-ci-openshift-release-master-ci-operator-config",
   "jobStatus":"triggered",
   "level":"error",
   "msg":"Failed to update report state on prowjob",
   "multiline_tag":"F",
   "object_uid":"694d3b3a-fcfc-47e1-b0e5-6488a081441a",
   "pod_name":"crier-6645f89964-ckbln",
   "pod_namespace":"ci",
   "prowjob":"ci/5b17e972-aa50-11ea-94e4-0a580a810426",
   "reporter":"github-reporter",
   "source_type":"kubernetes",
   "stream":"stderr",
   "time":"2020-06-09T12:54:37Z"
}
```

Unsure about the impact, but it looks like 
1. We only started to see this recently (see the histogram, there's a noticeable ramp-up on Jun 06 - and there *are* occurrences before that, so it's not a new log message or an artifact of log rotation)
2. Erick Fejta reported a similar thing in upstream on Jun 01 https://github.com/kubernetes/test-infra/issues/17790

/area triage

**Comment by petr-muller** [comment]
![crier-timeout](https://user-images.githubusercontent.com/712614/84150762-9ca81700-aa62-11ea-859c-7030510675ec.png)

**Comment by alvaroaleman** [comment]
Presumably https://github.com/kubernetes/test-infra/commit/01fd07142c61b3f89246cbad83a23ae4251e04f5 , before that change the error for the same issue was `failed to update report state again, give up`

**Comment by alvaroaleman** [comment]
Fixes in https://github.com/kubernetes/test-infra/pull/17891
/close
