### ISSUE TITLE
[Question] What does "workflow: openshift-e2e-aws" mean and how can I run it in my local environment?

### ISSUE THREAD

**Issue by xkwangcn** [openshift/release#9581]
/kind question

## What did you expect to happen?

From here https://github.com/openshift/release/blob/master/ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml, I want know what "workflow: openshift-e2e-aws" means, and I will run it in my local environment to ensure its CI works fine.

## Is there anything else we need to know?

I find the https://github.com/openshift/release/blob/master/ci-operator/config/openshift/oauth-proxy/openshift-oauth-proxy-master.yaml is the configuration of oauth-proxy `ci/prow/e2e-aws` : https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_oauth-proxy/176/pull-ci-openshift-oauth-proxy-master-e2e-aws/170, I want to know what test it contains in this job, and how can I run it to support the CI job works in my environment. My environment's arch is s390.

**Comment by xkwangcn** [comment]
Could you help me about this question? Thank you very much.

**Comment by petr-muller** [comment]
`openshift-e2e-aws` is a CI workflow in the OpenShift CI, and a workflow is a concept in OpenShift CI putting together setup-test-cleanup sequences from user-provided test workflows. 

You can find documentation about the concepts here: https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/help
The UI contains a [directory](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/) of all available workflows/chains/steps: you can find information about this specific workflow here: https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/workflow/openshift-e2e-aws

We do not support running the e2e workloads locally (too many moving parts are invoved for us to be able to support it), but you can see that the workflow ends up running the [openshift-e2e-test](https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/reference/openshift-e2e-test) step, and you can see that eventually the step runs the `openshift-tests` binary in the `tests` image (the tests image is a normal image built AFAIK after merges to https://github.com/openshift/origin)

**Comment by xkwangcn** [comment]
@petr-muller Hello, Petr, Very very helpful info, thank you very much. 

I will try to understand more details about `openshift-e2e-aws`, now I have a simple question:
It seems https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/reference/openshift-e2e-test is the code that `openshift-e2e-aws` run? But I didn't see what its relationship with oauth-proxy, it seems that `openshift-e2e-aws` is a common job for many projects? How can I judge if my test project can support the CI job? Maybe I can read https://ci-operator-configresolver-ui-ci.apps.ci.l2s4.p1.openshiftapps.com/reference/openshift-e2e-test get some answers, and to understand if my project could running in the openshift environment? 
Could you give me some advice?

This is my first work involving CI, so many basic questions may also be confusing, thank you for your patience to reply.
