### ISSUE TITLE
failed to initialize build cache at /.cache : Permission denied

### ISSUE THREAD

**Issue by akram** [openshift/release#9748]
It seems that our jobs are affected by this issue:
https://go-review.googlesource.com/c/go/+/122487/

When go is run with a user with unknown home (as it could be the case while using cri-o), go will default $HOME to / which causes issues while creating $HOME/.cache directory as `go test` or `go list` do.

The workaround:
```
GOCACHE=off
```
or 
```
GOCACHE=/tmp/
```

**Comment by abmomen** [comment]
having save issue on mac
